Revert "Update espresso to 3.5.1"
This reverts commit a493814d8f5741ecbf1508692cb0078d34f22605.

Reason for revert:
androidx_fetchall.py seems to be giving an error:

java.lang.AssertionError: No dependency collected for artifact checker-compat-qual. Expression: dep. Values: dep = null

I suspect that will cause
https://skia-autoroll.corp.goog/r/google3-libs-clank-internal-apps

to fail on its next roll.


Original change's description:
> Update espresso to 3.5.1
>
> Should update code to {{androidx_dependency_version}} after this lands successfully.
>
>
> Change-Id: I84113ee44f91127e45db3617951913128a2dd55a
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5405915
> Reviewed-by: Peter Wen <wnwen@chromium.org>
> Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1279851}

Change-Id: I2122998e710d955dded34c38a105ab451b8c144f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5406062
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1280023}