Revert "[M122] Revert "[DataTransfer] Check values of items in clipboard item data on `ResolveRead`""
This reverts commit 3e03437c56088f7ef6d623cf54863cc55d18ee44.

Reason for revert: Breaks compile on 6253: https://ci.chromium.org/ui/p/chrome/builders/official/win-clang/7739/overview - ../../third_party/blink/renderer/modules/clipboard/clipboard_promise.cc(376,29): error: no matching function for call to 'Cast'

Original change's description:
> [M122] Revert "[DataTransfer] Check values of items in clipboard item data on `ResolveRead`"
>
> Cherry pick of revert CL (+ temporary fix) to the branch position
> which the initial crash occurred (https://chromiumdash.appspot.com/commit/c2921140654206520043ed4e6b95ce8957e7f0e7)
>
> This reverts commit d4070088bb3512f6dbf09d4af971a4d916bc5448 and adds new code to fix the crash (as per c#7 of crbug.com/1517823).
>
> Reason for revert: The spec for this feature is unclear, and more
> clarification needs to be reached via a spec issue before relanding
> this change / a similar change to handle write/read with empty data
> from the clipboard.
>
> Original change's description:
> > [DataTransfer] Check values of items in clipboard item data on `ResolveRead`
> >
> > Addresses the cause of the crash in crbug/1517823 by only appending item(s)
> > to the clipboard item list, when their value is not null.
> >
> > Bug: 1517823
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5194243
> > Reviewed-by: Evan Stade <estade@chromium.org>
> > Commit-Queue: Christine Smith <christinesm@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#1246689}
>
> (cherry picked from commit 1e4c6fce318f438fe2248d0f88dd52883d1d31ac)
>
> Bug: 1517823
> Change-Id: I71d91c56efcfa2dd4f3076768b7a21fd96981029
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5228279
> Commit-Queue: Christine Hollingsworth <christinesm@chromium.org>
> Reviewed-by: Evan Stade <estade@chromium.org>
> Cr-Commit-Position: refs/branch-heads/6253@{#11}
> Cr-Branched-From: b99fcea52ab997bc6cfe057c82f7c6f869d44195-refs/heads/main@{#1247893}

Bug: 1517823
Change-Id: Iffc0802403f3a36ffa6c5fc55ac59e9f00d485e7
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5237865
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Rouslan Solomakhin <rouslan@chromium.org>
Reviewed-by: Christine Hollingsworth <christinesm@chromium.org>
Commit-Queue: Joshua Pawlicki <waffles@chromium.org>
Cr-Commit-Position: refs/branch-heads/6253@{#16}
Cr-Branched-From: b99fcea52ab997bc6cfe057c82f7c6f869d44195-refs/heads/main@{#1247893}