Revert "v8binding: Move WARN_UNUSED_RESULT to the end of func decl"
This reverts commit 7ad394a8d5e069b98a73de44b3782a3d6aa72050.

Reason for revert: attributes placed after function definition breaks
compilation with GCC.
The error example for GCC 9.3.0:
../../third_party/blink/renderer/bindings/core/v8/to_v8_traits.h:654:7:
error: attributes are not allowed on a function-definition

Original change's description:
> v8binding: Move WARN_UNUSED_RESULT to the end of func decl
>
> Just moves WARN_UNUSED_RESULT to the end of function
> declarations since it's the standard position in chromium
> code base.
>
> Change-Id: I47bc73f282b07ba16edd1dc82fce05018d4fa595
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2959348
> Reviewed-by: Kentaro Hara <haraken@chromium.org>
> Commit-Queue: Yuki Shiino <yukishiino@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#892981}

Bug: 819294
Change-Id: I6a634644a569ce56e609639a5e43238b73d47096
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2968744
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Reviewed-by: Yuki Shiino <yukishiino@chromium.org>
Commit-Queue: Ivan Murashov <ivan.murashov@lge.com>
Cr-Commit-Position: refs/heads/master@{#893769}