[wv] Add test for immediate JS execution after foregrounding a frozen WV
This adds a regression test to verify that evaluating JavaScript
immediately after bringing a backgrounded, frozen WebView back to the
foreground succeeds without stalling or dropping execution.

This is a regression test for b/b/547720473.

Verified that the test fails without
https://chromium-review.git.corp.google.com/c/chromium/src/+/8274931
with error:

```
expected:<"[success]"> but was:<"[error: Failed to execute 'createScriptURL' on 'TrustedTypePolicy': The provided callback is no longer runnable.]">
```

and passes with
https://chromium-review.git.corp.google.com/c/chromium/src/+/8274931.

Bug: 552352660
Change-Id: I5d78d796358ccf26dade01a2740f5cf7b05b9ce2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8288549
Commit-Queue: Abhijith Nair <abhijithnair@chromium.org>
Reviewed-by: Peter Beverloo <peter@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1686288}