Fix missing deps for obj/chrome/browser/ash/system/system/device_disabling_manager_default_delegate.o
```
ukai@ukai ...src/chromium/src % gn clean out/siso-chromeos
ukai@ukai ...src/chromium/src % siso ninja --verbose_failures=false -C out/siso-chromeos obj/chrome/browser/ash/system/system/device_disabling_manager_default_delegate.o --strict_remote
depot_tools/siso.py: Using Siso binary from SISO_PATH: /usr/local/google/home/ukai/go/bin/siso.
ninja: Entering directory `out/siso-chromeos'
reapi instance: projects/rbe-chrome-untrusted/instances/default_instance
 3.57s load siso config
13.16s Regenerating ninja files
 6.04s reloading
[11443/11444] 2m21.74s F CXX obj/chrom...e_disabling_manager_default_delegate.o
FAILED: e7883ff6-dad0-45ff-b7cc-811b9f325986 "./obj/chrome/browser/ash/system/system/device_disabling_manager_default_delegate.o" CXX obj/chrome/browser/ash/system/system/device_disabling_manager_default_delegate.o
err: exit=1
"python3" ../../build/toolchain/clang_code_coverage_wrapper.py --  ...(too long)
Use '--verbose_failures' to see the command lines
build step: cxx "./obj/chrome/browser/ash/system/system/device_disabling_manager_default_delegate.o"
siso_rule: clang/cxx/exception/fuzzer_large_compile
stderr:
In file included from ../../chrome/browser/ash/system/device_disabling_manager_default_delegate.cc:7:
In file included from ../../chrome/browser/ash/login/wizard_controller.h:25:
In file included from ../../chrome/browser/ash/login/quickstart_controller.h:16:
In file included from ../../chrome/browser/ui/webui/ash/login/oobe_ui.h:13:
../../ash/webui/common/backend/webui_syslog_emitter.h:8:10: fatal error: 'ash/webui/common/mojom/webui_syslog_emitter.mojom.h' file not found
    8 | #include "ash/webui/common/mojom/webui_syslog_emitter.mojom.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

build failed
local:7594 remote:0 cache:3850 fallback:0 retry:0 skip:8922
reapi: ops: 3851(err:0) / r:42563(err:0) 1.14GiB / w:71(err:0) 193.64MiB
fs: ops: 767116(err:208229) / r:93969(err:0) 5.63GiB / w:44055(err:0) 1.25GiB
   resource/capa used(err)  wait-avg |   s m |  serv-avg |   s m |
 pool=action/128   2972(0)     1.04s |█▂▃▆   |     0.53s | ▃█▂▂▂ |

2m22.23s Build Failure: 11444 done 1 failed 0 remaining - 80.46/s
 1 steps failed: exit=1
see ./out/siso-chromeos/siso_output for full command line and output
 or ./out/siso-chromeos/siso.INFO
use ./out/siso-chromeos/siso_failed_commands.sh to re-run failed commands
```

(cherry picked from commit 54ec13b292ac695692439b181f0b6b21b9681e63)

Bug: 420800532
Change-Id: Ia23ca65d68966b21b8824b287b68f0b298665528
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6596051
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Hidehiko Abe <hidehiko@chromium.org>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Cr-Original-Commit-Position: refs/heads/main@{#1466883}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6604016
Reviewed-by: Michael Wojcicka <mwoj@google.com>
Reviewed-by: Xiyuan Xia <xiyuan@chromium.org>
Commit-Queue: Madeleine Hardt <hardtmad@google.com>
Cr-Commit-Position: refs/branch-heads/7204@{#146}
Cr-Branched-From: d5de512dc9dc8ddfe4e6d71b0637578bb6158683-refs/heads/main@{#1465706}