Revert "[EVP] Fix cross-frame verification token fields"
This reverts commit 8cd08c0ec6ea21c778d13b5651b792e500dbd0ab.

Reason for revert: Mac Builder (dbg) failed with error:
[8879/29865] CXX obj/components/autofill/content/browser/browser/email_verifier_delegate.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/components/autofill/content/browser/browser/email_verifier_delegate.o.d ...(too long)
../../components/autofill/content/browser/email_verifier_delegate.cc:110:40: error: use of undeclared identifier 'email_field'
  110 |                field.host_form_id() == email_field->host_form_id();
      |                                        ^~~~~~~~~~~
../../components/autofill/content/browser/email_verifier_delegate.cc:106:7: error: no matching function for call to 'FindField'
  106 |       FindField(fields, [&](const AutofillField& field) {
      |       ^~~~~~~~~


Original change's description:
> [EVP] Fix cross-frame verification token fields
>
> This CL ensures that the <input> for the email and the <input>
> for the verification token are owned by the same form in the sense of
> https://chromium.googlesource.com/chromium/src/+/main/components/autofill/content/renderer/README.md#ownership
>
> In particular, it disallows them to be in different frames.
>
> Bug: 509579467
> Change-Id: I76c4721bb27dee8ae5884b2069859df45c6d7c4c
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7867992
> Commit-Queue: Christoph Schwering <schwering@google.com>
> Reviewed-by: Mohamed Amir Yosef <mamir@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1634231}

Bug: 509579467
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I8da35788d4e7c1d90a5c802d67598157c712d1f4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7867735
Reviewed-by: Ahmed Raslan <rslan@google.com>
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Ana Ercegovac <anaercegovac@google.com>
Commit-Queue: Ana Ercegovac <anaercegovac@google.com>
Cr-Commit-Position: refs/heads/main@{#1634234}