Revert "[Windows][Host][Logging] Adding EtwTraceConsumer class"
This reverts commit 341aef47f2373a68361f9dde477164917813a7e4.

Reason for revert: Tree-closing compilation failure. For example, https://ci.chromium.org/p/chromium/builders/ci/Win%20x64%20Builder/96007?
../../remoting/host/win/etw_trace_consumer.cc(119,11): error: use of undeclared identifier 'thread_checker_'
  DCHECK(!thread_checker_.CalledOnValidThread());
          ^
../../remoting/host/win/etw_trace_consumer.cc(125,11): error: use of undeclared identifier 'thread_checker_'
  DCHECK(!thread_checker_.CalledOnValidThread());

Original change's description:
> [Windows][Host][Logging] Adding EtwTraceConsumer class
>
> This CL adds the class which consumes the ETW events from
> Windows.  The class is fairly straight-forward but there
> is one interesting bit as the call to consumer events
> blocks us from running tasks on that thread.  In order to
> receive events and not block any of the existing threads,
> we create a new AutoThread which we use to listen for and
> handle events on.  When it is time to clean up, we unblock
> the listening thread by stopping the trace session.
>
> Future CLs will add the logic needed to parse the events
> and redirect the output to a new location (likely based on
> registry settings).  I've kept that out of this CL to keep
> its size on the smaller side.
>
> Bug: 1144185
> Change-Id: Ibf494251d0929a1741cb2796f26d69d258d96a64
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2515140
> Reviewed-by: Jamie Walch <jamiewalch@chromium.org>
> Commit-Queue: Joe Downing <joedow@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#823596}

TBR=jamiewalch@chromium.org,joedow@chromium.org

Change-Id: Id754b4ac043c4ae34196e6df3e2b621b60673591
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1144185
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2518104
Reviewed-by: Matthew Wolenetz <wolenetz@chromium.org>
Commit-Queue: Matthew Wolenetz <wolenetz@chromium.org>
Cr-Commit-Position: refs/heads/master@{#823605}