Revert "Periodically mark Chrome as active."
This reverts commit 492930fc0a3c831e556ef058811685a5109e2cc2.

Reason for revert: Build broken on buildbots.
https://ci.chromium.org/ui/p/chrome/builders/ci/mac-rel-ready/6111/overview

../../chrome/browser/updater/browser_updater_client_util_mac.mm:240:46: error: use of undeclared identifier 'SetActive'
240 |                              base::BindOnce(&SetActive));
|                                              ^


Original change's description:
> Periodically mark Chrome as active.
>
> This behavior was regressed when transitioning to the new updater.
> Windows is unaffected.
>
> Fixed: 1515153
> Change-Id: I12c47bbec2ca2ae5f287be31b85a993bb553131c
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5165609
> Reviewed-by: Xiaoling Bao <xiaolingbao@chromium.org>
> Commit-Queue: Joshua Pawlicki <waffles@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1242621}

Change-Id: I4bfa858bbb70e59edbfc1938e32252dfca86c2f9
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5166157
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Peter Williamson <petewil@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Peter Williamson <petewil@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1242638}