Revert "[base] Remove DIR_SOURCE_ROOT"
This reverts commit 425d865b5a0856091780a5304a8bfc6929348cd2.

Reason for revert: Causing compile failure in internal code. The mechanism for updating that code isn't clear at the moment so I'm reverting for now.

Example bot:
https://ci.chromium.org/ui/p/chrome/builders/ci/x64-builder/29542/overview

Log:
components/optimization_guide/internal/page_entities_model_handler_impl_unittest.cc:143:34: error: no member named 'DIR_SOURCE_ROOT' in namespace 'base'

Original change's description:
> [base] Remove DIR_SOURCE_ROOT
>
> Fixed: 1264897
> Change-Id: I37bfcb7576c23017a34b614d966114670e1e4b5b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4974095
> Reviewed-by: Christoph Schwering <schwering@google.com>
> Reviewed-by: danakj <danakj@chromium.org>
> Commit-Queue: Ho Cheung <uioptt24@gmail.com>
> Cr-Commit-Position: refs/heads/main@{#1214524}

Change-Id: I54142ab81d927ba397266f6bac375f2beae69e5b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4976743
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Matthew Jones <mdjones@chromium.org>
Owners-Override: Matt Jones <mdjones@google.com>
Cr-Commit-Position: refs/heads/main@{#1214841}