Revert "Use Mojo for communicating with web_app_shortcut_copier"
This reverts commit 3806c10c31140d32997718e7699255fc30c1abc1.

Reason for revert:
[gardener]
Causes consistent failures on some official bots such as mac-chrome
https://ci.chromium.org/ui/p/chrome/builders/ci/mac-chrome
also
https://ci.chromium.org/ui/p/chrome/builders/ci/mac64
https://ci.chromium.org/ui/p/chrome/builders/ci/mac-rel-ready

On the first bot mentioned, failures started here:
https://ci.chromium.org/ui/p/chrome/builders/ci/mac-chrome/40062/overview

They are compile failures:
[8242/19922] CXX obj/chrome/browser/web_applications/os_integration/mac/web_app_shortcut_copier_lib/web_app_shortcut_copier_mac.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/browser/web_applications/os_integration/mac/web_app_shortcut_copi...(too long)
../../chrome/browser/web_applications/os_integration/mac/web_app_shortcut_copier_mac.cc:71:40: error: invalid operands to binary expression ('const char[18]' and 'const char[6]')
   71 |           MAC_BUNDLE_IDENTIFIER_STRING + ".beta",
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~
../../chrome/browser/web_applications/os_integration/mac/web_app_shortcut_copier_mac.cc:72:40: error: invalid operands to binary expression ('const char[18]' and 'const char[8]')
   72 |           MAC_BUNDLE_IDENTIFIER_STRING + ".canary",
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~

This is the obvious cause (the only change on the blamelist that touched that file).

Original change's description:
> Use Mojo for communicating with web_app_shortcut_copier
>
> This makes it possible for web_app_shortcut_copier to reliably verify
> the identity of the process that it is performing work on behalf of
> (http://go/peer-process-validation).
>
> `WebAppShortcutCreator` moves away from passing the source and
> destination path to be copied to `web_app_shortcut_copier` via command
> line arguments. Instead a Mojo invitation is passed via the command line
> and a synchronous call is used to request the copy be performed.
>
> `web_app_shortcut_copier` is updated to recover the Mojo endpoint from
> its command line and process the `CopyWebAppShortcut` message. The
> copier exits after a message has been processed.
>
> During initialization, `web_app_shortcut_copier` sets a
> `ProcessRequirement` to prevent anyone other than the browser process
> from establishing a Mojo connection with it. Enforcement of the
> requirement by `MachPortRendezvousClientMac` is currently gated by a
> feature flag. This needs to be enabled by default before the feature
> flag that enables use of `web_app_shortcut_copier` can be enabled.
>
> Bug: 361784552
> Change-Id: I3a9b5128d21223bcd03a4acda2491bb1e42ed896
> Include-Ci-Only-Tests: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5924245
> Reviewed-by: Nasko Oskov <nasko@chromium.org>
> Reviewed-by: Alex Gough <ajgo@chromium.org>
> Reviewed-by: Marijn Kruisselbrink <mek@chromium.org>
> Auto-Submit: Mark Rowe <markrowe@chromium.org>
> Commit-Queue: Mark Rowe <markrowe@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1374160}

Bug: 361784552
Change-Id: I82ee885dbec3e0d0cd1452b59e7f6d6a3e22912d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5967679
Auto-Submit: Mark Pearson <mpearson@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Mark Pearson <mpearson@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1374209}