Disable binary_size tests on Windows
bcanalyzer and other binary_size tools don't work on Windows so these
tests just give lots of noisy and cryptic error messages. This change
disables these tests on Windows so that "git cl presubmit --all" output
will have a better signal to noise ratio.

Typical errors (hugely simplified) were:

    ERROR: testAnalyzer (__main__.BcAnalyzerTest)
    ...
    OSError: [WinError 193] %1 is not a valid Win32 application

This change was tested with:

    git cl presubmit --files=tools/binary_size/*

Bug: 1309977
Change-Id: I68117cfeeb083594b11622c5def9aedc3267c91f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3591277
Reviewed-by: Jesse McKenna <jessemckenna@google.com>
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#993759}