Update test to focus on frame and call content::HandleMissingKeyWindow()
This CL attempts to fix flaky tests that are failing with the message:
```
NotAllowedError: Failed to execute 'writeText' on 'Clipboard': Document
is not focused.
```

This is done by calling Focus() on the frame and also by calling
content::HandleMissingKeyWindow(), which was needed for a similar
failure fixed in crrev.com/c/6221803.

Bug: 418342665
Change-Id: I26227808d0e963af1a836f303130d7f521eeaddb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6579918
Commit-Queue: thefrog <thefrog@chromium.org>
Reviewed-by: Xinghui Lu <xinghuilu@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1464705}