CCA: Add missing function return types in ConstraintsPreferrer
This CL fixes the following error in ConstraintsPreferrer:
> error TS7014: Function type, which lacks return-type annotation,
> implicitly has an 'any' return type.

We do `await` on some of those functions and should annotate `!Promise`
in the return type.

Bug: b/172340451
Test: Run tsc and there are 6 less errors.
Change-Id: I49cd206c9178b8de1ee80fe574d5e59da6b87723
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2661706
Commit-Queue: Shik Chen <shik@chromium.org>
Reviewed-by: Inker Kuo <inker@chromium.org>
Cr-Commit-Position: refs/heads/master@{#849469}