Revert "Reenable PredictionManager and HintsFetcher browser tests that were"
This reverts commit 3bd04812b313c8422d3cc0a20b4e8b7cf1866c7e.

Reason for revert:
causes failures on
Win 7 Tests x64 (1)
Win7 Tests (dbg)(1)
Win7 (32) Tests

Example bot that failed:
https://ci.chromium.org/ui/p/chromium/builders/ci/Win%207%20Tests%20x64%20(1)/76517/overview

Top of failure message (it's long so I didn't paste the whole thing here):
[ RUN      ] PredictionManagerModelDownloadingBrowserTest.TestSuccessfulModelFileFlow
../../content/public/test/browser_test_base.cc(756): error: Failed
RunLoop::Run() timed out.
Stack trace:
Backtrace:
	base::internal::Invoker<base::internal::BindState<`lambda at ../../base/test/scoped_run_loop_timeout.cc:49:9',base::Location,base::RepeatingCallback<std::basic_string<char> ()> >,void ()>::Run [0x0000000143A46C1D+157] (o:\base\bind_internal.h:692)
	base::`anonymous namespace'::OnRunLoopTimeout [0x00000001439B533E+46] (o:\base\run_loop.cc:44)
	base::internal::Invoker<base::internal::BindState<void (*)(base::RunLoop *, base::OnceCallback<void ()>),base::internal::UnretainedWrapper<base::RunLoop>,base::RepeatingCallback<void ()> >,void ()>::RunOnce [0x00000001439B6726+86] (o:\base\bind_internal.h:679)
	base::internal::CancelableCallbackImpl<base::OnceCallback<void ()> >::ForwardOnce<> [0x0000000141157DE6+54] (o:\base\cancelable_callback.h:128)
	base::TaskAnnotator::RunTask [0x00000001439CD3DD+365] (o:\base\task\common\task_annotator.cc:163)
	base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl [0x0000000144EE8481+433] (o:\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc:352)
	base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork [0x0000000144EE814C+204] (o:\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc:266)
	base::MessagePumpForUI::DoRunLoop [0x0000000143A011BA+122] (o:\base\message_loop\message_pump_win.cc:225)
	base::MessagePumpWin::Run [0x0000000143A008DA+90] (o:\base\message_loop\message_pump_win.cc:82)
	base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run [0x0000000144EE8DF1+273] (o:\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc:463)
	base::RunLoop::Run [0x00000001439B4DE1+433] (o:\base\run_loop.cc:133)
	optimization_guide::PredictionManagerModelDownloadingBrowserTest_TestSuccessfulModelFileFlow_Test::RunTestOnMainThread [0x000000013FDFF540+288] (o:\chrome\browser\optimization_guide\prediction\prediction_manager_browsertest.cc:1045)
	content::BrowserTestBase::ProxyRunTestOnMainThreadLoop [0x0000000143C2BCB3+419] (o:\content\public\test\browser_test_base.cc:807)
	ChromeBrowserMainParts::PreMainMessageLoopRunImpl [0x0000000143A784EE+4582] (o:\chrome\browser\chrome_browser_main.cc:1688)
	ChromeBrowserMainParts::PreMainMessageLoopRun [0x0000000143A77241+65] (o:\chrome\browser\chrome_browser_main.cc:1044)
	content::BrowserMainLoop::PreMainMessageLoopRun [0x0000000141F3DFB9+73] (o:\content\browser\browser_main_loop.cc:946)
	content::StartupTaskRunner::RunAllTasksNow [0x00000001422F62C7+61] (o:\content\browser\startup_task_runner.cc:41)
	content::BrowserMainLoop::CreateStartupTasks [0x0000000141F3CD05+621] (o:\content\browser\browser_main_loop.cc:860)
	content::BrowserMainRunnerImpl::Initialize [0x0000000141F3FA1E+126] (o:\content\browser\browser_main_runner_impl.cc:130)
	content::BrowserMain [0x0000000141F3B579+161] (o:\content\browser\browser_main.cc:43)
	content::RunBrowserProcessMain [0x00000001428DCA39+169] (o:\content\app\content_main_runner_impl.cc:555)
	content::ContentMainRunnerImpl::RunBrowser [0x00000001428DD7F2+854] (o:\content\app\content_main_runner_impl.cc:1059)
	content::ContentMainRunnerImpl::Run [0x00000001428DD46F+335] (o:\content\app\content_main_runner_impl.cc:929)
	content::RunContentProcess [0x00000001428DC2D1+805] (o:\content\app\content_main.cc:372)
	content::ContentMain [0x00000001428DC64E+61] (o:\content\app\content_main.cc:398)
	content::BrowserTestBase::SetUp [0x0000000143C2B516+1894] (o:\content\public\test\browser_test_base.cc:683)
	InProcessBrowserTest::SetUp [0x00000001439630CE+398] (o:\chrome\test\base\in_process_browser_test.cc:351)
	optimization_guide::PredictionManagerBrowserTestBase::SetUp [0x000000013FDFF76A+266] (o:\chrome\browser\optimization_guide\prediction\prediction_manager_browsertest.cc:256)

../../base/test/metrics/histogram_tester.cc(43): error: Expected equality of these values:
  0
  expected_count
    Which is: 1
Zero samples found for Histogram "OptimizationGuide.PredictionModelDownloadManager.DownloadStatus".


Original change's description:
> Reenable PredictionManager and HintsFetcher browser tests that were
> disabled on desktop platforms
>
> Change-Id: I173ac1025760f908042e64c7c8839fb90e41fc78
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2626918
> Reviewed-by: Michael Crouse <mcrouse@chromium.org>
> Commit-Queue: Sophie Chang <sophiechang@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#843180}

TBR=sophiechang@chromium.org,mcrouse@chromium.org,chromium-scoped@luci-project-accounts.iam.gserviceaccount.com

Change-Id: Ia5e026dcfd3a0b0ccfb68c2baad18209222a02b4
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2628258
Reviewed-by: Mark Pearson <mpearson@chromium.org>
Commit-Queue: Mark Pearson <mpearson@chromium.org>
Cr-Commit-Position: refs/heads/master@{#843220}