Revert "Roll abseil_revision f70eadadd7..3b22e57740"
This reverts commit 1becef9e78101e4187ca04aa1b9ead6e83a02538.

Reason for revert:

https://ci.chromium.org/p/chromium/builders/ci/win-archive-rel

fails with

../../third_party/abseil-cpp/absl/random/internal/randen_detect.cc(43,19): error: '__cpuid' is not a recognized builtin [-Werror,-Wignored-pragma-intrinsic]
#pragma intrinsic(__cpuid)





Original change's description:
> Roll abseil_revision f70eadadd7..3b22e57740
>
> Change Log:
> https://chromium.googlesource.com/external/github.com/abseil/abseil-cpp/+log/f70eadadd7..3b22e57740
> Full diff:
> https://chromium.googlesource.com/external/github.com/abseil/abseil-cpp/+/f70eadadd7..3b22e57740
>
> Bug: None
> Change-Id: I28427deea4e0e9e3df63bc8000aa93771529d3f5
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3257270
> Commit-Queue: Mirko Bonadei <mbonadei@chromium.org>
> Reviewed-by: Danil Chapovalov <danilchap@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#937927}

Bug: None
Change-Id: Ia99f7c3cf9cc828576948e587a4934d1b572df32
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3260447
Auto-Submit: Avi Drissman <avi@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Avi Drissman <avi@chromium.org>
Owners-Override: Avi Drissman <avi@chromium.org>
Cr-Commit-Position: refs/heads/main@{#937972}