Revert "Add mojo interfaces for pepper plugins."
This reverts commit 3da5569e9184752810b475eaaad48940cdb9f794.

Reason for revert: Suspected to be causing widespread failures in PPAPI/Pepper tests on Win and Linux dbg bots:

https://ci.chromium.org/p/chromium/builders/ci/Win7%20Tests%20%28dbg%29%281%29/87226
https://ci.chromium.org/p/chromium/builders/ci/Linux%20Tests%20%28dbg%29%281%29/93584

Sample failure output:

[ RUN      ] OutOfProcessPPAPITest.Instance_ExecuteScript
[18698:18698:1211/141847.386588:INFO:content_main_runner_impl.cc(1027)] Chrome is running in full browser mode.

DevTools listening on ws://127.0.0.1:37739/devtools/browser/565ba965-de40-4715-8905-11c22e1cfcca
[18698:18811:1211/141848.175888:WARNING:render_message_filter.cc(137)] Could not find tid
[18698:18811:1211/141848.265958:WARNING:render_message_filter.cc(137)] Could not find tid
[18698:18698:1211/141848.839793:INFO:CONSOLE(1)] "Uncaught Error: plugin exception", source: file:///b/s/w/ir/ppapi/tests/test_case.html?testcase=Instance_ExecuteScript (1)
[18698:18698:1211/141848.844552:INFO:CONSOLE(1)] "Uncaught TypeError: document.doesntExist is not a function", source: file:///b/s/w/ir/ppapi/tests/test_case.html?testcase=Instance_ExecuteScript (1)
[18698:18698:1211/141848.855716:INFO:CONSOLE(176)] "ExecuteScript finished in 0.073 seconds.", source: file:///b/s/w/ir/ppapi/tests/test_case.html?testcase=Instance_ExecuteScript (176)
Received signal 11 <unknown> 000000000000
#0 0x7f89c0dca89f base::debug::CollectStackTrace()
#1 0x7f89c0b5409a base::debug::StackTrace::StackTrace()
#2 0x7f89c0b54055 base::debug::StackTrace::StackTrace()
#3 0x7f89c0dca36b base::debug::(anonymous namespace)::StackDumpSignalHandler()
#4 0x7f8993ea2390 (/lib/x86_64-linux-gnu/libpthread-2.23.so+0x1138f)
#5 0x7f89b142c419 std::__Cr::default_delete<>::operator()()
#6 0x7f89b142c3ea std::__Cr::unique_ptr<>::reset()
#7 0x7f89b142c379 std::__Cr::unique_ptr<>::~unique_ptr()
#8 0x7f89b142c16d mojo::internal::AssociatedInterfacePtrState<>::~AssociatedInterfacePtrState()
#9 0x7f89b142cb95 mojo::AssociatedRemote<>::~AssociatedRemote()
#10 0x7f89b142afab content::PepperPluginInstance::~PepperPluginInstance()
#11 0x7f89b2587d8e content::PepperPluginInstanceImpl::~PepperPluginInstanceImpl()
#12 0x7f89b2587e69 content::PepperPluginInstanceImpl::~PepperPluginInstanceImpl()
#13 0x7f89b25350f8 base::RefCounted<>::DeleteInternal<>()
#14 0x7f89b25350c5 base::DefaultRefCountedTraits<>::Destruct()
#15 0x7f89b25350a3 base::RefCounted<>::Release()
#16 0x7f89b2535069 scoped_refptr<>::Release()
#17 0x7f89b253020a scoped_refptr<>::~scoped_refptr()
#18 0x7f89b25ce3f3 scoped_refptr<>::reset()
#19 0x7f89b25cd8dd _ZN13scoped_refptrIN7content24PepperPluginInstanceImplEEaSEDn
#20 0x7f89b25cbe83 content::PepperWebPluginImpl::Destroy()
#21 0x7f89a7414e41 blink::WebPluginContainerImpl::Dispose()
#22 0x7f89a593f32d blink::HTMLFrameOwnerElement::PluginDisposeSuspendScope::PerformDeferredPluginDispose()
#23 0x7f89a4f5d292 blink::HTMLFrameOwnerElement::PluginDisposeSuspendScope::~PluginDisposeSuspendScope()
#24 0x7f89a4f58862 blink::ContainerNode::RemoveChild()
#25 0x7f89a5111cbb blink::Node::removeChild()
#26 0x7f89a70daabe blink::(anonymous namespace)::RemoveChildOperationCallback()
#27 0x7f899e0c0780 v8::internal::FunctionCallbackArguments::Call()
#28 0x7f899e0bedcd v8::internal::(anonymous namespace)::HandleApiCallHelper<>()
#29 0x7f899e0bcfe5 v8::internal::Builtin_Impl_HandleApiCall()
#30 0x7f899e0bcaa9 v8::internal::Builtin_HandleApiCall()
#31 0x7f899dae513f Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
  r8: 00000f84ee181f88  r9: 0000000000000000 r10: 0000000000000259 r11: 00007f8996194690
 r12: 00007f89a70da600 r13: 0000132400000000 r14: 00007ffc8c8eef10 r15: 00007ffc8c8eef10
  di: 00007f89b3e98918  si: 00007f89b3e98918  bp: 00007ffc8c8ee710  bx: 00007f89c0f52440
  dx: 00000f84ee181f90  ax: 00007f89b2587db0  cx: 0000000000000000  sp: 00007ffc8c8ee6f0
  ip: 00007f89b142c419 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000000
 trp: 000000000000000d msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
../../content/public/test/no_renderer_crashes_assertion.cc:101: Failure
Failed
Unexpected termination of a renderer process; status: 1, exit_code: 256
Stack trace:
#0 0x55ec1877d394 content::NoRendererCrashesAssertion::Observe()
#1 0x7f3d4cf1ead6 content::NotificationServiceImpl::Notify()
#2 0x7f3d4d3a3986 content::RenderProcessHostImpl::ProcessDied()
#3 0x7f3d4d3a46be content::RenderProcessHostImpl::OnChannelError()
#4 0x7f3d60fa392d IPC::ChannelProxy::Context::OnDispatchError()
#5 0x7f3d60fa987f base::internal::FunctorTraits<>::Invoke<>()
#6 0x7f3d60fa97c1 base::internal::InvokeHelper<>::MakeItSo<>()
#7 0x7f3d60fa9742 _ZN4base8internal7InvokerINS0_9BindStateIMN3IPC12ChannelProxy7ContextEFvvEJ13scoped_refptrIS5_EEEEFvvEE7RunImplIS7_NSt4__Cr5tupleIJS9_EEEJLm0EEEEvOT_OT0_NSE_16integer_sequenceImJXspT1_EEEE
#8 0x7f3d60fa96ec base::internal::Invoker<>::RunOnce()
#9 0x7f3d5ca3c0d1 _ZNO4base12OnceCallbackIFvvEE3RunEv
#10 0x7f3d5cc03df2 base::TaskAnnotator::RunTask()
#11 0x7f3d5cc49eba base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
#12 0x7f3d5cc49685 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
#13 0x7f3d5cc4a119 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
#14 0x7f3d5caf69f1 base::MessagePumpGlib::HandleDispatch()
#15 0x7f3d5caf7141 base::(anonymous namespace)::WorkSourceDispatch()
#16 0x7f3d2f683197 g_main_context_dispatch
#17 0x7f3d2f6833f0 (/lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2+0x4a3ef)
#18 0x7f3d2f68349c g_main_context_iteration
#19 0x7f3d5caf6b00 base::MessagePumpGlib::Run()
#20 0x7f3d5cc4a740 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
#21 0x7f3d5cb95d75 base::RunLoop::Run()
#22 0x55ec187b836a content::RunThisRunLoop()
#23 0x55ec187b831f content::RunMessageLoop()
#24 0x55ec18760320 content::JavascriptTestObserver::Run()
#25 0x55ec16a8b567 content::PPAPITestBase::RunTestURL()
#26 0x55ec16a8b48e content::PPAPITestBase::RunTest()
#27 0x55ec16a84f2a content::(anonymous namespace)::OutOfProcessPPAPITest_Instance_ExecuteScript_Test::RunTestOnMainThread()
#28 0x55ec18719264 content::BrowserTestBase::ProxyRunTestOnMainThreadLoop()
#29 0x55ec1871cf2a base::internal::FunctorTraits<>::Invoke<>()
#30 0x55ec1871cea1 base::internal::InvokeHelper<>::MakeItSo<>()
#31 0x55ec1871ce37 _ZN4base8internal7InvokerINS0_9BindStateIMN7content15BrowserTestBaseEFvvEJNS0_17UnretainedWrapperIS4_EEEEEFvvEE7RunImplIS6_NSt4__Cr5tupleIJS8_EEEJLm0EEEEvOT_OT0_NSD_16integer_sequenceImJXspT1_EEEE
#32 0x55ec1871cddc base::internal::Invoker<>::RunOnce()
#33 0x55ec157bbac1 _ZNO4base12OnceCallbackIFvvEE3RunEv
#34 0x55ec18a331cc content::ShellBrowserMainParts::PreMainMessageLoopRun()
#35 0x7f3d4c5f5282 content::BrowserMainLoop::PreMainMessageLoopRun()
#36 0x7f3d4c5ff18a base::internal::FunctorTraits<>::Invoke<>()
#37 0x7f3d4c5ff0a1 base::internal::InvokeHelper<>::MakeItSo<>()
#38 0x7f3d4c5ff027 _ZN4base8internal7InvokerINS0_9BindStateIMN7content15BrowserMainLoopEFivEJNS0_17UnretainedWrapperIS4_EEEEEFivEE7RunImplIS6_NSt4__Cr5tupleIJS8_EEEJLm0EEEEiOT_OT0_NSD_16integer_sequenceImJXspT1_EEEE
#39 0x7f3d4c5fefcc base::internal::Invoker<>::RunOnce()
#40 0x7f3d4c9d5b31 _ZNO4base12OnceCallbackIFivEE3RunEv
#41 0x7f3d4d812b16 content::StartupTaskRunner::RunAllTasksNow()
#42 0x7f3d4c5f3b8a content::BrowserMainLoop::CreateStartupTasks()
#43 0x7f3d4c602df0 content::BrowserMainRunnerImpl::Initialize()
#44 0x7f3d4c5f0d64 content::BrowserMain()
#45 0x7f3d4e7bcbc6 content::RunBrowserProcessMain()
#46 0x7f3d4e7be1e9 content::ContentMainRunnerImpl::RunBrowser()
#47 0x7f3d4e7bdad7 content::ContentMainRunnerImpl::Run()
#48 0x7f3d4e7bae05 content::RunContentProcess()
#49 0x7f3d4e7bb79d content::ContentMain()
#50 0x55ec18718d5a content::BrowserTestBase::SetUp()
#51 0x55ec1865a9ac content::ContentBrowserTest::SetUp()
#52 0x55ec16a8ba95 content::OutOfProcessPPAPITest::SetUp()
#53 0x55ec17363a6b testing::internal::HandleSehExceptionsInMethodIfSupported<>()
#54 0x55ec173547f7 testing::internal::HandleExceptionsInMethodIfSupported<>()

Note the ~AssociatedRemote from ~PepperPluginInstanceImpl, which I think was introduced in this CL.  This also seems to be the only plugin-related change in the blamelist (https://chromium.googlesource.com/chromium/src/+log/6828ef78f2200e4bac3280186c7520ab65b2d7f8%5E..21468f4304510a432e3376d9d72ec67962f39723?pretty=fuller&n=)

Original change's description:
> Add mojo interfaces for pepper plugins.
>
> This adds some base plumbing for pepper plugin instance handling. The
> pepper renderer code allocates and manages the PepperPluginInstanceImpl,
> this creates the correct encapsulation moving code out of RenderFrameImpl.
>
> On the browser side a PepperPluginInstance is created to handle the
> messages and relay them to the WebContentsImpl which use to handle
> the processing of Pepper messages.
>
> BUG=1157519
>
> Change-Id: I24941bb7eecef56a90bbf961e6396101c8d3c785
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2585627
> Commit-Queue: Dave Tapuska <dtapuska@chromium.org>
> Reviewed-by: Arthur Sonzogni <arthursonzogni@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Reviewed-by: Bill Budge <bbudge@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#836239}

TBR=dcheng@chromium.org,bbudge@chromium.org,dtapuska@chromium.org,arthursonzogni@chromium.org,chromium-scoped@luci-project-accounts.iam.gserviceaccount.com

Change-Id: Iddd93694ebe0611abef6c74b57667554b51e26fc
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1157519
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2587769
Reviewed-by: Alex Moshchuk <alexmos@chromium.org>
Commit-Queue: Alex Moshchuk <alexmos@chromium.org>
Cr-Commit-Position: refs/heads/master@{#836330}