IWYU: missing include for usage of ptrdiff_t in prtime.cc
Fix for build error with libstdc++:
    ../../base/third_party/nspr/prtime.cc: In function ‘PRStatus PR_ParseTimeString(const char*, PRBool, PRTime*)’:
    ../../base/third_party/nspr/prtime.cc:793:37: error: ‘ptrdiff_t’ was not declared in this scope; did you mean ‘std::ptrdiff_t’?
      793 |                                     ptrdiff_t ndigits = end - rest;
          |                                     ^~~~~~~~~
          |                                     std::ptrdiff_t

Bug: 957519
Change-Id: I3a6fc2d6b35763d03a3d93f4322a3b2522f5ccc5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3729259
Reviewed-by: Gabriel Charette <gab@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#1018692}