Revert "Privacy Sandbox Settings: Get correct m1 prompt type"
This reverts commit b6a5f9138623c233781372afbd1083a36517770d.

Reason for revert: Compilation error in linux-chrome. See the following link https://ci.chromium.org/p/chrome/builders/ci/linux-chrome

```
chrome/browser/privacy_sandbox/privacy_sandbox_service.cc:182:10: error: 'return' will never be executed [-Werror,-Wunreachable-code-return]
return false;
^~~~~
1 error generated.
```


Original change's description:
> Privacy Sandbox Settings: Get correct m1 prompt type
>
> Create an M1 version of GetRequiredPromptType that returns the prompt
> type that should be shown to a particular user.
>
> Bug: 1378703
> Change-Id: Id97d9e37579c39f3f0df41a5e55b5ec3e946e650
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4144907
> Reviewed-by: Olesia Marukhno <olesiamarukhno@google.com>
> Commit-Queue: Ehimare Okoyomon <eokoyomon@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1093031}

Bug: 1378703
Change-Id: I6ee5474b8532446b679866d0273e63266738ef5c
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4171664
Owners-Override: Martin Rodriguez <rodmartin@google.com>
Reviewed-by: Martin Bidlingmaier <mbid@google.com>
Reviewed-by: Kush Sinha <sinhak@chromium.org>
Reviewed-by: Amr Aboelkher <amraboelkher@chromium.org>
Commit-Queue: Martin Rodriguez <rodmartin@google.com>
Reviewed-by: Martin Rodriguez <rodmartin@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Mohammed Abdon <mohammedabdon@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1093042}