WebUI: Require CrLitElement subclasses to declare $ interface.
Remove the generic '$: ElementCache' declaration from CrLitElement which
forces subclasses to only access '$' if the class has explicitly defined
a '$' interface.

Update usages of $['...'] that were previously relying on the fallback
ElementCache declaration to use querySelector() instead, as they now
surface as TS errors like the following:
error TS2339: Property '$' does not exist on type 'SomeElement'.

Bug: 567169220
Change-Id: I623d3e0073adb39d92f2fa905f13541be57e4842
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8489032
Commit-Queue: Demetrios Papadopoulos <dpapad@chromium.org>
Reviewed-by: Rebekah Potter <rbpotter@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1707593}