Revert "Roll Catapult from f92a7636da65 to 808ef50106ef (3 revisions)"
This reverts commit a2352c3390180d860986dc25d5763c8f04530fbd.

Reason for revert: Broke the WPT importer (https://ci.chromium.org/p/infra/builders/cron/wpt-importer) due to failure to import requests:

Traceback (most recent call last):
  File "/b/s/w/ir/x/w/src/third_party/blink/tools/wpt_import.py", line 10, in <module>
    from blinkpy.w3c.test_importer import TestImporter
  File "/b/s/w/ir/x/w/src/third_party/blink/tools/blinkpy/w3c/test_importer.py", line 27, in <module>
    from blinkpy.w3c.import_notifier import ImportNotifier
  File "/b/s/w/ir/x/w/src/third_party/blink/tools/blinkpy/w3c/import_notifier.py", line 21, in <module>
    from blinkpy.w3c.wpt_expectations_updater import WPTExpectationsUpdater
  File "/b/s/w/ir/x/w/src/third_party/blink/tools/blinkpy/w3c/wpt_expectations_updater.py", line 22, in <module>
    from blinkpy.web_tests.models.test_expectations import TestExpectations
  File "/b/s/w/ir/x/w/src/third_party/blink/tools/blinkpy/web_tests/models/test_expectations.py", line 38, in <module>
    from blinkpy.web_tests.models import typ_types
  File "/b/s/w/ir/x/w/src/third_party/blink/tools/blinkpy/web_tests/models/typ_types.py", line 9, in <module>
    from typ import json_results, expectations_parser, artifacts
  File "/b/s/w/ir/x/w/src/third_party/catapult/third_party/typ/typ/__init__.py", line 66, in <module>
    from typ.runner import Runner, TestInput, TestSet, WinMultiprocessing, main
  File "/b/s/w/ir/x/w/src/third_party/catapult/third_party/typ/typ/runner.py", line 43, in <module>
    from typ import result_sink
  File "/b/s/w/ir/x/w/src/third_party/catapult/third_party/typ/typ/result_sink.py", line 29, in <module>
    import requests
ImportError: No module named requests

Original change's description:
> Roll Catapult from f92a7636da65 to 808ef50106ef (3 revisions)
>
> https://chromium.googlesource.com/catapult.git/+log/f92a7636da65..808ef50106ef
>
> 2020-11-17 hypan@google.com Add "third_party/gsutil" to cipd.yaml for devil
> 2020-11-16 bsheedy@chromium.org [typ] Use requests for ResultSink
> 2020-11-13 hypan@google.com Add CIPD create instruction cipd.yaml that packages devil
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/catapult-autoroll
> Please CC rmhasan@google.com on the revert to ensure that a human
> is aware of the problem.
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/master/autoroll/README.md
>
> Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:chromeos-kevin-rel;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:win_optional_gpu_tests_rel
> Bug: chromium:1108014,chromium:1147992
> Tbr: rmhasan@google.com
> Change-Id: I3f3bbd92222e9e80c84939f0bdbfab39d4379318
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2542748
> Reviewed-by: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/master@{#828099}

TBR=chromium-autoroll@skia-public.iam.gserviceaccount.com,rmhasan@google.com

Change-Id: I829d45a6cb43610c4c1da9f126f2ef420a4a0ce7
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: chromium:1108014
Bug: chromium:1147992
Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:chromeos-kevin-rel;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:win_optional_gpu_tests_rel
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2543832
Reviewed-by: Stephen McGruer <smcgruer@chromium.org>
Commit-Queue: Stephen McGruer <smcgruer@chromium.org>
Cr-Commit-Position: refs/heads/master@{#828157}