IWYU: missing memory include for unique_ptr usage in class_property.h
Fix GCC build breakage because of missing inclide:
./../ui/base/class_property.h:120:58: error: ‘std::unique_ptr’ has not been declared
  120 |   T* SetProperty(const ClassProperty<T*>* property, std::unique_ptr<T> value);
      |                                                          ^~~~~~~~~~

Bug: 819294
Change-Id: I46b921876702b8d44674689bbb5acdc107db21e5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3041030
Reviewed-by: Peter Boström <pbos@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/master@{#903820}