Reland "Reland "Load QuickOffice manifest from cros rootfs""
This reverts commit 9d571b2d7905fe48fafee1eabeb83e9a24f5a551.

Reason for revert: tests fixed
PS1: revert/reland
PS2: rebase
PS3: Added //chrome/test/data version of quickoffice manifest.json

Loading manifest and contents from rootfs will ensure that
QO always has the correct manifest for contents, especially for
lacros.

Original change's description:
> Revert "Reland "Load QuickOffice manifest from cros rootfs""
>
> This reverts commit 336415fa902298ba2f5e0da9d962fd61dedff5d8.
>
> Reason for revert: suspect causing browser_tests failure on linux-chromeos-chrome
>
> browser_tests failed because of:
> All/FileTasksBrowserTest.FallbackSucceedsWithQuickOffice/Guest
> All/FileTasksBrowserTest.FallbackSucceedsWithQuickOffice/Regular
> All/FileTasksBrowserTest.QuickOffice/Guest
> All/FileTasksBrowserTest.QuickOffice/Incognito
> ...6 more failure(s) (10 total)...
>
> The first build failure:
> https://ci.chromium.org/ui/p/chrome/builders/ci/linux-chromeos-chrome/37099/overview
>
> Original change's description:
> > Reland "Load QuickOffice manifest from cros rootfs"
> >
> > This reverts commit 05780297d2cd6230f32d3671022366447da79f73.
> >
> > Reason for revert: Fixed compile error
> >
> > Original change's description:
> > > Revert "Load QuickOffice manifest from cros rootfs"
> > >
> > > This reverts commit a1b9a2a855e11df2b04d6643c459e3fec2a8ebe6.
> > >
> > > Reason for revert: suspect causing compile failure on lacros-arm32-rel-ready bot.
> > >
> > > First build failure:
> > > https://ci.chromium.org/ui/p/chrome/builders/ci/lacros-arm32-rel-ready/17628/overview
> > >
> > > Sample log:
> > > ../../chrome/browser/extensions/component_loader.cc:550:7: error: use of undeclared identifier 'AddComponentFromDirWithManifestFilename'
> > > AddComponentFromDirWithManifestFilename(
> > > ^
> > > 1 error generated.
> > >
> > > Original change's description:
> > > > Load QuickOffice manifest from cros rootfs
> > > >
> > > > QuickOffice will change in crrev.com/c/5014644 to load all files
> > > > including manifest.json into rootfs at
> > > > /usr/share/chromeos-assets/quickoffice.
> > > >
> > > > CrOS will load all files directly from gcs rather than using the
> > > > chromium repo submodule. There will be no need to keep
> > > > chrome/browser/resources/chromeos/quickoffice.
> > > >
> > > > Bug: 1491571
> > > > Change-Id: I1f1de7cc1c4950b4fd30d1bab8300faf6b7e8494
> > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5013290
> > > > Commit-Queue: Joel Hockey <joelhockey@chromium.org>
> > > > Reviewed-by: Dominick Ng <dominickn@chromium.org>
> > > > Reviewed-by: Kyle Horimoto <khorimoto@chromium.org>
> > > > Cr-Commit-Position: refs/heads/main@{#1222566}
> > >
> > > Bug: 1491571
> > > Change-Id: Ifdc07c1b1b21caf0bf5ad35913bb1c2a12dd3f51
> > > No-Presubmit: true
> > > No-Tree-Checks: true
> > > No-Try: true
> > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5017114
> > > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > > Owners-Override: Takashi Sakamoto <tasak@google.com>
> > > Commit-Queue: Takashi Sakamoto <tasak@google.com>
> > > Cr-Commit-Position: refs/heads/main@{#1222647}
> >
> > Bug: 1491571
> > Change-Id: Ifed4ad16a0e646a23a2da62e06483cf47af1ea2b
> > No-Presubmit: true
> > No-Tree-Checks: true
> > No-Try: true
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5018558
> > Reviewed-by: Takashi Sakamoto <tasak@google.com>
> > Commit-Queue: Joel Hockey <joelhockey@chromium.org>
> > Reviewed-by: Dominick Ng <dominickn@chromium.org>
> > Owners-Override: Takashi Sakamoto <tasak@google.com>
> > Cr-Commit-Position: refs/heads/main@{#1222715}
>
> Bug: 1491571
> Change-Id: I771e0ccc0e1e9e1213c494746345085338e9868d
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5017601
> Owners-Override: Takashi Sakamoto <tasak@google.com>
> Commit-Queue: Takashi Sakamoto <tasak@google.com>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1222771}

Bug: 1491571
Change-Id: I51ba69366039ff06837b837ae47ede71a7957990
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5369299
Owners-Override: Eriko Kurimoto <elkurin@chromium.org>
Reviewed-by: Alexander Bolodurin <alexbn@chromium.org>
Commit-Queue: Eriko Kurimoto <elkurin@chromium.org>
Reviewed-by: Erik Chen <erikchen@chromium.org>
Reviewed-by: Eriko Kurimoto <elkurin@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1273250}