wayland: fix weston executable wayland dependencies
In-tree Weston executables (and other targets that do not depend on
':libweston', for example) must explicitly declare a dependency on
//third_party/wayland:wayland_client, thus ensuring the correct core
header files, such as wayland-client-core.h, otherwise the header from
the sysroot will be incorrectly picked up, causing errors as the
following, when upgrading wayland repo to 1.21:

```
In file included from ../../third_party/weston/src/clients/keyboard.c:38:
gen/third_party/wayland-protocols/src/unstable/input-method/input-method-unstable-v1-client-protocol.h:352:119: error: use of undeclared identifier 'WL_MARSHAL_FLAG_DESTROY'
                         ZWP_INPUT_METHOD_CONTEXT_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) zwp_input_method_context_v1), WL_MARSHAL_FLAG_DESTROY);
```

R=thomasanderson

Bug: 1359189, 1359223
Change-Id: I37259433b062652234416de681f5d216e15f38f3
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3870008
Commit-Queue: Thomas Anderson <thomasanderson@chromium.org>
Reviewed-by: Thomas Anderson <thomasanderson@chromium.org>
Auto-Submit: Nick Yamane <nickdiego@igalia.com>
Cr-Commit-Position: refs/heads/main@{#1042604}