media: video: Add explicit copy assignment operator for H264SliceHeader
A new error has appeared following the addition of the explicit copy
constructor for H264SliceHeader:

../../media/video/h264_parser.h:290:3: error: definition of implicit
	copy assignment operator for 'H264SliceHeader' is deprecated
	because it has a user-provided copy constructor
	[-Werror,-Wdeprecated-copy-with-user-provided-copy]
  H264SliceHeader(const H264SliceHeader& t);
  ^
../../media/gpu/v4l2/test/h264_decoder.cc:358:32: note: in implicit
	copy assignment operator for 'media::H264SliceHeader' first
	required here
  slice_metadata->slice_header = slice_hdr;
                               ^

Explicitly declare the default copy assignment operator to make the
compiler happy.

Bug: b:261157120
Test: With use_v4l2_codec=true build v4l2_stateless_decoder for Linux
Change-Id: I51734ff245c95fcfdd294857fe626c801ac290ba
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4218179
Commit-Queue: Chen-Yu Tsai <wenst@chromium.org>
Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1102623}