Fix error running Mac signing under py3.
  pipeline.py, line 46, in _binary_architectures
  output = output.replace(' ', ',')
  TypeError: a bytes-like object is required, not 'str'

BUG=1238067
R=​rsesek@chromium.org

(cherry picked from commit dc75ba91ffbdfb6b7d004662014e945ba2665f32)

Change-Id: Id099ae273948651d976388dad4cf7b59f19e177e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3082313
Commit-Queue: Michael Moss <mmoss@chromium.org>
Reviewed-by: Robert Sesek <rsesek@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#910016}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3088373
Auto-Submit: Michael Moss <mmoss@chromium.org>
Commit-Queue: Robert Sesek <rsesek@chromium.org>
Cr-Commit-Position: refs/branch-heads/4577@{#728}
Cr-Branched-From: 761ddde228655e313424edec06497d0c56b0f3c4-refs/heads/master@{#902210}