Fix path separator issue in wpt_common that causes errors on Windows.
Example:
C:\cr\src>vpython testing\scripts\wpt_common_unittest.py
EEEE.EEE
======================================================================
ERROR: test_copy_expected_output (__main__.BaseWptScriptAdapterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing\scripts\wpt_common_unittest.py", line 363, in test_copy_expected_output
    self.assertEqual("test.html actual text", written_files[actual_path])
KeyError: 'layout-test-results\\external\\wpt\\test-actual.txt'

The actual key in dict is:
layout-test-results\\external/wpt/test-actual.txt

Fix:
Use OS specific separators.

Bug: None
Change-Id: Ia7deb8d6e4d70cdbe1dbf73f43ca8e80226712bb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2848589
Reviewed-by: Rakib Hasan <rmhasan@google.com>
Commit-Queue: Lorne Mitchell <lomitch@microsoft.com>
Cr-Commit-Position: refs/heads/master@{#875856}