Revert "Move "skip default apps" up to top level in ExternalWebAppManager"
This reverts commit 983950b467bc989226a6ef821f1db34d9fb59977.

Reason for revert:
[3872/3922] CXX obj/chrome/test/browser_tests/default_apps_browsertest.o
FAILED: obj/chrome/test/browser_tests/default_apps_browsertest.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
../../chrome/browser/extensions/default_apps_browsertest.cc:115:37: error: no member named 'SkipStartupForTesting' in 'web_app::ExternalWebAppManager'
web_app::ExternalWebAppManager::SkipStartupForTesting();
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
1 error generated.

Original change's description:
> Move "skip default apps" up to top level in ExternalWebAppManager
>
> There were two separate "skip default app" logics, one in GetConfigDir()
> and one in GetPreinstalledWebApps(). Each will disable a different set
> of default apps for a different set of circumstances.
>
> This CL unifies the two so we don't auto install any default web apps
> for sign-in/lock-screen profiles or in tests.
>
> Change-Id: Ibb8adbfded7885b1b0deb5ddb77876dd320a5830
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2677076
> Commit-Queue: Eric Willigers <ericwilligers@chromium.org>
> Reviewed-by: Eric Willigers <ericwilligers@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#852092}

TBR=ericwilligers@chromium.org,alancutter@chromium.org,chromium-scoped@luci-project-accounts.iam.gserviceaccount.com

Bug: 1173784
Change-Id: I6c8856cc1103ba50d277b1f2c7c4e4c5a1d8f417
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2682023
Reviewed-by: Alan Cutter <alancutter@chromium.org>
Commit-Queue: Alan Cutter <alancutter@chromium.org>
Cr-Commit-Position: refs/heads/master@{#852102}