Fix missing deps for obj/chrome/browser/chromeos/app_mode/app_mode/chrome_kiosk_app_launcher.o
[65682/110994] CXX obj/chrome/browser/chromeos/app_mode/app_mode/chrome_kiosk_app_launcher.o

FAILED: obj/chrome/browser/chromeos/app_mode/app_mode/chrome_kiosk_app_launcher.o
"python3" ../../build/toolchain/clang_code_coverage_wrapper.py --target-os=linux --files-to-instrument=../../.code-coverage/files_to_instrumen...(too long)
In file included from ../../chrome/browser/chromeos/app_mode/chrome_kiosk_app_launcher.cc:14:
../../chrome/browser/apps/app_service/publishers/chrome_app_deprecation.h:12:10: fatal error: 'chrome/browser/apps/app_service/publishers/proto/chrome_app_deprecation.pb.h' file not found
12 | #include "chrome/browser/apps/app_service/publishers/proto/chrome_app_deprecation.pb.h"
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Bug: 420494810
Change-Id: I72617a9d677ed8c5671d9ad63194651923842eb6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6596149
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Hidehiko Abe <hidehiko@chromium.org>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Hidehiko Abe <hidehiko@chromium.org>
Reviewed-by: Mitsuru Oshima <oshima@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1466306}