IWYU: Add missing include for std::variant usage in ai_text_session_set.h
In the CL https://crrev.com/c/5775466 used std::variant in the
chrome/browser/ai/ai_text_session_set.h, but corresponding include
was missed. Added missing include for std::variant usage.
Otherwise the build with libstdc++ fails with error:
../../chrome/browser/ai/ai_text_session_set.h:25:12:
error: ‘variant’ in namespace ‘std’ does not name a template type

Bug: 41455655
Change-Id: Ic512c4332bc85abcad210b750018f5ce188837e1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5831375
Reviewed-by: Vasilii Sukhanov <vasilii@chromium.org>
Reviewed-by: Mingyu Lei <leimy@chromium.org>
Commit-Queue: Ivan Murashov <ivan.murashov@lge.com>
Cr-Commit-Position: refs/heads/main@{#1350192}