[WebNN] Fix CoreML build by moving GetContextProperties to ContextImplCoreml
CL 8032700 included services/webnn/coreml/graph_builder_coreml.h in
webnn_context_provider_impl.cc to call GraphBuilderCoreml::GetContextProperties().
However, webnn_context_provider_impl.cc is part of webnn_service_base,
which does not depend on //third_party/coremltools:modelformat_proto.
Because graph_builder_coreml.h includes MIL.pb.h, remote execution builds
on Mac (such as 'Libfuzzer Upload Mac ASan') fail with:
fatal error: 'third_party/coremltools/mlmodel/format/MIL.pb.h' file not found

Expose static ContextProperties GetContextProperties() on ContextImplCoreml
instead (analogous to ContextImplOrt::GetContextProperties), which avoids
including graph_builder_coreml.h in webnn_context_provider_impl.cc.

Bug: 524263705
Change-Id: I0294646a4ffadcfec2e701a629bc1f206da13dda
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8482754
Commit-Queue: Phillis Tang <phillis@chromium.org>
Reviewed-by: Phillis Tang <phillis@chromium.org>
Reviewed-by: Mikołaj Wałachowski <mwalachowski@google.com>
Cr-Commit-Position: refs/heads/main@{#1708226}