Improves policy templates PRESUBMIT script
Using PRESUBMIT `output_api` to print error and warning message
instead of using `print() so that the messages can be presented more
clearly. Developers also need to confirm warning messages now.

Also slightly change the format of some error messages. Here is a fake
example now:

Syntax error(s) in file:
  C:\src\chrome\src\components\policy\resources\policy_templates.json

***************
Error: In policy OnFileDownloadedEnterpriseConnector: The policy needs to be supported now or in the future on at least one platform.
Error: Schema is invalid for policy OnPrintEnterpriseConnector
  Schema of type 'array' must have an 'items' attribute.
Error: Schema is invalid for policy PerAppTimeLimits
  Attribute 'enum' may not be empty.
  Invalid range specified: [2000; 1440]
Error: In line 26362: Bad indentation. Should be 22 spaces.
Warning: Policy EventPathEnabled doesn't seem to describe what happens when it is set to False. If possible update the description to describe this while using at least
Warning: Policy ClickToCallEnabled: 'future_on' is empty.
***************


Bug: 1342084
Change-Id: I90d5fbbc6775d9d522f0b241227dd6ddbc410013
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3759179
Reviewed-by: Igor Ruvinov <igorruvinov@chromium.org>
Commit-Queue: Owen Min <zmin@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1025247}