Revert "Bump BiDi Mapper"
This reverts commit d1c058f38ccef59809e658659de0006d7b758520.

Reason for revert: [Gardener] Appears to break the external/wpt/webdriver/tests/bidi/browser/set_download_behavior/download_behavior_allowed.py test on https://ci.chromium.org/ui/p/chromium/builders/ci/Linux%20Tests/167237/overview

Sample failure output:
This is a wdspec test.
[FAIL] test_allow_and_reset_no_destination_folder
  webdriver.bidi.error.InvalidArgumentException: invalid argument (Invalid input in "downloadBehavior".)
Harness: the test ran to completion.

Original change's description:
> Bump BiDi Mapper
>
> Bug: 42323268
> Change-Id: I542a145c4ee1487f78ba97bb2e93e8357b413070
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6994136
> Reviewed-by: Alex N. Jose <alexnj@chromium.org>
> Auto-Submit: Maksim Sadym <sadym@chromium.org>
> Commit-Queue: Alex N. Jose <alexnj@chromium.org>
> Commit-Queue: Maksim Sadym <sadym@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1522280}

Bug: 42323268
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Iec5e94c5aee2fa6388726981f6ef2cf291b330b9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6996287
Owners-Override: Alex Moshchuk <alexmos@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Alex Moshchuk <alexmos@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1522376}