Add weblayer_test_assets to weblayer_support_apk's DEPS.
WebLayerSupport.apk depends on assets/snapshot_blob_32.bin, but
android_apk("weblayer_support_apk") doesn't have the dependency.
We need to add android_assets("weblayer_test_assets") to the deps.

Sample build failure:
https://ci.chromium.org/ui/p/chromium/builders/ci/android-arm64-archive-rel/969/overview

Sample log:
KeyError: "There is no item named 'assets/snapshot_blob_32.bin' in the archive"

Change-Id: I50c889c4b78a4f2f7351fed636a2fb3e75881b33
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4122819
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Reviewed-by: Peter Beverloo <peter@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1091187}