Revert "Roll google-java-format AQn4F5N... -> vwy9yNE..."
This reverts commit 1f3c45cf34cc85216fd57016f162994d8d932651.

Reason for revert: Fails to recognize switch expressions

chrome/android/java/src/org/chromium/chrome/browser/customtabs/CustomTabsConnection.java:333:34: error: expected token: 'b'; generated ) instead
                if (o instanceof Bundle b) {

Original change's description:
> Roll google-java-format AQn4F5N... -> vwy9yNE...
>
> Changelog doesn't list any meaningful changes that I can tell.
>
> Change-Id: I6a2b701ab2172a8b7c83667adfe458e2ff5f3340
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6974728
> Auto-Submit: Andrew Grieve <agrieve@chromium.org>
> Commit-Queue: Brian Ryner <bryner@google.com>
> Reviewed-by: Brian Ryner <bryner@google.com>
> Cr-Commit-Position: refs/heads/main@{#1519526}

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Ie218741d744a73d7b8b19633fb390f8321b8b974
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6977293
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Andrew Grieve <agrieve@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1519737}