Dep on make_platform_generated in blink_headers
Make it safe (safer) to include headers from blink_headers when a target
only deps on //third_party/blink/public:blink_headers.

The blink_header target lists a large amount of blink headers, some of
which include generated headers. Without a proper dependency path to
the generators, the build is flaky and, for example, most of
//components/webcrypto could fail to build in a clean build with:
In file included from ../../components/webcrypto/status.cc:5:
In file included from ../../components/webcrypto/status.h:13:
In file included from ../../third_party/blink/public/platform/web_crypto.h:36:
In file included from ../../third_party/blink/public/platform/web_crypto_algorithm.h:35:
In file included from ../../third_party/blink/public/platform/web_private_ptr.h:36:
In file included from ../../third_party/blink/renderer/platform/heap/cross_thread_persistent.h:8:
../../third_party/blink/renderer/platform/heap/persistent.h:8:10: fatal error:
'third_party/blink/renderer/platform/heap/heap_buildflags.h' file not found

Fix by having blink_headers dep on make_platform_generated, which can be
extended to include more generated headers that blink_headers require.
This is blink_heap_buildflags currently.

Note that blink_platform_public_deps can't be used for this, because
that deps on blink_headers, so it'd be a cycle to also dep the other
way.

This fixes over 30 flaky build steps in the compilation of content_shell
alone. Other than webcrypto, those were:
obj/content/child/child/blink_platform_impl.o
obj/content/child/child/image_decoder_utils.o
obj/third_party/blink/renderer/platform/image-decoders/image_decoders/image_decoder.o

Bug: 1495268
Change-Id: I99d156ea7c78502db54e4b9c91e998f0c9a3d48a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4969777
Commit-Queue: Tomasz Śniatowski <tomasz.sniatowski@xperi.com>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1214156}