Revert "SuperSize: Filter out 0-sized .relro_padding section when present"
This reverts commit 67b30b879a87dba00fbf0c2c6173784e42f30f62.

Reason for revert: Causes:
Exception: ELF file and .map file do not agree on section sizes.
readelf: {'.rela.dyn': (3184, 0)}
.map file: {'.rela.dyn': (-1, -1)}

Original change's description:
> SuperSize: Filter out 0-sized .relro_padding section when present
>
> Bug: 476313144
> Change-Id: I314046f726064a92965964cc9305f218e3cb0ae4
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7486993
> Commit-Queue: Samuel Huang <huangs@chromium.org>
> Reviewed-by: Samuel Huang <huangs@chromium.org>
> Auto-Submit: Andrew Grieve <agrieve@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1570544}

(cherry picked from commit b5f09f8046a1cfb3ce6639685742774d36065382)

Bug: 476313144
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I6a0be2441884993a26abbc745797e56e10cd37f9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7487316
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Original-Commit-Position: refs/heads/main@{#1570715}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7490207
Auto-Submit: Harry Souders <harrysouders@google.com>
Owners-Override: Harry Souders <harrysouders@google.com>
Cr-Commit-Position: refs/branch-heads/7632@{#290}
Cr-Branched-From: 0bbdf2913883391365383b0a5dfe7bf9fd1a5213-refs/heads/main@{#1568190}