Revert "Reland "[UPM] Clean up of unused methods""
This reverts commit 631b984432b3a6c981632181edc0ecf7692cb6bf.

Reason for revert: lank/junit/src/com/google/android/apps/chrome/password_manager/PasswordStoreAndroidGoogleBackendTest.java:48: error: method getAllLogins in interface PasswordStoreAndroidBackend cannot be applied to given types

Original change's description:
> Reland "[UPM] Clean up of unused methods"
>
> This is a reland of 7b3b41fd31a270dbba92e78a9a72a6acff12926a
>
> Original change's description:
> > [UPM] Clean up of unused methods
> >
> > getAllLogins and removeLogins now can be called only with target. Since
> > internal implementation doesn't use old API anymore it is safe to delete
> > them.
> >
> > Bug: 1278748
> > Change-Id: Ie3f4cebc615d9b0438940b6b84455ab6115e8e46
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3353718
> > Reviewed-by: Ioana Pandele <ioanap@chromium.org>
> > Commit-Queue: Viktor Semeniuk <vsemeniuk@google.com>
> > Cr-Commit-Position: refs/heads/main@{#953820}
>
> Bug: 1278748
> Change-Id: I8024cd2f30a774a18bd73998d18dae21dcc0ba19
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3353496
> Reviewed-by: Vasilii Sukhanov <vasilii@chromium.org>
> Commit-Queue: Viktor Semeniuk <vsemeniuk@google.com>
> Cr-Commit-Position: refs/heads/main@{#953873}

Bug: 1278748
Change-Id: I81fe4c50e97e5a2ead0b6407332ef127e453cfb2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3355498
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: bttk - <bttk@chromium.org>
Owners-Override: bttk - <bttk@chromium.org>
Cr-Commit-Position: refs/heads/main@{#953955}