IWYU: usage of base::flat_map requires declaration of key and values in AggregationKeys
Fix build issue with libstdc++, as base::flat_map uses internally
std::pair, and the libstdc++ implementation requires full declaration
of the two contained types in pair.

Build error is:
    /usr/include/c++/12/bits/stl_pair.h: In instantiation of ‘struct std::pair<std::__cxx11::basic_string<char>, absl::uint128>’:
    /usr/include/c++/12/bits/stl_vector.h:1084:24:   required from ‘constexpr bool std::vector<_Tp, _Alloc>::empty() const [with _Tp = std::pair<std::__cxx11::basic_string<char>, absl::uint128>; _Alloc = std::allocator<std::pair<std::__cxx11::basic_string<char>, absl::uint128> >]’
    ../../base/containers/flat_tree.h:709:21:   required from ‘constexpr bool base::internal::flat_tree<Key, GetKeyFromValue, KeyCompare, Container>::empty() const [with Key = std::__cxx11::basic_string<char>; GetKeyFromValue = base::internal::GetFirst; KeyCompare = std::less<void>; Container = std::vector<std::pair<std::__cxx11::basic_string<char>, absl::uint1
    28>, std::allocator<std::pair<std::__cxx11::basic_string<char>, absl::uint128> > >]’
    ../../components/attribution_reporting/source_registration.cc:159:37:   required from here
    /usr/include/c++/12/bits/stl_pair.h:192:11: error: ‘std::pair<_T1, _T2>::second’ has incomplete type
      192 |       _T2 second;                ///< The second member
          |           ^~~~~~
    In file included from ../../components/attribution_reporting/source_registration.h:15:
    ../../components/attribution_reporting/aggregation_keys.h:18:7: note: forward declaration of ‘class absl::uint128’
       18 | class uint128;
          |       ^~~~~~~

Bug: 957519
Change-Id: If3db4a7b3dff76687f6c5b00a2b687c569b47249
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4334264
Reviewed-by: Charlie Harrison <csharrison@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#1116385}