Revert "tflite/mediapipe/eigen: avoid exposing flags to disable warnings"
This reverts commit 007ee0b888d34a32cdcc84cfa3732c94620235b9.

Reason for revert: Suspected culprit of failure here:

https://ci.chromium.org/ui/p/chromium/builders/ci/lacros-amd64-generic-rel-non-skylab/210/overview

Original change's description:
> tflite/mediapipe/eigen: avoid exposing flags to disable warnings
>
> eigen's config contains a handful of flags that disable warnings.
> tflite was depending on this config via a public_config, which
> means any code using tflite was inheriting a bunch of flags that
> disable warnings. This is risky, and not something we should do.
>
> This patch splits eigen's config into two. The one that tflite
> depends upon via public_config does not disable any warnings. This
> means code using tflite no longer disables a bunch of compiler
> warnings. As a result of this I needed to add some flags to disable
> warnings in other code that was picking up the flags from eigen.
> That this code needs to disable warnings is not new, it was masked
> by eigen's config.
>
> This also adds -Wno-unused-function to tflite as this was masked
> by flags from eigen. Without it the following error is generated:
>
> ../../third_party/tflite/src/tensorflow/lite/kernels/internal/optimized/neon_tensor_utils.cc:587:13: error: unused function 'DotprodMatrixBatchFourVectorMultiplyAccumulate' [-Werror,-Wunused-function]
> 587 | static void DotprodMatrixBatchFourVectorMultiplyAccumulate(
> |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
>
>
> Bug: 1491776
> Change-Id: I95424b5cabe94066d4b3615565ce5a4f3f1865fe
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4929809
> Reviewed-by: Sophie Chang <sophiechang@chromium.org>
> Commit-Queue: Scott Violet <sky@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1209520}

Bug: 1491776
Change-Id: I6728f818bce140b8b4946aac1ff0d2bd31a619cc
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4939256
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Devlin Cronin <rdevlin.cronin@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Devlin Cronin <rdevlin.cronin@chromium.org>
Owners-Override: Devlin Cronin <rdevlin.cronin@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1209529}