Revert "Adding OS warning to site-settings"
This reverts commit 09ab4677ebe8c3f126a1763ca0b0e35c73e459fb.

Reason for revert: Breaks compile: https://ci.chromium.org/ui/p/chromium/builders/ci/linux-cfm-rel/60501/overview : ../../chrome/browser/ash/privacy_hub/privacy_hub_util.cc:304:25: error: member access into incomplete type 'SessionControllerImpl'
  304 |       session_controller->GetLastActiveUserPrefService();
      |                         ^
../../ash/shell.h:246:7: note: forward declaration of 'ash::SessionControllerImpl'
  246 | class SessionControllerImpl;
      |       ^
In file included from ../../chrome/browser/ash/privacy_hub/privacy_hub_util.cc:5:

Original change's description:
> Adding OS warning to site-settings
>
> In case, geolocation, camera or mic is blocked on OS level, a warning is
> displayed in the site-settings in chrome.
> Design: go/privacy-hub-v2.3-designdoc
>
> Bug: b/331784136
> Change-Id: I1c9213cecfa0ce513aa7af970369494d7592246d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5513147
> Reviewed-by: Filipa Senra <fsenra@google.com>
> Reviewed-by: Vasilii Sukhanov <vasilii@chromium.org>
> Commit-Queue: Jan Láník <janlanik@google.com>
> Reviewed-by: Elias Klim <elklm@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1336071}

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: b/331784136
Change-Id: I90e35ef221d52edd2e0eb827bfe803d46aa5b537
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5756363
Commit-Queue: Jan Láník <janlanik@google.com>
Auto-Submit: Joshua Pawlicki <waffles@chromium.org>
Reviewed-by: Jan Láník <janlanik@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Joshua Pawlicki <waffles@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1336101}