Fix syntax error in /chrome/tools/build/presubmit.py
This script tries to concatenate bytes objects with a string which is a
syntax error. This syntax error prevents the error from outputting and
blocks all other checks from outputting. This change fixes the syntax
error by just converting the bytes to strings.

After the fix, errors are correctly outputted, for example:
win\FILES.cfg syntax error:
  File "win\FILES.cfg", line 507
    {
    ^
SyntaxError: invalid syntax

Bug: 1275183
Change-Id: I6b005e294aa6fafdedf4c7b0028d554d64733836
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3309225
Reviewed-by: Michael Moss <mmoss@chromium.org>
Commit-Queue: Cliff Smolinsky <cliffsmo@microsoft.com>
Cr-Commit-Position: refs/heads/main@{#946605}