Revert "Remove FILES.cfg from chromeos"
This reverts commit 7efae5e020bcf919363e4299853df34a465d4bfb.

Reason for revert: Breaks cq builder like:
https://ci.chromium.org/p/chromium/builders/try/linux-chromeos-rel/1070948
FAILED: gen_linux_ash_chromium_cipd_yaml_cipd.yaml
python3 ../../build/cipd/cipd_from_file.py --description=Prebuilt\ test\ binary. --buildtype=dev --arch=64bit --files_file=../../chrome/tools/build/chromeos/FILES.cfg --package=chromium/testing/linux-ash-chromium/x86_64/ash.zip --install_mode=copy --output_yaml_file=gen_linux_ash_chromium_cipd_yaml_cipd.yaml
Traceback (most recent call last):
  File "../../build/cipd/cipd_from_file.py", line 65, in <module>
    main()
  File "../../build/cipd/cipd_from_file.py", line 61, in main
    _Process(args)
  File "../../build/cipd/cipd_from_file.py", line 25, in _Process
    fileobj = _ParseFilesCfg(args.files_file)
  File "../../build/cipd/cipd_from_file.py", line 14, in _ParseFilesCfg
    raise IOError('Files list does not exist (%s).' % files_file)
OSError: Files list does not exist (../../chrome/tools/build/chromeos/FILES.cfg).

Original change's description:
> Remove FILES.cfg from chromeos
>
> FILES.cfg is now obsolete for chromeos builders. The PRESUBMIT.py file
> for FILES.cfg is not needed anymore because they are all removed.
>
> Bug: 1260176
> Change-Id: I91bacba2fd570f239d0a0dbe83fd5a28affb24bf
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3362243
> Reviewed-by: Michael Moss <mmoss@chromium.org>
> Commit-Queue: Wanda Mora <morawand@google.com>
> Cr-Commit-Position: refs/heads/main@{#955378}

Bug: 1260176
Change-Id: Ifbb3b2096bc109182782f25b90e02a750e0b7899
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3366812
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Sven Zheng <svenzheng@chromium.org>
Owners-Override: Sven Zheng <svenzheng@chromium.org>
Auto-Submit: Sven Zheng <svenzheng@chromium.org>
Cr-Commit-Position: refs/heads/main@{#955416}