Revert "[iOS] Fix -[TranslateInfobarTestCase testTranslateAfterReaderMode]"
This reverts commit 5232b8d771bb7ef4ebd8c16b3e1e442dae62e789.

Reason for revert:

breaks https://ci.chromium.org/ui/p/chromium/builders/luci.chromium.ci/ios-simulator-full-configs starting with build 72985:

[07:04:13:INFO] /../../ios/chrome/browser/infobars/ui_bundled/translate_infobar_egtest.mm:1211: error: -[TranslateInfobarTestCase testTranslateAfterReaderMode] : Immediately halt execution of testcase - ((([self isAfterTranslateBannerVisible])) is true) failed
[07:04:13:INFO] 
[07:04:13:INFO] Show Original Banner was not found.
[07:04:13:INFO] 
[07:04:13:INFO] App-side Screenshot at Point-of-Failure: /Users/chrome-bot/Library/Developer/CoreSimulator/Devices/CE7FCA06-04E2-4162-A29A-9C5817092F61/data/Containers/Data/Application/C5711AA0-17C3-4E34-A550-26B2E45E9F83/Documents/AssertionFailedException-AF4D6D34-B71F-455C-9FC7-1842931B4E75/app_screenshot.png


Original change's description:
> [iOS] Fix -[TranslateInfobarTestCase testTranslateAfterReaderMode]
>
> This CL fixes the test by ensuring that required flag are enabled while
> it is running.
>
> Change-Id: I006b4db9cba8f4d546da0ff453773cacf5800265
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6798276
> Reviewed-by: Gauthier Ambard <gambard@chromium.org>
> Commit-Queue: Gauthier Ambard <gambard@chromium.org>
> Auto-Submit: Quentin Pubert <qpubert@google.com>
> Commit-Queue: Quentin Pubert <qpubert@google.com>
> Cr-Commit-Position: refs/heads/main@{#1494128}

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I87bd37b9e2d4fa6277e8c91fc1927942deb7f76b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6802301
Owners-Override: Avi Drissman <avi@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Avi Drissman <avi@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1494239}