Revert "Reapply "Refactor tools/metrics/PRESUBMIT.py to use subprocesses""
This reverts commit eccb9b7f9f5b3c02ac392b23e5450182cb75799b.

Reason for revert: Reverting this change as a gardener to restore the win-presubmit health (https://ci.chromium.org/ui/p/chromium/builders/ci/win-presubmit).

With this change, when running the presubmit checks on a large patchset, subprocess.Popen fails on Windows with the following error due to the command line length limit:

FileNotFoundError: [WinError 206] The filename or extension is too long

I'm reverting this to verify if the presubmit health is restored.

Original change's description:
> Reapply "Refactor tools/metrics/PRESUBMIT.py to use subprocesses"
>
> This reverts commit 1ce9d104787120878b650f1b09373f3ba0ae60fb.
>
> The problem was that we didn't use shell on windows. We already had this
> issue in the past and I actually realize that we should just reuse
> previous solution and use `script_checker.check_scripts` instead of
> another RunPythonScript.
>
> This reland coverts the encapsulated presubmit into `TestableScript` and
> uses `script_checker.check_scripts`.
>
> Bug: 488351821
> Change-Id: I2197257a0c69e843043fe4479b9ee50c1e1eda46
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7893669
> Commit-Queue: Andrzej Fiedukowicz <afie@google.com>
> Reviewed-by: Ramon Cano Aparicio <rcanoaparicio@google.com>
> Cr-Commit-Position: refs/heads/main@{#1641009}

Bug: 488351821
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I3e601edc1c6bfb7bf57b5fba5b896c1fc5be350e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7898724
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Minoru Chikamune <chikamune@chromium.org>
Owners-Override: Minoru Chikamune <chikamune@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1641434}