Revert "Roll clang llvmorg-14-init-1380-gee659383-1 : llvmorg-14-init-2175-g945cde8b-1"
This reverts commit b2a4be0187d9845eba5d8286d152f3d48e396f01.

Reason for revert: Speculative revert for a weird compilation error on GPU FYI on ChromeOS, starting here:
https://ci.chromium.org/ui/p/chromium/builders/ci/ChromeOS%20FYI%20Release%20(kevin)/6203/blamelist
and here:
https://ci.chromium.org/ui/p/chromium/builders/ci/ChromeOS%20FYI%20Release%20(amd64-generic)/4406/blamelist

../../third_party/angle/src/libANGLE/renderer/gl/egl/gbm/DisplayGbm.cpp:215:9: error: too few arguments to function call, expected 3, have 2; did you mean 'DispatchTableGL::bindRenderbuffer'?
sm->bindRenderbuffer(GL_RENDERBUFFER, mColorBuffer);

bindRenderbuffer most certainly should only have 2 arguments, and checking codesearch for StateManagerGL::bindRenderbuffer verifies this.

Original change's description:
> Roll clang llvmorg-14-init-1380-gee659383-1 : llvmorg-14-init-2175-g945cde8b-1
>
> Ran `./tools/clang/scripts/upload_revision.py 945cde8b6a4579406886d08f803b632e00f0b1ec`.
>
> Bug: 1241217
> Change-Id: I78b6bdf8da92d82241bb1ab301291f45e03de3e7
> Cq-Include-Trybots: chromium/try:chromeos-amd64-generic-cfi-thin-lto-rel
> Cq-Include-Trybots: chromium/try:dawn-win10-x86-deps-rel
> Cq-Include-Trybots: chromium/try:linux-chromeos-dbg
> Cq-Include-Trybots: chromium/try:linux_angle_deqp_rel_ng
> Cq-Include-Trybots: chromium/try:linux_chromium_cfi_rel_ng
> Cq-Include-Trybots: chromium/try:linux_chromium_chromeos_msan_rel_ng
> Cq-Include-Trybots: chromium/try:linux_chromium_compile_dbg_32_ng
> Cq-Include-Trybots: chromium/try:linux_chromium_msan_rel_ng
> Cq-Include-Trybots: chromium/try:mac-arm64-rel,mac_chromium_asan_rel_ng
> Cq-Include-Trybots: chromium/try:win-asan,win7-rel
> Cq-Include-Trybots: chromium/try:android-official,fuchsia-official
> Cq-Include-Trybots: chromium/try:mac-official,linux-official
> Cq-Include-Trybots: chromium/try:win-official,win32-official
> Cq-Include-Trybots: chrome/try:iphone-device,ipad-device
> Cq-Include-Trybots: chrome/try:linux-chromeos-chrome
> Cq-Include-Trybots: chrome/try:win-chrome,win64-chrome,mac-chrome
> Cq-Include-Trybots: chrome/try:linux-pgo,mac-pgo,win32-pgo,win64-pgo
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3115626
> Reviewed-by: Nico Weber <thakis@chromium.org>
> Reviewed-by: Arthur Eubanks <aeubanks@google.com>
> Commit-Queue: Arthur Eubanks <aeubanks@google.com>
> Cr-Commit-Position: refs/heads/main@{#915333}

Bug: 1241217
Change-Id: I52147a2da469030b39fa1c9c2837cf5dace08b33
Cq-Include-Trybots: chromium/try:chromeos-amd64-generic-cfi-thin-lto-rel
Cq-Include-Trybots: chromium/try:dawn-win10-x86-deps-rel
Cq-Include-Trybots: chromium/try:linux-chromeos-dbg
Cq-Include-Trybots: chromium/try:linux_angle_deqp_rel_ng
Cq-Include-Trybots: chromium/try:linux_chromium_cfi_rel_ng
Cq-Include-Trybots: chromium/try:linux_chromium_chromeos_msan_rel_ng
Cq-Include-Trybots: chromium/try:linux_chromium_compile_dbg_32_ng
Cq-Include-Trybots: chromium/try:linux_chromium_msan_rel_ng
Cq-Include-Trybots: chromium/try:mac-arm64-rel,mac_chromium_asan_rel_ng
Cq-Include-Trybots: chromium/try:win-asan,win7-rel
Cq-Include-Trybots: chromium/try:android-official,fuchsia-official
Cq-Include-Trybots: chromium/try:mac-official,linux-official
Cq-Include-Trybots: chromium/try:win-official,win32-official
Cq-Include-Trybots: chrome/try:iphone-device,ipad-device
Cq-Include-Trybots: chrome/try:linux-chromeos-chrome
Cq-Include-Trybots: chrome/try:win-chrome,win64-chrome,mac-chrome
Cq-Include-Trybots: chrome/try:linux-pgo,mac-pgo,win32-pgo,win64-pgo
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3120276
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Kai Ninomiya <kainino@google.com>
Commit-Queue: Kai Ninomiya <kainino@chromium.org>
Cr-Commit-Position: refs/heads/main@{#915473}