[Sheriff] Disable MissingInflatedId with @SuppressLint.
The lint update from
https://chromium-review.googlesource.com/c/chromium/src/+/3714568
https://chromium-review.googlesource.com/c/chromium/src/+/3723350
caused the following error:
ChromeActivity.java:748: Error: @layout/main does not contain a
declaration with id control_container [MissingInflatedId]
(ControlContainer) findViewById(R.id.control_container);

Bug: 1336778
Change-Id: Id03d080860b45747263a9cd3bdcbd43337829423
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3720673
Commit-Queue: Christoph Schwering <schwering@google.com>
Reviewed-by: Friedrich Horschig <fhorschig@chromium.org>
Reviewed-by: James Lee <ljjlee@google.com>
Owners-Override: Christoph Schwering <schwering@google.com>
Cr-Commit-Position: refs/heads/main@{#1017575}