[119] Don't select at an invalid index path
This CL addresses a crash we see in Stable, with the following
exception:

> NSInternalInconsistencyException: Attempted to scroll the
> collection view to an out-of-bounds item (15) when there are
> only 15 items in section 0.

(cherry picked from commit ae61a148bbc31b5e8ed1e963b4c705bb225e58e2)

Bug: 1487015
Change-Id: I88ffd7648b7548bf2b8fb71f28ae2db779cc1b59
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4915697
Code-Coverage: findit-for-me@appspot.gserviceaccount.com <findit-for-me@appspot.gserviceaccount.com>
Commit-Queue: Louis Romero <lpromero@google.com>
Reviewed-by: Gauthier Ambard <gambard@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1206405}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4931551
Auto-Submit: Louis Romero <lpromero@google.com>
Reviewed-by: Aliona Dangla <alionadangla@chromium.org>
Cr-Commit-Position: refs/branch-heads/6045@{#299}
Cr-Branched-From: 905e8bdd32d891451d94d1ec71682e989da2b0a1-refs/heads/main@{#1204232}