Move //components/reporting/proto:configuration_file_proto to public_deps
The proto's header files are used from header files in the browser
component. The browser component depends on storage_selector but allows
circular includes from it. Due to the missing dependency edge, we can
get transient compilation errors as below:

```
In file included from ../../chrome/browser/policy/messaging_layer/storage_selector/storage_selector.cc:5:
In file included from ../../chrome/browser/policy/messaging_layer/storage_selector/storage_selector.h:19:
../../chrome/browser/policy/messaging_layer/util/upload_declarations.h:12:10: fatal error: 'components/reporting/proto/synced/configuration_file.pb.h' file not found
   12 | #include "components/reporting/proto/synced/configuration_file.pb.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

R=avi@chromium.org

Change-Id: Id80e1c1aa33b03703a420aad25dcd5784d506485
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5605025
Reviewed-by: Avi Drissman <avi@chromium.org>
Commit-Queue: danakj <danakj@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1311528}