chore(deps): Bump wpt from `17e2e02` to `2e54748` (#3471)
Bumps [wpt](https://github.com/web-platform-tests/wpt) from `17e2e02` to
`2e54748`.
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/2e547483d48c482395a801e2a82fdae5a60983e3"><code>2e54748</code></a>
QuotaExceededError: Update leftover QuotaExceededError instances (<a
href="https://redirect.github.com/web-platform-tests/wpt/issues/52856">#52856</a>)</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/9765d17152dbbcb4693611a987640f7907cf5843"><code>9765d17</code></a>
Add &quot;sub&quot; to DBSC JWT</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/bcc1209b52fdc56224836039594a72a72d8940ae"><code>bcc1209</code></a>
[replaced] Don't attempt to stretch-fit within MinMaxSizesFunc
lambda.</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/cc1fc759b977b4fa0ef569130de5cf10ccb73a3a"><code>cc1fc75</code></a>
[soft navs] Make popstate-multiple-backs WPT less racy.</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/9c805060889140002cd772094636d78800c9ce0a"><code>9c80506</code></a>
[vt] Fix raciness with test harness</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/77752ad86cd0bd36d1f9ed1075574ec9c7432c68"><code>77752ad</code></a>
[vt] Cleanup workaround for clipping bug</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/70f0a19eac6b582538f523fdfe19fced1b6b4e1f"><code>70f0a19</code></a>
Make ToggleEvent.source WPTs non-tentative</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/a2585863c66cdf9982c6209eb4e3c47307c1030a"><code>a258586</code></a>
[gap-decorations] Address null-dereference in
<code>PaintGapDecorations</code></li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/21c375ea54225fa4b93932bea5ace42abf02a694"><code>21c375e</code></a>
Add test for border-radius with clip along one axis</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/b4268a8bd2ee079f0f1da1d36c6c709a7366bb81"><code>b4268a8</code></a>
Nesting selectors that refer to pseudo elements must not match the
originatin...</li>
<li>Additional commits viewable in <a
href="https://github.com/web-platform-tests/wpt/compare/17e2e028455d9f86ae9a428fccb292b354d89ed6...2e547483d48c482395a801e2a82fdae5a60983e3">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: browser-automation-bot <133232582+browser-automation-bot@users.noreply.github.com>