IWYU: std::vector requires including <vector> in OnDeviceHeadModel
Fix build error:
../../components/omnibox/browser/on_device_head_model.h:68:15: error: ‘vector’ in namespace ‘std’ does not name a template type

Bug: 957519
Change-Id: Idad1853af6afbf31faf288b6b5a73007497338a8
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2453452
Reviewed-by: Angela Yoeurng <yoangela@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/master@{#814796}