Revert "Wi-Fi Sync: Record connection success metrics after login."
This reverts commit afbb8a3503efd7b11028776140b7108b56cc7421.

Reason for revert:
Failed to compile on some bots.

e.g.
https://ci.chromium.org/ui/p/chromium/builders/ci/Linux%20ChromiumOS%20Full/189577/overview

synced_network_metrics_logger.h:142:9: error: no type named 'Time' in namespace 'base'

Bug: 1228910

Original change's description:
> Wi-Fi Sync: Record connection success metrics after login.
>
> Previously, if a Wi-Fi connection to a synced network was completed
> during or immediately after login it would not be recorded to UMA.
>
> Change-Id: I2de4d438d7b3f4aed12f0411dc26b24ee58119f4
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3022584
> Commit-Queue: Jon Mann <jonmann@chromium.org>
> Reviewed-by: Claude van der Merwe <cvandermerwe@google.com>
> Cr-Commit-Position: refs/heads/master@{#901117}

Change-Id: I33f37d7045c4be392e9df8aa2a823e929bf05441
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3025548
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Jon Mann <jonmann@chromium.org>
Owners-Override: Xiyuan Xia <xiyuan@chromium.org>
Auto-Submit: Xiyuan Xia <xiyuan@chromium.org>
Commit-Queue: Xiyuan Xia <xiyuan@chromium.org>
Cr-Commit-Position: refs/heads/master@{#901181}