Remove reflection from stylus rich gestures code
This CL moves the gesture handling logic into the input connection.
It replaces StylusGestureHandler with a class to convert from Android
to Blink gestures.
It also removes reflection from StylusGestureConverterTest.

Not removing reflection from StylusGestureEndToEndTest as
android-nougat-x86-rel fails to compile content_shell_test_apk due to
a NoClassDefFoundError.

Bug: 1416170
Change-Id: Ifa619a0d4514e7e5d041064168deb18132b43828
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4670506
Code-Coverage: Findit <findit-for-me@appspot.gserviceaccount.com>
Reviewed-by: Jinsuk Kim <jinsukkim@chromium.org>
Reviewed-by: Peter Conn <peconn@chromium.org>
Commit-Queue: Alex Mitra <alexmitra@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1170003}