Revert "indexeddb: defer journal cleanup in CommitPhaseTwo"
This reverts commit 715577e4d7cb62b678d194efa5f6ea17fd002c5b.

Reason for revert: This caused compile failure:
https://ci.chromium.org/p/chromium/builders/ci/fuchsia-arm64-cast/97365?
[8734/14809] CXX obj/content/test/content_unittests__exec/indexed_db_backing_store_unittest.o
FAILED: obj/content/test/content_unittests__exec/indexed_db_backing_store_unittest.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
../../content/browser/indexed_db/indexed_db_backing_store_unittest.cc:924:20: error: no member named 'SetExecuteJournalCleaningOnNoTransactionsForTesting' in 'content::indexed_db_backing_store_unittest::TestableIndexedDBBackingStore'
backing_store()->SetExecuteJournalCleaningOnNoTransactionsForTesting();
~~~~~~~~~~~~~~~  ^
1 error generated.

Original change's description:
> indexeddb: defer journal cleanup in CommitPhaseTwo
>
> Currently, IndexedDBBackingStore::Transaction::CommitPhaseTwo
> calls IndexedDBBackingStore::DidCommitTransaction which cleans up blobs
> in the recovery journal (under some conditions).  Unfortunately, it
> doesn't remove the blobs that were just written in that transaction from
> the recovery journal prior to calling DidCommitTransaction.
>
> This patch rearranges the calls so that DidCommitTransaction is always
> called in CommitPhaseTwo, but only after the journal has been updated.
>
> Bug: 1131151
> Change-Id: I703d250f42b3de77a41b7ebc151ae71db5dbda6c
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2495872
> Commit-Queue: enne <enne@chromium.org>
> Auto-Submit: enne <enne@chromium.org>
> Reviewed-by: Marijn Kruisselbrink <mek@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#820486}

TBR=mek@chromium.org,enne@chromium.org

Change-Id: Id3876068e31e91817ff7c396f024cf159b3c1dfe
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1131151
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2496035
Reviewed-by: Scott Violet <sky@chromium.org>
Commit-Queue: Scott Violet <sky@chromium.org>
Cr-Commit-Position: refs/heads/master@{#820492}