[m104][rollicu] Update TZ to 2022b
This CL is the M104 branch equivalent of
https://chromium-review.googlesource.com/c/chromium/src/+/3841326

IANA announcement:
https://mm.icann.org/pipermail/tz-announce/2022-August/000071.html

Upstream ICU PR:
https://github.com/unicode-org/icu/pull/2157

How to verify - In JavaScript

(new Date("2022-09-05T12:34:56Z")).toLocaleTimeString("en", {timeZone: "America/Santiago", timeZoneName:"long"})
(new Intl.DateTimeFormat("en",  {timeZone: "Europe/Kiev"})).resolvedOptions().timeZone
(new Intl.DateTimeFormat("en",  {timeZone: "Europe/Kyiv"})).resolvedOptions().timeZone

Before the change:
> '9:34:56 AM Chile Summer Time'
> 'Europe/Kiev'
>  RangeError: Invalid time zone specified: Europe/Kyiv

After the change:
> '8:34:56 AM Chile Standard Time'
> 'Europe/Kiev'
> 'Europe/Kiev'

Changes
"
Briefly:
     Chile's DST is delayed by a week in September 2022.
     Iran no longer observes DST after 2022.
     Rename Europe/Kiev to Europe/Kyiv.
     New zic -R option
     Vanguard form now uses %z.
     Finish moving duplicate-since-1970 zones to 'backzone'.
     New build option PACKRATLIST
     New tailored_tarballs target, replacing rearguard_tarballs

   Changes to future timestamps

     Chile's 2022 DST start is delayed from September 4 to September 11.
     (Thanks to Juan Correa.)

     Iran plans to stop observing DST permanently, after it falls back
     on 2022-09-21.  (Thanks to Ali Mirjamali.)

   Changes to past timestamps

     Finish moving to 'backzone' the location-based zones whose
     timestamps since 1970 are duplicates; adjust links accordingly.
     This change ordinarily affects only pre-1970 timestamps, and with
     the new PACKRATLIST option it does not affect any timestamps.
     In this round the affected zones are Antarctica/Vostok,
     Asia/Brunei, Asia/Kuala_Lumpur, Atlantic/Reykjavik,
     Europe/Amsterdam, Europe/Copenhagen, Europe/Luxembourg,
     Europe/Monaco, Europe/Oslo, Europe/Stockholm, Indian/Christmas,
     Indian/Cocos, Indian/Kerguelen, Indian/Mahe, Indian/Reunion,
     Pacific/Chuuk, Pacific/Funafuti, Pacific/Majuro, Pacific/Pohnpei,
     Pacific/Wake and Pacific/Wallis, and the affected links are
     Arctic/Longyearbyen, Atlantic/Jan_Mayen, Iceland, Pacific/Ponape,
     Pacific/Truk, and Pacific/Yap.

     From fall 1994 through fall 1995, Shanks wrote that Crimea's
     DST transitions were at 02:00 standard time, not at 00:00.
     (Thanks to Michael Deckers.)

     Iran adopted standard time in 1935, not 1946.  In 1977 it observed
     DST from 03-21 23:00 to 10-20 24:00; its 1978 transitions were on
     03-24 and 08-05, not 03-20 and 10-20; and its spring 1979
     transition was on 05-27, not 03-21.
     (Thanks to Roozbeh Pournader and Francis Santoni.)

     Chile's observance of -04 from 1946-08-29 through 1947-03-31 was
     considered DST, not standard time.  Santiago and environs had moved
     their clocks back to rejoin the rest of mainland Chile; put this
     change at the end of 1946-08-28.  (Thanks to Michael Deckers.)

     Some old, small clock transitions have been removed, as people at
     the time did not change their clocks.  This affects Asia/Hong_Kong
     in 1904, Asia/Ho_Chi_Minh in 1906, and Europe/Dublin in 1880.

   Changes to zone name

     Rename Europe/Kiev to Europe/Kyiv, as "Kyiv" is more common in
     English now.  Spelling of other names in Ukraine has not yet
     demonstrably changed in common English practice so for now these
     names retain old spellings, as in other countries (e.g.,
     Europe/Prague not "Praha", and Europe/Sofia not "Sofiya").
"

Bug: 1354379
Change-Id: I2cfce87ef632ff1741977adb7c35d45d13a42e2b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3846896
Reviewed-by: Jungshik Shin <jshin@chromium.org>
Commit-Queue: Frank Tang <ftang@chromium.org>
Cr-Commit-Position: refs/branch-heads/5112@{#1512}
Cr-Branched-From: b13d3fe7b3c47a56354ef54b221008afa754412e-refs/heads/main@{#1012729}