chore(deps): Bump wpt from `4af8376` to `7cc53e6` (#4027)
Bumps [wpt](https://github.com/web-platform-tests/wpt) from `4af8376` to
`7cc53e6`.
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/7cc53e677dfae85f4af017ed0d7d59935bdd0947"><code>7cc53e6</code></a>
Add missing WPT coverage for CustomElementRegistry.initialize()</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/2e2e15b1d44551c5798cdd2f26d846f426eb6856"><code>2e2e15b</code></a>
Fix focus navigation for popover that is shadow host</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/66d5d24159eb3637d00edf8cf3fa2a7b07f5e4a0"><code>66d5d24</code></a>
When &lt;link rel=stylesheet&gt; media attribute changes, don't
re-fetch</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/f47e795f6c5f833b3318b2ac6e506c566be00996"><code>f47e795</code></a>
Add fuzz annotation to WPT fragmented-at-start-ignored.html. (<a
href="https://redirect.github.com/web-platform-tests/wpt/issues/57369">#57369</a>)</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/e3d5424555c03dd46c32f2daa074aefa84c68da7"><code>e3d5424</code></a>
[soft navigations] Set up paint tracking for inline style and class
attribute...</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/e3c46fdf5587369127de2863a7e38295f4e07f16"><code>e3c46fd</code></a>
url: more drive letter quirk coverage</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/3e32b1b196d97a9ac8f373707a1825f031c156de"><code>3e32b1b</code></a>
Throw TypeError for incompatible types in CSSNumericValue
operations</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/984156521a45b97285c47ff4039bb00a045bdbeb"><code>9841565</code></a>
Do not set x-math lang on MathML elements by default when font-family:
math i...</li>
<li><a
href="https://github.com/web-platform-tests/wpt/commit/f67ee20aa7eb5a32af7c9fdb7615e0a02f612d62"><code>f67ee20</code></a>
HTML: style load event not fired for DOM mutations while the element is
still...</li>
<li>See full diff in <a
href="https://github.com/web-platform-tests/wpt/compare/4af83765a2f5708bd7a8534a4db5d659b2cf6619...7cc53e677dfae85f4af017ed0d7d59935bdd0947">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>