PRESUBMIT: Update JSON parse test
In my tree, running `./PRESUBMIT_test.py` yields

```
======================================================================
FAIL: testFailure (__main__.JSONParsingTest.testFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/kdlee/chromium/src/./PRESUBMIT_test.py", line 585, in testFailure
    self.assertTrue(
    ~~~~~~~~~~~~~~~^
        expected_error in str(actual_error),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        "'%s' not found in '%s'" % (expected_error, actual_error))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: False is not true : 'Expecting property name' not found in 'Illegal trailing comma before end of object: line 1 column 21 (char 20)'
```

which is divergent from what happens when presubmit hooks actually run
(apparently through vpython).

*   Update the shebang to explicitly use vpython3.

*   Specific to the JSON parsing tests, add the mock filename to the
    diagnostic message as well to make it more obvious which test case
    failed.

Change-Id: I32ca6aa379e5d9cd6076eb5c6779fe27ce4085dd
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7061691
Commit-Queue: Kalvin Lee <kdlee@chromium.org>
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1536435}