Revert "[tools/jj] Sync Git worktree HEAD before presubmits"
This reverts commit bfbbaeaaedaab6e743557aa90d7dbcbfe99af04c.

Reason for revert: Running `jj upload` without `-r` would cause a new
head to be created on top of your current commit, then fail upload with
a message like:

Error: Refusing to upload revision rotltlmznowr because it is empty
Hint: Perhaps you squashed then ran upload? Maybe you meant to upload
the parent commit instead (eg. @-)

Original change's description:
> [tools/jj] Sync Git worktree HEAD before presubmits
>
> When using Jujutsu with a colocated Git repository or Git worktrees
> (such as in Rift workspaces), Git's HEAD reference is detached and
> does not automatically track Jujutsu's working copy or mutable
> commits. Consequently, depot_tools' `git cl presubmit` defaults
> diff and description calculations to an obsolete Git HEAD (often
> origin/main from checkout time), resulting in false presubmit errors
> (e.g. CheckSubmodulesInDepsFile reporting missing submodules).
>
> This CL updates `tools/jj/upload.py` to synchronize Git's HEAD
> to the tip commit being uploaded (`to_upload[0]['commit_id']`) via
> `git update-ref --no-deref HEAD <commit_id>` immediately before
> invoking `git cl presubmit`.
>
> Bug: None
> Change-Id: I9c246d85686508be138149cdb3b8fe8b6a6a6964
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8350744
> Commit-Queue: Jan Wilken Dörrie <jdoerrie@chromium.org>
> Reviewed-by: Matt Stark <msta@google.com>
> Cr-Commit-Position: refs/heads/main@{#1691414}

Bug: None
Change-Id: Id457ce873d39a17ad7a3ba5f24e4429aab3fb44d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8466005
Auto-Submit: Sam Maier <smaier@google.com>
Reviewed-by: Jan Wilken Dörrie <jdoerrie@chromium.org>
Reviewed-by: Matt Stark <msta@google.com>
Commit-Queue: Sam Maier <smaier@google.com>
Cr-Commit-Position: refs/heads/main@{#1706999}