Add the missing dependency for calendar pixel test
Otherwise the ash_pixeltests cannot build with error:
error: undefined symbol: google_apis::calendar::DateTime::DateTime()
>>> referenced by calendar_unittest_utils.cc:29
(../../ash/system/time/calendar_unittest_utils.cc:29)
>>>               obj/ash/ash_pixeltests/calendar_unittest_utils.o:
(ash::calendar_test_utils::CreateEvent(char const*, char const*, char
const*, char const*, google_apis::calendar::CalendarEvent::EventStatus,
google_apis::calendar::CalendarEvent::ResponseStatus, bool))

Bug: b:259918463
Change-Id: Ie53fd37d8acc1c1481231e036c9b37c90edbe71e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4068722
Reviewed-by: Andrew Xu <andrewxu@chromium.org>
Commit-Queue: Jiaming Cheng <jiamingc@chromium.org>
Commit-Queue: Andrew Xu <andrewxu@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1077817}