Reland "Support reconnectable sessions in CrdAdminSessionController"
This is a reland of commit 06a65a37e4c41e5850c39288ef70f860c267a422

The original CL was reverted because it broke fuzzer code
https://ci.chromium.org/ui/p/chromium/builders/ci/Libfuzzer%20Upload%20Chrome%20OS%20ASan/102595/overview

[77649/80085] CXX obj/chrome/browser/ash/policy_remote_commands_fuzzer/remote_commands_fuzzer.o
FAILED: obj/chrome/browser/ash/policy_remote_commands_fuzzer/remote_commands_fuzzer.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../chrome/browser/ash/policy/remote_commands/remote_commands_fuzzer.cc:100:47: error: variable type 'StubDeviceCommandStartCrdSessionJobDelegate' is an abstract class
StubDeviceCommandStartCrdSessionJobDelegate start_crd_session_job_delegate;

Original change's description:
> Support reconnectable sessions in CrdAdminSessionController
>
> This also introduces the reconnectable sessions API in
> RemoteSupportHostAsh.
>
> Change-Id: I39acc9844d45d45b6d93a3cc67139e2fb71df307
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4618043
> Reviewed-by: Joe Downing <joedow@chromium.org>
> Auto-Submit: Jeroen Dhollander <jeroendh@google.com>
> Commit-Queue: Jeroen Dhollander <jeroendh@google.com>
> Cr-Commit-Position: refs/heads/main@{#1162402}

Change-Id: If12226c07cca757bfd1b8159cf9bc3286bd6d201
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4647332
Reviewed-by: Joe Downing <joedow@chromium.org>
Auto-Submit: Jeroen Dhollander <jeroendh@google.com>
Reviewed-by: Roman Sorokin <rsorokin@google.com>
Commit-Queue: Roman Sorokin <rsorokin@google.com>
Cr-Commit-Position: refs/heads/main@{#1163437}