Revert "Tracking Protection 100%: Separate the page info code"
This reverts commit 6a8511c3114d999d5b2507d9c14633a69a2baea7.

Reason for revert: conflicts with crrev.com/c/5378371 which landed just before this patch:

PageInfoTrackingProtectionController.java:124: error: incompatible types: BrowserContextHandle cannot be converted to SiteSettingsDelegate
        new WebsitePermissionsFetcher(mMainController.getBrowserContext())

https://ci.chromium.org/ui/p/chromium/builders/try/android-x64-rel/16538/overview

Original change's description:
> Tracking Protection 100%: Separate the page info code
>
> This is a refactoring without any UI changes.
> Further cleanup and renaming will be done in a follow up CL.
>
> Bug: 330745124
> Change-Id: I79269db157ad7c9466ec61854472cf2f6e9c5f98
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5425991
> Reviewed-by: Nicola Tommasi <tommasin@chromium.org>
> Commit-Queue: Andrey Zaytsev <andzaytsev@google.com>
> Cr-Commit-Position: refs/heads/main@{#1283902}

Bug: 330745124
Change-Id: I8229089539ddf6e70b7c210feabd50db63a34240
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5434499
Reviewed-by: Nicola Tommasi <tommasin@chromium.org>
Commit-Queue: Etienne Pierre-Doray <etiennep@chromium.org>
Owners-Override: Etienne Pierre-Doray <etiennep@chromium.org>
Owners-Override: Mikel Astiz <mastiz@google.com>
Commit-Queue: Mikel Astiz <mastiz@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Matthew Jones <mdjones@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1283910}