Remove features::kV8DecommitPooledPages following underlying flag removal from v8
The --decommit_pooled_pages flag from removed from v8 by
https://chromium-review.googlesource.com/c/v8/v8/+/7209068, so every
renderer execution now is accompanied by the following message to
stderr:

Error: unrecognized flag --decommit-pooled-pages Try --help for options

Bug: 326303884
Change-Id: I381d12b0cb05dd5e9ba669be6147d15cfe15e50e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7228470
Commit-Queue: Michael Lippautz <mlippautz@chromium.org>
Auto-Submit: Andrey Kosyakov <caseq@chromium.org>
Reviewed-by: Michael Lippautz <mlippautz@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1554532}