Revert "Store list of IMEs as constexpr std::string_view arrays"
This reverts commit 6a75eef6a9542d519bb967fefdc2be50f28cae7e.

Reason for revert:
compile error on multiple bots
`../../chrome/browser/ash/input_method/editor_switch.cc:61:5: error: no matching function for call to 'Extend'`
See for example: https://ci.chromium.org/ui/p/chromium/builders/ci/Linux%20ChromiumOS%20MSan%20Builder/80471/overview

Original change's description:
> Store list of IMEs as constexpr std::string_view arrays
>
> The list of IMEs per language is static data and does not need to be
> held in dynamically-allocated heap storage at runtime.
>
> Bug: 375364966
> Change-Id: Id560bb570b481842620defd6077e26771a0386ef
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6015247
> Reviewed-by: Curtis McMullan <curtismcmullan@chromium.org>
> Reviewed-by: Yuichiro Hanada <yhanada@chromium.org>
> Commit-Queue: Daniel Cheng <dcheng@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1382221}

Bug: 375364966
Change-Id: Iafd625d32ea551ca7c7ea52c206e62d02b9a4464
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6010842
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Bret Sepulveda <bsep@chromium.org>
Owners-Override: Bret Sepulveda <bsep@chromium.org>
Commit-Queue: Bret Sepulveda <bsep@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1382223}