[Install-build-deps] Use check_output instead of check_call
If some packages install failed (caused by some package do not exists
or network issue, etc.), there no output attribute in the check_call
raised error, we will get error message show like this:
AttributeError: 'NoneType' object has no attribute 'decode'.
This change using check_output instead of check_call to fix this.

Bug: 356905949
Change-Id: I152a3297e517f9c2416add0064e9a9bdbb8ea0c6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5756626
Reviewed-by: Thomas Anderson <thomasanderson@chromium.org>
Reviewed-by: Lei Zhang <thestig@chromium.org>
Commit-Queue: Lei Zhang <thestig@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1338273}