[tools] Make mass-rename.py Python3 compatible.
Fixes several issues due to the non-interchangeability of strings
and bytes in Python3.

The errors were raised as exceptions like this:
  TypeError: a bytes-like object is required, not 'str'

Change-Id: I495c120303da9045e963bce02d9aa8247a2d095d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3195094
Commit-Queue: Kevin Marshall <kmarshall@chromium.org>
Auto-Submit: Kevin Marshall <kmarshall@chromium.org>
Reviewed-by: Dirk Pranke <dpranke@google.com>
Cr-Commit-Position: refs/heads/main@{#926532}