[Passwords] Avoid ambiguous reference to the LoginsReply
LoginsReply declared twice in the header files which causes an issues
with ambiguous usage.
Clang doesn't claims about it, but GCC does.
The errors example for GCC 9.3.0:
/components/password_manager/core/browser/password_store_impl.h:110:7:
error: reference to 'LoginsReply' is ambiguous
/components/password_manager/core/browser/password_store_backend.h:27:9:
note: candidates are: 'using LoginsReply = class
/components/password_manager/core/browser/password_store.h:321:9:
note: candidates are: 'using LoginsReply = class

Bug: 1217071, 1217070, 819294
Change-Id: I5ed4127d35c7d36f24dfa35e84310ba5128c4013
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2980536
Reviewed-by: Vasilii Sukhanov <vasilii@chromium.org>
Commit-Queue: Ivan Murashov <ivan.murashov@lge.com>
Cr-Commit-Position: refs/heads/master@{#895117}