Reland "Remove unused source code in PPAPI"
This reverts commit d32590d50c3c3b0f4a2146f04051a5ca2525c9f3.

Reason for revert: The original revert issue has been addressed
by https://crrev.com/1481330

Bug: 40511450
Original change's description:
> Revert "Remove unused source code in PPAPI"
>
> This reverts commit b54fb3d12a612c8cba47c8928f52ae873da1071f.
>
> Reason for revert: gles2/gles2.c is missing
>
> FileNotFoundError: [Errno 2] No such file or directory: '/b/s/w/ir/cache/builder/linux_presubmit/src/ppapi/lib/gl/gles2/gles2.c'
>
> Bug: 40511450, chromium:428926701
> Original change's description:
> > Remove unused source code in PPAPI
> >
> > Bug: 40511450
> > Change-Id: Id469003594da402cb4cdb3e83f257830dc9e353c
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6696273
> > Reviewed-by: Derek Schuff <dschuff@chromium.org>
> > Commit-Queue: Eugene Zemtsov <eugene@chromium.org>
> > Reviewed-by: Tom Sepez <tsepez@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#1481245}
>
> Bug: 40511450
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Change-Id: Icd2ccba65d7b0fee6f3cf6f5f4a7b1633c962ca6
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6697998
> Owners-Override: Solomon Kinard <solomonkinard@google.com>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Commit-Queue: Solomon Kinard <solomonkinard@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1481305}

Bug: 40511450, chromium:428926701
Bug: 40511450
Change-Id: Id34a9cde6b9874d912c04180209c1b1ea24b9af0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6698095
Commit-Queue: Eugene Zemtsov <eugene@chromium.org>
Reviewed-by: Fabian Sommer <fabiansommer@chromium.org>
Reviewed-by: Tom Sepez <tsepez@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Derek Schuff <dschuff@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1483225}