Roll Depot Tools from 008ecc31b215 to 671f3a1488db (1 revision)
https://chromium.googlesource.com/chromium/tools/depot_tools.git/+log/008ecc31b215..671f3a1488db

2025-09-04 ukai@google.com ninja: fix TypeError: check_out_dir() missing 1 required positional argument

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/depot-tools-chromium-autoroll
Please CC chops-source-team@google.com on the revert to ensure that a human
is aware of the problem.

To file a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/entry

To report a problem with the AutoRoller itself, please file a bug:
https://issues.skia.org/issues/new?component=1389291&template=1850622

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

Cq-Include-Trybots: luci.chromium.try:linux-utr-tester;luci.chromium.try:win-utr-tester
Bug: chromium:442612621
Tbr: 
Change-Id: I92172e33cbf12cc1ef5064b06b34967622e0f7db
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6914153
Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1510641}