Revert "[Nearby] Validate device name in onboarding."
This reverts commit 920451c0e30528ebcb1bfbed3a6580f3388afec7.

Reason for revert: suspect causing browertests failure on linux-chromeos-dbg
browser_tests failed because of:
- NearbyOnboardingPageTest.All

First failure: https://ci.chromium.org/p/chromium/builders/ci/linux-chromeos-dbg/20674

Sample log: https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8867535501208450768/+/steps/browser_tests/0/logs/Deterministic_failure:_NearbyOnboardingPageTest.All__status_FAILURE_/0
---
 ReferenceError: loadTimeData is not defined
     at Context.<anonymous> (file:///b/s/w/ir/chrome/test/data/webui/nearby_share/shared/nearby_onboarding_page_test.js:50:5)
---

Original change's description:
> [Nearby] Validate device name in onboarding.
>
> This adds support for validating the device name that a user enters
> during the Nearby Share onboarding flow. Validation happens as the user
> types and also when they try to proceed to the next screen. If an
> invalid name is detected, an error message will appear and the "Next"
> button will be disabled.
>
> Screenshots:
>   https://screenshot.googleplex.com/3USR7ftg7QCwJhR.png
>   https://screenshot.googleplex.com/6Cr6pedUxWnUKju.png
>
> Bug: b:169582004
> Change-Id: I07d4822e0ea099b30d23ed34a5f70f01940a3009
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2441150
> Reviewed-by: Kyle Horimoto <khorimoto@chromium.org>
> Reviewed-by: James Vecore <vecore@google.com>
> Commit-Queue: Michael Hansen <hansenmichael@google.com>
> Cr-Commit-Position: refs/heads/master@{#813193}

TBR=khorimoto@chromium.org,vecore@google.com,hansenmichael@google.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: b:169582004
Change-Id: I6a9dd1f9f40c6f54e6a467de3053b75f8f264645
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2448510
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#813624}