Provide base::Unretained template specialization for raw_ptr<T>.
Before this CL calling base::Unretained(raw_ptr_of_t) would fail
to compile:

    ../../base/memory/raw_ptr_unittest.cc:720:45: error: no matching
    function for call to 'Unretained'
        auto callback1 = base::BindOnce(PingPong, base::Unretained(p));
                                                  ^~~~~~~~~~~~~~~~
    ../../base/bind.h:138:39: note: candidate template ignored:
    could not match 'T *' against 'raw_ptr<int>'
    inline internal::UnretainedWrapper<T> Unretained(T* o) {
                                          ^

After this CL, it works (as shown in the new unit test).

Note that the automatic rewriter will still insert `.get()` when
raw_ptr_of_t is passed into any template function (including
base::Unretained, where it is no longer necessary after this CL).  We
will start skipping the rewrite of such functions in a follow-up CL at
https://crrev.com/c/3285929.

Also note that we don't have immediate plans to broadly add template
specializations in other places (e.g. to WrapUnique or WrapRefCounted).
base::Unretained is special, because it inherently deals with raw
pointers (and the extra template specialization helps treat raw_ptr_of_t
as a regular C++ raw pointer).

Bug: 1073933
Change-Id: I4703d7523d72c7595c44c6cf9c5e9a38655a3939
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3283196
Auto-Submit: Łukasz Anforowicz <lukasza@chromium.org>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Reviewed-by: danakj <danakj@chromium.org>
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Reviewed-by: Bartek Nowierski <bartekn@chromium.org>
Commit-Queue: Łukasz Anforowicz <lukasza@chromium.org>
Cr-Commit-Position: refs/heads/main@{#943564}