Revert "Introduce AccountId::Literal for testing convenience"
This reverts commit 114351c44471a7f6ea07ff031cc82befa524063f.

Reason for revert: broke win builder dbg: https://ci.chromium.org/ui/p/chromium/builders/ci/Win%20Builder%20(dbg)/203954/overview

```
[818/20847] LIB obj/components/account_id/test_support.lib
..\..\third_party\llvm-build\Release+Asserts\bin\lld-link.exe /lib /OUT:obj/components/account_id/test_support.lib /nologo /WX /ignore:4221 /llvmlibthin @obj/components/account_id/test_support.lib.rsp
warning: no input files, not writing output file
         pass /llvmlibempty to write empty .lib file,
         pass /ignore:emptyoutput to suppress warning
treating warning as error due to /WX
lld-link: error: lib failed
exit=1
error: 1 steps failed: exit=1
```

Original change's description:
> Introduce AccountId::Literal for testing convenience
>
> One of the common mistakes in tests is to define global
> `const AccountId` variable. It conflicts with style guideline,
> and could introduce unexpected behaviors.
>
> This CL introduces AccountId::Literal, which can be used in
> constexpr context, and can be converted into AccountId implicitly
> for easier test writing.
>
> BUG=None
> TEST=Tryjob
>
> Change-Id: I368438deb1a69fd33a293cf91bf6e2643e2a634b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6636616
> Reviewed-by: Xiyuan Xia <xiyuan@chromium.org>
> Commit-Queue: Hidehiko Abe <hidehiko@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1473081}

Bug: None
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I8bdc82ce2ca96cfc8fd32e81272e44c7f8e87e15
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6641243
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Elly FJ <ellyjones@chromium.org>
Owners-Override: Elly FJ <ellyjones@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1473102}