Reland "[Reading mode] Log the empty state with a short delay"
This is a reland of commit d796cd636063ae9d3f56116c1bab166684d636db

Updated to fix the error "Uncaught TypeError:
chrome.readingMode.logEmptyState is not a function"

Original change's description:
> [Reading mode] Log the empty state with a short delay
>
> If the empty state is still showing after a delay, then log it.
> Otherwise, the empty state was only shown very briefly, so don't log it.
>
> Change-Id: I322694af1ed86ad3b477f6d17edae2905e92769e
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6951837
> Commit-Queue: Kristi Saney <kristislee@google.com>
> Reviewed-by: Lauren Winston <lwinston@google.com>
> Cr-Commit-Position: refs/heads/main@{#1515795}

Change-Id: I61ad3f3188951b5def35486da733b410edfd85fa
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6956653
Auto-Submit: Kristi Saney <kristislee@google.com>
Commit-Queue: Lauren Winston <lwinston@google.com>
Reviewed-by: Lauren Winston <lwinston@google.com>
Commit-Queue: Kristi Saney <kristislee@google.com>
Cr-Commit-Position: refs/heads/main@{#1516342}