Revert "build: Use -nostdlib++ unconditionally in runtime_library config"
This reverts commit 49570fdaf3e2d1821fbe4b56084c07755ba5f194.

Reason for revert: Builder failure: https://ci.chromium.org/ui/p/chromium/builders/ci/linux-gcc-rel/596773/overview

[1/1] LINK ./empty_main
python3 ../../build/toolchain/gcc_link_wrapper.py --output=./empty_main -- g++ -Werror -fPIC -m64 -Wl,--gc-sections -Wl,-z,defs -Wl,--as-needed -nostdlib++ --sysroot=../../build/linux/debian_bullseye_amd64-sysroot -Wl,--fatal-warnings -Wl,--build-id -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -rdynamic -pie -Wl,--disable-new-dtags -o ./empty_main -Wl,--start-group @./empty_main.rsp -Wl,--end-group -ldl -lpthread -lrt -Wl,--start-group -Wl,--end-group
g++: error: unrecognized command-line option '-nostdlib++'; did you mean '-nostdlib'?
exit=1
error: 1 steps failed: exit=1

Original change's description:
> build: Use -nostdlib++ unconditionally in runtime_library config
>
> GCC supports -nostdlib++ since version 13, which is available in Ubuntu
> 24.04, Debian 13 and Fedora 38.
>
> Change-Id: If2e7fc98c9baef644fd182d24e2b0a8824a3e2b9
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7865415
> Reviewed-by: Philipp Wollermann <philwo@google.com>
> Commit-Queue: Henrique Ferreiro <hferreiro@igalia.com>
> Reviewed-by: Junji Watanabe <jwata@google.com>
> Cr-Commit-Position: refs/heads/main@{#1636066}

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I4d865a93e36a31089a99806f8003df35d26a67eb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7866075
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Mikołaj Wałachowski <mwalachowski@google.com>
Owners-Override: Mikołaj Wałachowski <mwalachowski@google.com>
Cr-Commit-Position: refs/heads/main@{#1636080}