Attempt to deflake PromoCarImpressionTest#testImpression_PrimaryButton_Seen
Previously the test was destroying the coordinator on the
Instrumentation thread, and the coordinator is setting the listener
to null here:
https://source.chromium.org/chromium/chromium/src/+/master:components/browser_ui/widget/android/java/src/org/chromium/components/browser_ui/widget/impression/ImpressionTracker.java;drc=763c071aa91f87c5e404edff98bc5bac8075d4a1;l=56

Since that is happening in a separate thread, it is racey and thus
potentially triggering the NPEs like this:
java.lang.NullPointerException: Attempt to invoke interface method 'void org.chromium.components.browser_ui.widget.impression.ImpressionTracker$Listener.onImpression()' on a null object reference
	at org.chromium.components.browser_ui.widget.impression.ImpressionTracker.onPreDraw(ImpressionTracker.java:138)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)

If this does not resolve the issue, then it would imply some raciness in
part of the Android APIs, and we likely should null check the listener
inside of the ImpressionTracker.

BUG=1179212

Change-Id: Ibfdc7e5a9ee617167c984d60c95626bf2ada3a61
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2705605
Reviewed-by: Michael Thiessen <mthiesse@chromium.org>
Commit-Queue: Ted Choc <tedchoc@chromium.org>
Cr-Commit-Position: refs/heads/master@{#855524}