Revert "ChromeOS: Do not report previously discarded tabs to resourced"
This reverts commit d3ed019ea2664906e5b0e9933b257729d0058c09.

Reason for revert: Gardening: a culprit of the build failure:

https://ci.chromium.org/ui/p/chromium/builders/ci/linux-lacros-dbg/32329/overview

```
[27/153] CXX obj/chrome/test/unit_tests/report_page_processes_policy_unittest.o
FAILED: obj/chrome/test/unit_tests/report_page_processes_policy_unittest.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../chrome/browser/performance_manager/policies/report_page_processes_policy_unittest.cc:349:30: error: no member named 'GetPageProcesses' in 'performance_manager::policies::MockReportPageProcessesPolicy'
349 |   auto processes = policy()->GetPageProcesses();
|                    ~~~~~~~~  ^
1 error generated.
```

Original change's description:
> ChromeOS: Do not report previously discarded tabs to resourced
>
> resourced uses the list of tab processes to calculate how much memory
> can be freed by killing tabs of a certain priority. When a tab has been
> discarded, it should not be included in this list even if its processes
> are still alive.
>
> Skip reporting discarded and marked tab processes to resourced.
>
> Bug: b/326860364
> Change-Id: Ie384f4c3efe78af7301c9757c13ae749ea747862
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5363999
> Reviewed-by: Francois Pierre Doray <fdoray@chromium.org>
> Reviewed-by: Vovo Yang <vovoy@chromium.org>
> Commit-Queue: Kameron Lutes <kalutes@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1273963}

Bug: b/326860364
Change-Id: I9f6a772dbe11fe63a64e4e3e16f00fcb636e97a0
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5366915
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Hayato Ito <hayato@chromium.org>
Owners-Override: Hayato Ito <hayato@chromium.org>
Auto-Submit: Hayato Ito <hayato@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1273967}