Revert "[aw] Allow to set Network in AwPacProcessor."
This reverts commit bd3b0ee6d5161b1c777a7d9326fb47963b1d498d.

Reason for revert: Likely the cause of of the compile crash on
https://ci.chromium.org/p/chrome/builders/ci/arm64-unpublished-builder-rel/14332

Error:
../../clank/android_webview/next/java/src/com/android/webview/chromium/PacProcessorForS.java:34: error: constructor AwPacProcessor in class AwPacProcessor cannot be applied to given types;
        mProcessor = new AwPacProcessor(network);
                     ^
  required: no arguments
  found: Network
  reason: actual and formal argument lists differ in length
1 error

Original change's description:
> [aw] Allow to set Network in AwPacProcessor.
>
> Bug: 1085115
> Change-Id: I8846261a0f21ecb48692b70ab778f68996843760
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2414173
> Reviewed-by: Richard Coles <torne@chromium.org>
> Commit-Queue: Anna Malova <amalova@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#812494}

TBR=torne@chromium.org,amalova@chromium.org

Change-Id: I087cdfa4fd0f4ca71c50a38b3a01fec1f67fa7aa
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1085115
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2440600
Reviewed-by: Alice Wang <aliceywang@chromium.org>
Commit-Queue: Alice Wang <aliceywang@chromium.org>
Cr-Commit-Position: refs/heads/master@{#812582}