Bugfix: test failures from upstreaming OsAdditionalSecurityProvider
Change to [upstream
OsAdditionalSecurityProvider](https://chrome-internal-review.googlesource.com/c/clank/internal/apps/+/8950264)
caused [test
failures](https://ci.chromium.org/ui/p/chrome/builders/ci/android-desktop-16-x64-rel-emu-tests/3298/overview)
in Android tests due to missing Android manifest permission:

```
java.lang.SecurityException: Access denied, requires: android.permission.QUERY_ADVANCED_PROTECTION_MODE
```

Adding permission check to ensure OsAdditionalSecurityProvider has
correct permissions before observing advanced protection status.

Change-Id: Ib82eeb51c0c937380869a06b4466af411a38fb46
Bug: 477677919
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7569207
Owners-Override: Patrick Noland <pnoland@chromium.org>
Reviewed-by: Sky Malice <skym@chromium.org>
Reviewed-by: Patrick Noland <pnoland@chromium.org>
Commit-Queue: Liz Prucka <lizprucka@google.com>
Reviewed-by: James Cook <jamescook@chromium.org>
Commit-Queue: Patrick Noland <pnoland@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1583560}