Fix test flakiness due to null context
This fixes a regression introduced in https://crrev.com/c/4813316 where
some code under test would race against the base context behind
`CronetTestFramework.sContextWrapper` being reset to null, leading to
test crashes such as:

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.Context.unregisterReceiver(android.content.BroadcastReceiver)' on a null object reference
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:769)
 	at org.chromium.net.ProxyChangeListener.unregisterBroadcastReceiver(ProxyChangeListener.java:318)
	at org.chromium.net.ProxyChangeListener.stop(ProxyChangeListener.java:151)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)

Change-Id: I38b6887971452c8f48c43591f861cf74f52fd1eb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4834227
Auto-Submit: Etienne Dechamps <edechamps@google.com>
Commit-Queue: Stefano Duo <stefanoduo@google.com>
Reviewed-by: Stefano Duo <stefanoduo@google.com>
Cr-Commit-Position: refs/heads/main@{#1192063}