fix link error of optimization_guide_gpu_unittests
```
ukai@ukai ...src/chrome/src % cat out/Default/args.gn
is_chrome_branded=true
is_debug=true

ukai@ukai ...src/chrome/src % ninja -C out/Default optimization_guide_gpu_unitte
sts
ninja: Entering directory `out/Default'
[0/1] Regenerating ninja files
[11247/11247] LINK ./optimization_guide_gpu_unittests
FAILED: optimization_guide_gpu_unittests
...
ld.lld: error: undefined symbol: charntorune
>>> referenced by ngram_hash_ops_utils.cc:42 (../../components/translate/core/language_detection/ngram_hash_ops_utils.cc:42)
>>>               language_detection/ngram_hash_ops_utils.o:(translate::Tokenize(char const*, unsigned long, unsigned long, bool)) in archive obj/components/translate/core/language_detection/liblanguage_detection.a
>>> referenced by ngram_hash_ops_utils.cc:77 (../../components/translate/core/language_detection/ngram_hash_ops_utils.cc:77)
>>>               language_detection/ngram_hash_ops_utils.o:(translate::LowercaseUnicodeStr(char const*, int, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>>*)) in archive obj/components/translate/core/language_detection/liblanguage_detection.a

ld.lld: error: undefined symbol: runetochar
>>> referenced by ngram_hash_ops_utils.cc:81 (../../components/translate/core/language_detection/ngram_hash_ops_utils.cc:81)
>>>               language_detection/ngram_hash_ops_utils.o:(translate::LowercaseUnicodeStr(char const*, int, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>>*)) in archive obj/components/translate/core/language_detection/liblanguage_detection.a
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

charntorune is defined in
third_party/libphonenumber:libphonnumber_without_metadata.

third_party/utf/src/utf/chartorune.c also defines charntorne,
but it is not included in third_party/utf.
If we add src/utf/chartorune.c in third_party/utf:utf, we'll
get duplicate symbol with libphonnumber_without_metadata.a.

charntorune is used in
components/translate/core/language_detection/ngram_hash_ops_utils.cc,
so it should depend on third_party/libphonenumber:libphonenumber_without_metadata

Bug: 342486149
Change-Id: I377de8492dbad135968752845f1ad9f83cf03d1c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5567569
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Sophie Chang <sophiechang@chromium.org>
Reviewed-by: Takashi Toyoshima <toyoshim@chromium.org>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Cr-Commit-Position: refs/heads/main@{#1305516}