[fuchsia] fix random.samples breakage caused by python 3.11 uprev
I am not an expert of python, but the issue started from
https://ci.chromium.org/ui/p/chrome/builders/ci/fuchsia-ava-sherlock/3142/blamelist,
and it seems like the python 3.11 uprev from 3.8 is the cause.

The error looks like

```
File "/home/swarming/bot/w/ir/out/d0bf-fuchsia-ava-she/../../fuchsia_web/av_testing/av_sync_tests.py", line 213, in run_test
    for file in random.sample(candidates, 2):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/swarming/bot/w/ir/.task_template_vpython_cache/vpython/store/cpython+l5fnajrvijf7cvdkjqmbicg3i8/contents/lib/python3.11/random.py", line 439, in sample
    raise TypeError("Population must be a sequence.  "
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
```

Cq-Include-Trybots: luci.chrome.try:fuchsia-ava-sherlock
Change-Id: If9466a64ff2951334d88d48f6522fa2cf8db19a9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6284595
Commit-Queue: David Song <wintermelons@google.com>
Reviewed-by: David Song <wintermelons@google.com>
Auto-Submit: Zijie He <zijiehe@google.com>
Commit-Queue: Zijie He <zijiehe@google.com>
Cr-Commit-Position: refs/heads/main@{#1422743}