android: Use vpython3 for generate_profile.py
This should resolve the module error on the bot:

```
ModuleNotFoundError: No module named 'six'
```

Also turn off logcat streaming in case that was causing the module
error.

Add .pydeps to ensure deps are included (they should already be
transitive deps of the existing data_deps but it's better to be explicit
and know when generate_profile.py's deps are changed).

Bug: 40272686
Change-Id: If35965e2b2657ab9bfbcfa2513eaefe2d033d9b0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5917969
Auto-Submit: Peter Wen <wnwen@chromium.org>
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1366368}