[Android] HistogramWatcher: correct checking, informative asserts
This CL changes how HistogramWatcher interacts with RecordHistogram's
get*ForTesting methods. It previously checked the count of records in
a bucket, and also the total count to check that no more or no less
was recorded than expected.

This CL changes HistogramWatcher to use a new getHistogramSamplesForTesting() call, which returns all buckets for
a histogram as (min, max, count) triples.

This fixes a bug in the following case:

        var watcher = HistogramWatcher.newBuilder()
               .expectIntRecord("Histogram1", 6000)
               .expectIntRecord("Histogram1", 7000)
               .expectIntRecord("Histogram1", 8000);
        RecordHistogram.recordTimesHistogram("Histogram1", 6000);
        RecordHistogram.recordTimesHistogram("Histogram1", 7000);
        RecordHistogram.recordTimesHistogram("Histogram1", 8000);
fails-> watcher.assertExpected();

The bug happens because 6000 and 7000 fall into the same bucket, so
the delta seen is 2 for both of them. It happens using HistogramDelta,
HistogramTestRule and RecordHistogram too.

Moreover, getHistogramSamplesForTesting() allows outputting more
informative assert messages that show what was actually logged, for
example:

java.lang.AssertionError: Records for histogram "Android.BackgroundRestrictions.StandbyBucket" did not match expected.
1 record(s) expected: [3]
2 record(s) seen: [3, 4]

Also added tests for HistogramWatcher, since the logic is now quite
complex. The tests run in three scenarios:
- Without native (using CachingUmaRecorder)
- With native (using NativeUmaRecorder + native)
- Transitioning into native

The first two scenarios are batched, hence them being broken down by
class.

Bug: 1412884,1412573
Change-Id: I601de8b89452c00510b637e1a93c5744c2431aa1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4234900
Code-Coverage: Findit <findit-for-me@appspot.gserviceaccount.com>
Commit-Queue: Henrique Nakashima <hnakashima@chromium.org>
Reviewed-by: Nate Fischer <ntfschr@chromium.org>
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1107031}