[ios] Fixed build errors for ios-blink
CL https://crrev.com/c/4296407 added a new flag to show RPDQ debug
borders on Mac but it's causing build failure in experimental
ios-blink port.

../../ui/accelerated_widget_mac/ca_renderer_layer_tree.mm:51:14: error:
unused variable 'kShowMacRenderPassDrawQuadBorders'
[-Werror,-Wunused-const-variable]

Bug: 1411704
Change-Id: Ibb26f3669fc3bb067bd75b67e9be8c2f3f4e0ac6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4686436
Reviewed-by: Ian Vollick <vollick@chromium.org>
Commit-Queue: Abhijeet Kandalkar <abhijeet@igalia.com>
Reviewed-by: ccameron chromium <ccameron@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1171191}