Revert "[ClapperQuiet] Adds Clapper Quiet Icon"
This reverts commit 3eb3ba3140f1f5b6cc5c2567d3942e630f469521.

Reason for revert are server CI failures:
https://ci.chromium.org/ui/p/chromium/builders/ci/android-12l-landscape-x64-dbg-tests/24473
https://ci.chromium.org/ui/p/chromium/builders/ci/android-15-tablet-landscape-x64-rel
https://ci.chromium.org/ui/p/chromium/builders/ci/android-desktop-x64-rel-15-tests
which fail the tests 
chrome_public_test_apk failed because of:
* PermissionClapperQuietTest#testQuietClapperPreemptionWhilePageInfoOpenDismiss
* PermissionClapperQuietTest#testQuietClapperPreemptionWhilePageInfoOpenReset
* PermissionClapperQuietTest#testQuietClapperPreemptionWhilePageInfoOpenSubscribe

with logs like

```
Caused by: java.lang.AssertionError: expected:<org.chromium.chrome.browser.modaldialog.ChromeTabModalPresenter@f0582f5> but was:<org.chromium.components.browser_ui.modaldialog.AppModalPresenter@1bd988a>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.chromium.components.browser_ui.modaldialog.ModalDialogTestUtils.lambda$checkCurrentPresenter$4(ModalDialogTestUtils.java:228)
	at org.chromium.components.browser_ui.modaldialog.ModalDialogTestUtils$3.run(D8$$SyntheticClass:0)
```

Original change's description:
> [ClapperQuiet] Adds Clapper Quiet Icon
>
> Adds the ui logic to show the clapper quiet icon on demand.
>
> Bug: 463333225
> Change-Id: Id0405384f654f63225b71d0914a796c0e8aa73df
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7362147
> Commit-Queue: Judith Hemp <hempjudith@google.com>
> Reviewed-by: Antonio Sartori <antoniosartori@chromium.org>
> Reviewed-by: Patrick Noland <pnoland@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1568293}

Bug: 463333225
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I7453558908b73042ded5269fde5b4ba6c147b245
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7460948
Owners-Override: Friedrich Hauser <friedrichh@chromium.org>
Commit-Queue: Friedrich Hauser <friedrichh@chromium.org>
Reviewed-by: Kartar Singh <kartarsingh@google.com>
Auto-Submit: Friedrich Hauser <friedrichh@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1568331}