Revert "WebUI: Fix some undeclared gn inputs in ts_library() targets"
This reverts commit ab34f63393b707ed8791634ca35be73ead38393c.

Reason for revert: breaks ChromeOS-Chrome builds
e.g.

   assert validateMapping(mapping_path, mapping[0], args.root_gen_dir,
AssertionError: mnt/nvme1/chrome/src/out_brya/common/tsc/* is not in root_gen_dir. |path_mappings| should only map to generated directories, so that a corresponding target can be added in in |deps|.
[26985/87881] ACTION //chrome/browser/resources/chromeos/accessibility/chromevox:ts_build(//build/toolchain/cros:target)

Original change's description:
> WebUI: Fix some undeclared gn inputs in ts_library() targets
>
> When ts_library() path_mappings are used to map URL prefixes to
> directories in src/, any files that are imported are dependencies of
> the ts_library() target but are not added to |inputs| for gn and are
> not directly generated by any dependency of the target. This leads to
> compile failures in remote execution environments.
>
> This CL
> (1) Adds validation for any path_mapping, that the mapping corresponds
>     to a generated directory and not a src directory.
> (2) Adds exceptions for a few auto-mapped cases that are safe since
>     they are only added when a dependency on a target that depends on
>     all .d.ts files within the folder is added.
> (3) Also adds exceptions for some possibly unsafe infra-related and
>     CrOS specific cases, which should be investigated later.
> (4) Fixes the cases causing the specific failures in the bug, by adding
>     targets preprocessing definitions files to a generated directory
>     and then adding dependencies on these targets in all locations
>     using the path_mapping.
>
> Bug: 326005022
> Change-Id: I9e9c75044bd75ad5e9521a2834eb8b67400f6a0e
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5315956
> Reviewed-by: Demetrios Papadopoulos <dpapad@chromium.org>
> Commit-Queue: Rebekah Potter <rbpotter@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1264316}

Bug: 326005022
Change-Id: Icc6e9856672f64fb507735d603d42366badfdf24
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5320430
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: John Palmer <jopalmer@chromium.org>
Reviewed-by: Rebekah Potter <rbpotter@chromium.org>
Commit-Queue: Rebekah Potter <rbpotter@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1264607}