Fix shell_integration_mac_unittest for official builds.
This fixes the build after commit 09f3c058aae735ca485c0dfcdd6c53a16b9349cc.

Reason for breakage: `chrome::SetChannelForTesting` does not exist at tip of tree, breaks mac build.

../../chrome/browser/shell_integration_mac_unittest.mm:26:15: error: no type named 'SetChannelForTesting' in namespace 'chrome'

Bug: b:446672134
Change-Id: I3a998bb1e0a93fa2632016cb740e0c716b630b23
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7108949
Commit-Queue: Avi Drissman <avi@chromium.org>
Auto-Submit: Justin DeWitt <dewittj@chromium.org>
Reviewed-by: Avi Drissman <avi@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1539058}