Revert "Roll WPT Tooling."
This reverts commit bb3fab20f93691c54d347a2b9564d827d8a4d767.

Reason for revert: The CL broke at least linux-blink-rel:
https://ci.chromium.org/p/chromium/builders/try/linux-blink-rel

  File "/b/s/w/ir/third_party/blink/web_tests/external/wpt/webdriver/tests/support/fixtures.py", line 126
    async def reset_current_session_if_necessary(caps, request_bidi):
            ^
SyntaxError: invalid syntax

Original change's description:
> Roll WPT Tooling.
>
> This is a significant change because we pull in the breaking py3-only
> changes from upstream.
>
> In addition to the changes made by //third_party/wpt_tools/checkout.sh,
> this CL also includes several fixups to pass CQ (eg: some more py3
> updates, and manually adding a webdriver bidi PR).
>
> Cq-Include-Trybots: luci.chromium.try:linux-wpt-identity-fyi-rel,linux-wpt-input-fyi-rel
> Change-Id: I6380ec6bb46fa6fe8e0db66ebe1f82122b5c3c87
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2764543
> Reviewed-by: Stephen McGruer <smcgruer@chromium.org>
> Reviewed-by: Rakib Hasan <rmhasan@google.com>
> Commit-Queue: Luke Z <lpz@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#863882}

Change-Id: Ifab3e6b6c13b0617de72ac96f4ab4bfb2bdb5aeb
Cq-Include-Trybots: luci.chromium.try:linux-wpt-identity-fyi-rel,linux-wpt-input-fyi-rel
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2771303
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Xianzhu Wang <wangxianzhu@chromium.org>
Cr-Commit-Position: refs/heads/master@{#864061}