[Managed prefs] Add managed disclaimer to ChromeSwitchPreference
This CL generalizes changes in `ChromeBasePreference` and apply them to
`ChromeSwitchPreference`. Also adds a test for CSP, which is very
similar to CBP, but I decided to keep them separate in case we want
to add more functionality later, such as checking the toggle state
of the switch view.

It also fixes multiple issues with icon visibility, which are now
extensively covered by tests.

New screenshots: https://drive.google.com/drive/folders/17nmSP0gkwnaqWZD519dYJoCvukNFqjCa?usp=share_link

Note: Change to `AdaptiveToolbarPreferenceFragmentTest` required because
`testSelectShortcuts` failed while inflating `ChromeSwitchPreference`
with error:

```
java.lang.IllegalArgumentException: No test value configured for
HighlightManagedPrefDisclaimerAndroid and native is not available to
provide a default value. Use @EnableFeatures or @DisableFeatures to
provide test values for the flag.
```

Bug: 1356748
Fixed: b:253062948
Change-Id: I92e23ba269e15d29b31a892b7bb8b859f7b8d1a0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3978871
Reviewed-by: Boris Sazonov <bsazonov@chromium.org>
Commit-Queue: Fabio Tirelo <ftirelo@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1066695}