IWYU: std::sort requires include algorithm in AutoFillOfferData.
Fixes this compilation error:
../../components/autofill/core/browser/data_model/autofill_offer_data.cc:56:8: error: ‘sort’ is not a member of ‘std’; did you mean ‘sqrt’?

Bug: 957519
Change-Id: Iaef429cfca5e55af8b819457f9b9729ab4f669f5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2423586
Commit-Queue: Parastoo Geranmayeh <parastoog@google.com>
Reviewed-by: Parastoo Geranmayeh <parastoog@google.com>
Cr-Commit-Position: refs/heads/master@{#809447}