Revert "WebUI Mojo Bindings: Remove use_typescript_sources"
This reverts commit 2599dd89d8c7c4afc478906b02105abbfca40c5f.

Reason for revert: breaks compile for chromeos dbg
https://ci.chromium.org/ui/p/chromium/builders/try/linux-chromeos-compile-dbg/1632716

FileNotFoundError: [Errno 2] No such file or directory: 'gen/mojom-webui/chrome/test/data/webui/chromeos/web_ui_test.mojom-webui.js'

Original change's description:
> WebUI Mojo Bindings: Remove use_typescript_sources
>
> The use_typescript_sources parameter was confusing to reviewers (not
> clear what "sources" it refers to, or that it is WebUI-specific), and
> is now default true/on which is the reverse of convention and confuses
> developers about when the parameter needs to be specified.
>
> Renaming it to generate_webui_js_bindings, changing to default "off",
> and limiting the parameter to ChromeOS Ash since WebUI bindings always
> use TypeScript on other platforms.
>
> In this CL removing use_typescript_sources and updating a few
> remaining users.
>
> Bug: 1002798
> Change-Id: Ic6ee29be22b65bb2d4b1f5fda013766b3c06bd5e
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5115946
> Reviewed-by: Reilly Grant <reillyg@chromium.org>
> Reviewed-by: Robert Sesek <rsesek@chromium.org>
> Commit-Queue: Rebekah Potter <rbpotter@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1237670}

Bug: 1002798
Change-Id: I84c93e8c09ac384f18440e3eb791cf8b5b5d4b22
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5124793
Auto-Submit: Joel Hockey <joelhockey@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Shibalik Mohapatra <shibalik@chromium.org>
Owners-Override: Shibalik Mohapatra <shibalik@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1237850}