Revert "Simple frame production"
This reverts commit 23a50951556c98fab168260ac37c32006fe546d1.

Reason for revert: compilation failure in https://ci.chromium.org/ui/p/chromium/builders/ci/mac-arm64-on-arm64-rel/60768/overview :

../../cc/slim/slim_layer_tree_compositor_frame_unittest.cc:70:51: error: too few arguments to function call, expected 4, have 2
frame_sink_->OnBeginFrame(begin_frame_args, {});
~~~~~~~~~~~~~~~~~~~~~~~~~                     ^
../../cc/slim/frame_sink_impl.h:78:8: note: 'OnBeginFrame' declared here
void OnBeginFrame(const viz::BeginFrameArgs& begin_frame_args,
^

Original change's description:
> Simple frame production
>
> A simple frame production algorithm. Supports:
> * a single root render pass only
> * Layer position, transform
> * SetMaskToBounds for axis-aligned layer
>
> Add AppendQuads for SolidColorLayer as the simplest layer for unit
> testing.
>
> Notable missing features:
> * Non-axis aligned clip and filters (requires non-root pass)
> * Damage tracking
> * Quad occlusion culling
> * Visible rect on quads
>
> Add test harness to unit test frame generation.
>
> Bug: 1408128
> Change-Id: I5508292876ddc66b59b118742dbceacb2c6a7d8e
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4245000
> Reviewed-by: Kyle Charbonneau <kylechar@chromium.org>
> Commit-Queue: Bo Liu <boliu@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1106868}

Bug: 1408128
Change-Id: I0f9cdab7ce4c8afc4412e85abcc20d6b032fcd55
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4261220
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: David Baron <dbaron@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: David Baron <dbaron@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1106874}