GCC: Made default move constructor of SequenceManager::PrioritySettings noexcept
Default move constructor of SequenceManager::Settings declared noexcept.
It requires default move constructor of SequenceManager::PrioritySettings,
which is a member of SequenceManager::Settings, to be declared noexcept
too.

Otherwise GCC build fails with error:
base/task/sequence_manager/sequence_manager.cc:107:1: error: function
'base::sequence_manager::SequenceManager::Settings::Settings(base::sequence_manager::SequenceManager::Settings&&)'
defaulted on its redeclaration with an exception-specification
that differs from the implicit exception-specification ''

Bug: 819294
Change-Id: I4801e827779cfcb151e1914d50511c4ebda5b17d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4854748
Commit-Queue: Ivan Murashov <ivan.murashov@lge.com>
Reviewed-by: Scott Haseley <shaseley@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1195016}