Revert "Create a ResetShortcutsComponent in CCT."
This reverts commit 1e6b827ea8d460e1707fcde3f83fe33c006d11a9.

Reason for revert: Tests are failing on https://ci.chromium.org/p/chromium/builders/ci/Win7%20Tests%20%281%29

For example:

[ RUN      ] ResetShortcutsComponentTest.ResetShortcutChromeTargetPreserveArguments
[3748:3728:1117/162648.254:1947251:ERROR:reset_shortcuts_component.cc(62)] Number of shortcuts to reset: 1
../../chrome/chrome_cleaner/components/reset_shortcuts_component_unittest.cc(144): error: Expected equality of these values:
  found_shortcuts[0].target_path
    Which is: L"E:\\b\\swarm_slave\\w\\itk5vfdk\\5116_696520538\\0\\scoped_dir3748_371919881\\d8473183-ca73-484f-bbdf-d7df1deebbed.tmp"
  fake_chrome_path_.value()
    Which is: L"e:\\b\\swarm_slave\\w\\itk5vfdk\\5116_696520538\\0\\scoped_dir3748_371919881\\d8473183-ca73-484f-bbdf-d7df1deebbed.tmp"
Stack trace:
Backtrace:
	chrome_cleaner::ResetShortcutsComponentTest_ResetShortcutChromeTargetPreserveArguments_Test::TestBody [0x0017FAAD+1389]

[  FAILED  ] ResetShortcutsComponentTest.ResetShortcutChromeTargetPreserveArguments (172 ms)


Original change's description:
> Create a ResetShortcutsComponent in CCT.
>
> The ResetShortcutsComponent will use the
> existing sandboxed shortcut parser to retrieve
> modified shortcuts and then overwrites the
> existing shortcuts with new ones. The
> component will be hooked up to the CCT in a
> future CL.
>
> Bug: 1116017,1148930
> Change-Id: Ia6c8453af267b98884804eed3b18944afb0506ba
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2520419
> Reviewed-by: Albert J. Wong <ajwong@chromium.org>
> Reviewed-by: Will Harris <wfh@chromium.org>
> Reviewed-by: Varun Khaneja <vakh@chromium.org>
> Commit-Queue: Bettina Dea <bdea@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#828453}

TBR=ajwong@chromium.org,veranika@chromium.org,vakh@chromium.org,wfh@chromium.org,bdea@chromium.org

Change-Id: I87e55d98da30d41141ca5c09585c02e78aa64022
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1116017
Bug: 1148930
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2545895
Reviewed-by: Marijn Kruisselbrink <mek@chromium.org>
Commit-Queue: Marijn Kruisselbrink <mek@chromium.org>
Cr-Commit-Position: refs/heads/master@{#828513}