Get the win_upload_clang bot to start trying to build Rust.
The python scripts deal with the various OS differences instead of
assuming Linux, and avoid trying to download GCC.

It gets as far as x.py compiling and trying to link, but failing to
find a linker.

Some docs for building on windows here:
https://github.com/rust-lang/rust#building-on-windows

Build output:
```
  Building rustbuild

    Compiling winapi v0.3.9
     Compiling proc-macro2 v1.0.46
     Compiling cfg-if v1.0.0
     Compiling memchr v2.5.0
     Compiling typenum v1.15.0
     Compiling version_check v0.9.4
     Compiling unicode-ident v1.0.0
     Compiling syn v1.0.102
     Compiling serde_derive v1.0.137
     Compiling cc v1.0.73
     Compiling serde v1.0.137
     Compiling pkg-config v0.3.25
     Compiling libc v0.2.126
     Compiling windows_x86_64_msvc v0.42.0
     Compiling log v0.4.17
     Compiling regex-syntax v0.6.26
     Compiling crossbeam-utils v0.8.8
     Compiling fnv v1.0.7
     Compiling serde_json v1.0.81
     Compiling once_cell v1.12.0
     Compiling lazy_static v1.4.0
     Compiling ryu v1.0.10
     Compiling itoa v1.0.2
     Compiling unicode-width v0.1.9
     Compiling bootstrap v0.0.0 (C:\b\s\w\ir\cache\builder\src\third_party\rust_src\src\src\bootstrap)
     Compiling cpufeatures v0.2.2
     Compiling hex v0.4.3
     Compiling getopts v0.2.21
  error: linker `link.exe` not found
    |
    = note: program not found

 note: the msvc targets depend on the msvc linker but `link.exe` was not found

 note: please ensure that Visual Studio 2017 or later, or Build Tools for Visual Studio were installed with the Visual C++ option.

 note: VS Code is a different product, and is not sufficient.
```


Bug: 1271215
Change-Id: Ibb4f4fe2fecc87b3fa3ab4f0edeedeab72bd3b46
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4071585
Reviewed-by: Hans Wennborg <hans@chromium.org>
Commit-Queue: danakj <danakj@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1080968}