Revert "Add weblayer_test_assets to weblayer_support_apk's DEPS."
This reverts commit ab07cc5bdd2e5fe9e0baa782aac02adbc3493b22.

Reason for revert: this CL causes the compile failure.

Sample build failure:
https://ci.chromium.org/ui/p/chromium/builders/ci/Android%20arm64%20Builder%20All%20Targets%20(dbg)/6692/overview

Original change's description:
> Add weblayer_test_assets to weblayer_support_apk's DEPS.
>
> WebLayerSupport.apk depends on assets/snapshot_blob_32.bin, but
> android_apk("weblayer_support_apk") doesn't have the dependency.
> We need to add android_assets("weblayer_test_assets") to the deps.
>
> Sample build failure:
> https://ci.chromium.org/ui/p/chromium/builders/ci/android-arm64-archive-rel/969/overview
>
> Sample log:
> KeyError: "There is no item named 'assets/snapshot_blob_32.bin' in the archive"
>
> Change-Id: I50c889c4b78a4f2f7351fed636a2fb3e75881b33
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4122819
> Commit-Queue: Takashi Sakamoto <tasak@google.com>
> Reviewed-by: Peter Beverloo <peter@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1091187}

Change-Id: Ieecaccc42bcd65e55b286828879ece2e3d9f1472
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4150371
Commit-Queue: Fergal Daly <fergal@chromium.org>
Owners-Override: Fergal Daly <fergal@google.com>
Auto-Submit: Takashi Sakamoto <tasak@google.com>
Reviewed-by: Fergal Daly <fergal@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1091203}