Fix AccountPreviewPreference usage in account aware password promo test
In crrev.com/c/8460583 (refs/heads/main@{#1710062}),
account_aware_password_signin_promo_unittest.cc was added using
pref.other_device_form_factor. Shortly after, in crrev.com/c/8500215
(refs/heads/main@{#1710150}), other_device_form_factor was combined into
PreferredDeviceInfo other_device_info.

Because crrev.com/c/8500215 branched before #1710062, it missed updating
the newly added test file. This causes compile failures on
Chrome-branded builders such as chrome/ci/win-chrome:

../../chrome/browser/ui/webui/password_manager/notification_cards/account_aware_password_signin_promo_unittest.cc(98,10):
error: no member named 'other_device_form_factor' in
'signin::AccountPreviewDataService::AccountPreviewPreference'
   98 |     pref.other_device_form_factor = form_factor;
      |     ~~~~ ^

Update the test to set pref.other_device_info.form_factor and include
syncer::PASSWORDS in enabled_data_types so device-aware titles format
correctly.

Bug: 546059799, 567901894
Change-Id: Ia4eea043c041eafb62025e107073be83bdf410fb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8499848
Reviewed-by: Steven Luong <stluong@chromium.org>
Commit-Queue: Darryl James <dljames@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1710589}