[Fuzzing] Fix Android dependencies in Blink fuzzers
This change fixes missing Android dependencies for Blink fuzzers by
introducing the `blink_fuzzer_test` template and centralizing assets in
`blink_fuzzer_test_support_assets`.

This avoids manual dependency management in each fuzzer target and
ensures all Blink fuzzers automatically receive the required assets when
built for Android.

The added dependencies solve errors at runtime similar to `JAVA
EXCEPTION: Caused by: java.lang.ClassNotFoundException`

R=titouan@chromium.org

Bug: 510921438
Test: Fuzzers built and executed successfully on Android.
Change-Id: Ie6d54a3bbfccfc5ec717ef1cd00bb7f8477cef94
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7852630
Reviewed-by: Titouan Rigoudy <titouan@chromium.org>
Commit-Queue: Kouhei Ueno <kouhei@chromium.org>
Auto-Submit: Edgar Aguilar <eledgar@google.com>
Reviewed-by: Kouhei Ueno <kouhei@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1642096}