[PA] Remove tautological casting
This CL edits two accesses of `PartitionRoot` members not to use
`reinterpret_cast`, since the members are already uintptr_ts. MSVC
raises an error for this tautological cast:

```
partition_bucket.cc(589): error C2440: 'reinterpret_cast':
  cannot convert from 'uintptr_t' to 'uintptr_t'
partition_bucket.cc(589): note: Conversion is a valid standard
  conversion, which can be performed implicitly or by use of
  static_cast, C-style cast or function-style cast
```

Bug: 1351310
Change-Id: I4a22055a8f1cea47c4b34f7844da109d7b2dbe7a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3872416
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Auto-Submit: Kalvin Lee <kdlee@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1043149}