Revert "Merge M87: "Disable overlays on nvidia hardware prior to 456.38 driver.""
This reverts commit 97dcf4ad7bdbbfdfe7fac48bd3d145495bf13539.

Reason for revert: This change is causing 'telemetry_gpu_unittests' failures on the M87 mac builders.

Initial failure:
https://ci.chromium.org/p/chromium-m87/builders/ci/Mac10.11%20Tests/378

Failure text:
[32/43] gpu_tests.test_expectations_unittest.GpuTestExpectationsValidation.testExpectationsFilesCanBeParsed failed unexpectedly 0.5062s:
  Traceback (most recent call last):
    File "/b/s/w/ir/content/test/gpu/gpu_tests/test_expectations_unittest.py", line 278, in testExpectationsFilesCanBeParsed
      'Error parsing %s:\n\t%s' % (os.path.basename(f.name), err))
  AssertionError: Error parsing info_collection_expectations.txt:
  	13: Unknown tag "nvidia"


I'm pretty sure this is because the cherry-picked CL relies on the tag that was introduced in this CL (https://chromium-review.googlesource.com/c/chromium/src/+/2459386).

Given that another merge is required, I would like to back this change out to fix the bots and have the CL author decide whether to update this change or merge the dependent CL before trying this one again.

Original change's description:
> Merge M87: "Disable overlays on nvidia hardware prior to 456.38 driver."
>
> NVIDIA has indicated that they don't expect overlays to work properly
> prior to the 455 driver. Confusingly, 456.38 appears to be the first
> r455 driver.
>
> TBR=​zmo
>
> (cherry picked from commit 899e736f9bc1916ad2f36182c7bcf2d9f308867e)
>
> Bug: 1113893, 1056267
> Change-Id: I7db3a1332628b64a9e480543b2b4d5434c91fd4f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2481065
> Commit-Queue: Dale Curtis <dalecurtis@chromium.org>
> Reviewed-by: Zhenyao Mo <zmo@chromium.org>
> Auto-Submit: Dale Curtis <dalecurtis@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#818171}
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2487694
> Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
> Cr-Commit-Position: refs/branch-heads/4280@{#657}
> Cr-Branched-From: ea420fb963f9658c9969b6513c56b8f47efa1a2a-refs/heads/master@{#812852}

TBR=dalecurtis@chromium.org

Change-Id: I4ff70433f943973dffbc9232e4b9d6cf24a75da8
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1113893
Bug: 1056267
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2495328
Reviewed-by: Joe Downing <joedow@google.com>
Commit-Queue: Joe Downing <joedow@google.com>
Cr-Commit-Position: refs/branch-heads/4280@{#676}
Cr-Branched-From: ea420fb963f9658c9969b6513c56b8f47efa1a2a-refs/heads/master@{#812852}