Avoid calling scrollIntoView on text nodes.
Chrome's version of check-layout.js tries to scroll to an error
message by calling message.previousSibling.scrollIntoView.

When previousSibling is a text node, this fails. This causes test
to fail with a generic error message, instead of displaying
the actual error.

"CONSOLE ERROR: Uncaught TypeError:
pre.previousSibling.scrollIntoView is not a function"

The fix avoids calling scrollIntoView on text nodes.

Example of unexpected failure:
https://luci-milo.appspot.com/ui/inv/build-8804882053093180193/test-results?q=fast%2Ftable%2Fpercent-widths-float.html

Bug: 1356256
Change-Id: Ic334eecb276a79fc0b486e7192cd35ff412683b5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3917693
Reviewed-by: Ian Kilpatrick <ikilpatrick@chromium.org>
Commit-Queue: Ian Kilpatrick <ikilpatrick@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1051874}