Revert "media/gpu/v4l2: extract EnumerateSupportedPixelformats() of V4L2Device"
This reverts commit 384452bcffff11f9d92b08773abdc3af84f29d31.

Reason for revert:
chromeos-chrome-115.0.5766.0_rc-r1: [1m../../../../../../../home/chrome-bot/chrome_root/src/media/gpu/v4l2/v4l2_unittest.cc:202:15: [0m[0;1;31merror: [0m[1mno member named 'EnumerateSupportedPixelformats' in 'media::V4L2Device'[0m
chromeos-chrome-115.0.5766.0_rc-r1:       device->EnumerateSupportedPixelformats(
chromeos-chrome-115.0.5766.0_rc-r1: [0;1;32m      ~~~~~~~~^
chromeos-chrome-115.0.5766.0_rc-r1: [0m1 error generated.
chromeos-chrome-115.0.5766.0_rc-r1:

Bug: b/282177829

Original change's description:
> media/gpu/v4l2: extract EnumerateSupportedPixelformats() of V4L2Device
>
> This CL extracts EnumerateSupportedPixelformats() out of V4L2Device,
> similarly to crrev/c/4516435. Doing so will allow further CLs to use
> this logic (note the |ioctl_cb| injected to the function).
>
> No new functionality, although I changed the DVLOGF(3) with the
> enumerated codecs to be in a single line and not in one-codec per
> line as ToT.
>
> Bug: b:279980150
> Change-Id: Ic3e04f61120421144241fb7c4860c51cce5c51ce
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4518972
> Commit-Queue: Miguel Casas-Sanchez <mcasas@chromium.org>
> Reviewed-by: Fritz Koenig <frkoenig@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1142951}

(cherry picked from commit aafc9173e880feef456b01b24bd7d96ee3d63842)

Bug: b:279980150
Change-Id: Iad576a5400ca8cb9ed6da849c23320e701941e32
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4527275
Commit-Queue: Miguel Casas-Sanchez <mcasas@chromium.org>
Reviewed-by: Sammie Quon <sammiequon@chromium.org>
Reviewed-by: Miguel Casas-Sanchez <mcasas@chromium.org>
Owners-Override: Sammie Quon <sammiequon@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1143317}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4529095
Commit-Queue: Yilkal Abe <yilkal@chromium.org>
Cr-Commit-Position: refs/branch-heads/5767@{#3}
Cr-Branched-From: 9023bb59db1ac664978f421f76b1a21cbc0a750f-refs/heads/main@{#1143188}