Make //ui/accessibility:platform component().
//ui/accessibility/platform:platform should depend on //ui/accessibility:accessibility.

The missing dependency causes the following flaky compile failure:
https://ci.chromium.org/ui/p/chromium/builders/ci/mac-arm64-archive-rel/15083/overview
---
In file included from ../../ui/accessibility/platform/automation/automation_v8_bindings.cc:18:
In file included from ../../ui/accessibility/ax_language_detection.h:16:
In file included from ../../third_party/cld_3/src/src/nnet_language_identifier.h:22:
In file included from ../../third_party/cld_3/src/src/embedding_feature_extractor.h:23:
../../third_party/cld_3/src/src/feature_extractor.h:45:10: fatal error: 'cld_3/protos/feature_extractor.pb.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	 1 error generated.
---

To fix the issue:
- make component("accessibility") to be component("accessiblity_internal").
- make component("platform") depend on component("accessibility_internal").
- add group("accessibility") and make other components depend on the group.
- If other components depend on //ui/accessibility/platform:platform, the components will depend on it via the group's public_deps.

Bug: 1393268

Change-Id: Id35a4b4ff25f7776ffb0fec22a4f09ab26feb74e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4054481
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Reviewed-by: David Tseng <dtseng@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1078389}