[M150] [experimental-opt-in] Loading placeholder animations
Original change's description:
> [experimental-opt-in] Loading placeholder animations
>
> Adds shimmering ghost loading animations while the opt-in UI container
> attempts to render the opt-in URL that is hosted in the webview. This
> communicates to the user that a page will render soon.
>
> Recording(s):
> go/screencast/cast/NTE3NjQ1NDQyOTAxNjA2NHw3ZWEzYTg2Yy00OQ
> go/screencast/cast/NTkzMjgwNjAyMTU3ODc1Mnw2MjczNzNmMC1jYQ
>
> Offline: go/screencast/cast/NTgxODUxNTA5NjMzODQzMnw3N2IxMWYxNS0zYg
> Error: go/screenshot/7mGVQcSzu9wfWeP
>
> Bug: b:513344047
> Change-Id: I78dc2dfda08db4d79c512aac4b39d6cfa9566c55
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7898152
> Commit-Queue: Roman Arora <romanarora@chromium.org>
> Reviewed-by: Marke Hallowell <wry@chromium.org>
> Reviewed-by: Theodore Olsauskas-Warren <sauski@google.com>
> Cr-Commit-Position: refs/heads/main@{#1641648}

(cherry picked from commit f33a36ceec0edb91a237b4d840239967b9cb78ab)

Bug: 519980886,b:513344047
Change-Id: I78dc2dfda08db4d79c512aac4b39d6cfa9566c55
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7910445
Auto-Submit: chrome-cherry-picker@chops-service-accounts.iam.gserviceaccount.com <chrome-cherry-picker@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/branch-heads/7871@{#666}
Cr-Branched-From: f542126b8c1b3e80104b26bb05ec830bd1206f29-refs/heads/main@{#1639810}