Fix ESLint test
The ESLint tests were broken by crrev.com/c/3628365 because it disabled
an error that the tests expected to have reported. This showed up when
testing "git cl presubmit --all". The failures looked like:

test_suite.py
vpython test_suite.py (4.53s) failed
E.................................................................
======================================================================
ERROR: testGetElementByIdCheck (web_dev_style.js_checker_eslint_test.JsCheckerEsLintTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../js_checker_eslint_test.py", line 59, in testGetElementByIdCheck
    results = self._runChecks("const a = document.getElementById('foo');", 'js')
  File ".../js_checker_eslint_test.py", line 42, in _runChecks
    format='json')[0]
IndexError: list index out of range

Potentially these error messagess could be made clearer. There was enough
evidence to investigate but I ended up doing a bisect, running
test_suite.py as I navigated through the history.

Bug: 1309977
Change-Id: I3bd0bd0d9e8b2ddba4015adfc58518c22794f280
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3632476
Reviewed-by: Demetrios Papadopoulos <dpapad@chromium.org>
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1000413}