Reland "web-engine: Add origin allow list"
This reverts commit 9f0dbcade0d88c076134f6bfff210091e5dd8479.

Reason for revert: The tests started failing because I missed out a full stop when I moved the error message in an exception:
"org.junit.ComparisonFailure: expected:<Navigation failed[]> but was:<Navigation failed[.]>"
Adding in that full stop in this reland.

Original change's description:
> Revert "web-engine: Add origin allow list"
>
> This reverts commit aa3b44ccfbf21714fdba924567dadc20511f2692.
>
> Reason for revert: https://crbug.com/1434307
>
> Original change's description:
> > web-engine: Add origin allow list
> >
> > We want to be able to allow developers to limit
> > WebEngine to particular domains if they are concerned
> > about their application interacting with other websites.
> >
> > Had to make the allowlist expect an ArrayList because the
> > Bundle we used to transport parameters only supports sending
> > arraylists. The alternative was adding an API like `addAllowListOrigin`
> > and hiding those details but it would be confusing to developers
> > that the allowlist only starts applying once you provide
> > a host while "setAllowList" seems a lot more clear.
> >
> > We are using strings instead of android.net.Uri because we are
> > only interested in the origin and don't want to give a confusing
> > public facing API.
> >
> > This uses NavigationThrottles so the good thing is it will
> > still call all the regular navigation observer methods like
> > navigation failure when the domain is blocked.
> >
> > Test: run_webengine_support_instrumentation_test_apk
> > Bug: 1420954
> > Change-Id: I2ab112b526f388ee745326717e51ddb5515b4cb8
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4405838
> > Commit-Queue: Rupert Wiser <bewise@chromium.org>
> > Auto-Submit: Rupert Wiser <bewise@chromium.org>
> > Reviewed-by: Rayan Kanso <rayankans@chromium.org>
> > Reviewed-by: Robert Sesek <rsesek@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#1131791}
>
> Bug: 1434307, 1420954
> Change-Id: I12d5006524f73096bb78c2b2387d22e85008e057
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4440667
> Owners-Override: Rubin Deliallisi <rubindl@chromium.org>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Commit-Queue: Rubin Deliallisi <rubindl@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1131867}

Bug: 1434307, 1420954
Change-Id: I4846dfa1bb27a6c321776cbcc427d1860f04b179
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4440629
Reviewed-by: Rayan Kanso <rayankans@chromium.org>
Auto-Submit: Rupert Wiser <bewise@chromium.org>
Commit-Queue: Robert Sesek <rsesek@chromium.org>
Reviewed-by: Rubin Deliallisi <rubindl@chromium.org>
Commit-Queue: Rupert Wiser <bewise@chromium.org>
Reviewed-by: Robert Sesek <rsesek@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1131940}