Revert "FSO: Do not allow observing symbolic links/hard links/junctions"
This reverts commit ba9cf6733415654b2f70763a7911a4e8c33e75ab.

Reason for revert: [Build sheriff] Suspected to cause persistent test failures on fuchsia-arm64-cast-receiver-rel and 
fuchsia-x64-cast-receiver-rel CQ bots.

First failure:
https://ci.chromium.org/ui/p/chromium/builders/ci/fuchsia-arm64-cast-receiver-rel/17237/

Failing tests:
FileSystemAccessObserveWithFlagBrowserTest.UnobserveDisabledByDefault
FileSystemAccessObserverBrowserTest.NonRecursiveWatchReportsAppearedWhenDirectDescendentMovedFromNonDirectDescendent
FileSystemAccessObserverBrowserTest.NonRecursiveWatchReportsDisappearedWhenDirectDescendentMovedToNonDirectDescendent
FileSystemAccessObserverBrowserTest.ObserveDirectory
FileSystemAccessObserverBrowserTest.ObserveDirectoryRecursively
FileSystemAccessObserverBrowserTest.ObserveDirectoryReportsCorrectHandle
FileSystemAccessObserverBrowserTest.ObserveDirectoryReportsCorrectHandleType
FileSystemAccessObserverBrowserTest.ObserveDirectoryReportsCorrectRelativePathComponents
FileSystemAccessObserverBrowserTest.ObserveDirectoryReportsMoveChangeInfo
FileSystemAccessObserverBrowserTest.WritableReportsSingleModifiedEventOnClose

Sample output:
[ RUN      ] FileSystemAccessObserveWithFlagBrowserTest.UnobserveDisabledByDefault

DevTools listening on ws://127.0.0.1:32566/devtools/browser/a38d646b-dcbe-45ab-9511-25510a325f06
[128576:128578:0903/195714.040306:WARNING:viz_main_impl.cc(85)] VizNullHypothesis is disabled (not a warning)
../../content/browser/file_system_access/file_system_access_observer_browsertest.cc:334: Failure
Value of: result.error.find("is not a function") != std::string::npos
  Actual: false
Expected: true
a JavaScript error: "InvalidModificationError: The object can not be modified in this way."

Original change's description:
> FSO: Do not allow observing symbolic links/hard links/junctions
>
> This change adds a check in FileSystemAccessObserverHost that runs the
> ObserveCallback with an error if the path corresponding with the
> TransferToken is a symlink or junction.
>
> Bug: 360147104
> Change-Id: I1c46cd4b8ef3f1db3d9ead0f3567794d8c19fd07
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5814588
> Reviewed-by: Nathan Memmott <memmott@chromium.org>
> Commit-Queue: Rahul Singh <rahsin@microsoft.com>
> Reviewed-by: Ayu Ishii <ayui@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1350303}

Bug: 360147104
Change-Id: Ibc8ba78aea6d800226e8591736f992ce3d271540
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5834121
Commit-Queue: Alex Moshchuk <alexmos@chromium.org>
Owners-Override: Alex Moshchuk <alexmos@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1350416}