Roll Skia from 863497b7fea4 to e89b50ae054c (13 revisions)
https://skia.googlesource.com/skia.git/+log/863497b7fea4..e89b50ae054c

2021-02-10 stani@google.com Android roll broke with a compilation error:
2021-02-09 michaelludwig@google.com Delete deprecated alpha threshold header
2021-02-09 johnstiles@google.com Add support for matrix == and != in Metal shaders.
2021-02-09 jvanverth@google.com Implement indirect draws in Metal
2021-02-09 johnstiles@google.com Rename `bool highp` to a non-reserved keyword.
2021-02-09 bungeman@google.com GM glyph_pos correct advance placement.
2021-02-09 ethannicholas@google.com Added SkSL DSL switch statements
2021-02-09 jlavrova@google.com Fixing a crash in Flutter Text Editor
2021-02-09 johnstiles@google.com Remove deprecated form of SkRuntimeEffect::Make.
2021-02-09 brianosman@google.com Add .stage output to skslc for runtime effects
2021-02-09 brianosman@google.com Stop exposing non-square matrices to runtime effects
2021-02-09 johnstiles@google.com Add SkSL test demonstrating missed optimization with +=.
2021-02-09 bungeman@google.com SkScalerContext to handle hairline paths.

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/skia-autoroll
Please CC borenet@google.com on the revert to ensure that a human
is aware of the problem.

To report a problem with the AutoRoller itself, please file a bug:
https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/master/autoroll/README.md

Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:linux-blink-rel;luci.chromium.try:linux-chromeos-compile-dbg;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:win_optional_gpu_tests_rel
Cq-Do-Not-Cancel-Tryjobs: true
Bug: chromium:1172543
Tbr: borenet@google.com
Change-Id: If2cf7773f4f9df5d7c0cabdb4f4705efb467308c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2686473
Reviewed-by: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Cr-Commit-Position: refs/heads/master@{#852493}