Fix calculate_package_deps.py error path to work in Python 3
Without this change, a failure in the invocation of dpkg-shlibdeps
will give:

Traceback (most recent call last):
  File ".../chrome/installer/linux/debian/calculate_package_deps.py", line 70, in <module>
    print('stderr was ' + stderr)
TypeError: can only concatenate str (not "bytes") to str

Fix by using the 'encoding' argument instead of decode().  Also change
to use '%' rather than '+', and put the stderr output on a different
line.

Bug: 1299021
Change-Id: Ia8c3cf112d723736248a916c7f40048ce0dcace9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3595268
Reviewed-by: Thomas Anderson <thomasanderson@chromium.org>
Commit-Queue: Mark Seaborn <mseaborn@chromium.org>
Cr-Commit-Position: refs/heads/main@{#994720}