[Android] Re-enable WebContentsAccessibilityEventsTest
Set up filtering again of "trivial" events.

Exception: 6 tests which are now failing.

Bug: 414363686
Change-Id: I05afde54d24ff98023bc9d0df406bdd698e77b26
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6639856
Commit-Queue: Henrique Nakashima <hnakashima@chromium.org>
Reviewed-by: Mark Schillaci <mschillaci@google.com>
Auto-Submit: Henrique Nakashima <hnakashima@chromium.org>
Commit-Queue: Mark Schillaci <mschillaci@google.com>
Cr-Commit-Position: refs/heads/main@{#1472744}