QuotaExceededError: Add helper for throwing new QuotaExceededErrors
This change adds a new `ThrowQuotaExceededError` helper to
ExceptionState to throw the new DOMException derived
QuotaExceededError. Services using this will be updated
in a follow-up CL. Dependency injection is used to create
in `platform/`, similar to DOMException, since DOMException
& QuotaExceededError is defined in `core/`.

Bug: 406162261
Change-Id: I2d6ba89c5dfe8431c577e7dfe9fd4e43183f0184
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6533783
Reviewed-by: Andrey Kosyakov <caseq@chromium.org>
Reviewed-by: Joey Arhar <jarhar@chromium.org>
Commit-Queue: Ayu Ishii <ayui@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1461021}