Minor improvement of error messages from `run_cargo_metadata`.
When `generate_for_std` calls `run_cargo_metadata` it may fails and
refer in its error message to `Cargo.toml` or `.cargo/config.toml`.
After this CL, the error message will also refer to the templates that
these files are generated from - see the "synthesized from ..." line in
the example error message below:

```
Running cargo --quiet --locked run --release --manifest-path .../chromium2/src/tools/crates/gnrt/Cargo.toml --target-dir=/tmp/tmpahza0kxn/target -- gen --for-std=third_party/rust-src
Generating stdlib GN rules from third_party/rust-src
Error: Failed to parse cargo metadata in a directory synthesized from build/rust/std/fake_root/Cargo.toml.template and build/rust/std/fake_root/.cargo/config.toml.template

Caused by:
    0: running cargo metadata
    1: `cargo metadata` exited with an error: error: could not load Cargo configuration

       Caused by:
         could not parse TOML configuration in `.../chromium2/src/build/rust/std/fake_root/.cargo/config.toml`

       Caused by:
         TOML parse error at line 1, column 5
           |
         1 | blah
           |     ^
         expected `.`, `=`

Failed.
```

Note that this CL doesn't fix https://crbug.com/339172099 - it is just
an opportunistic, related follow-up.

Bug: 339172099
Change-Id: I39e2db496664a54f3ec5af15a99d805ec9c9a772
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5530010
Commit-Queue: Łukasz Anforowicz <lukasza@chromium.org>
Reviewed-by: danakj <danakj@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1298834}