Revert "Remove kDCompVisualTreeOptimization feature flag"
This reverts commit 5b54e581ad2ae4324ff07adda3ce06e4a2ecca48.

Reason for revert: build failure surfaced on `win-archive-rel`

```
[85349/101903] CXX obj/ui/gl/gl_unittests/direct_composition_surface_win_unittest.obj
FAILED: obj/ui/gl/gl_unittests/direct_composition_surface_win_unittest.obj
..\..\buildtools\reclient\rewrapper -cfg=..\..\buildtools\reclient_cfgs\chromium-browser-clang\rewra...(too long)
../../ui/gl/direct_composition_surface_win_unittest.cc(1536,28): error: no member named 'GetAttachedToRootFromPreviousFrameForTesting' in 'gl::DCLayerTree'
1536 |   EXPECT_TRUE(dcLayerTree->GetAttachedToRootFromPreviousFrameForTesting(0));
|               ~~~~~~~~~~~  ^
../..\third_party/googletest/src/googletest/include/gtest/gtest.h(1823,50): note: expanded from macro 'EXPECT_TRUE'
```

GN args, for posterity:

```
dcheck_always_on = false
is_component_build = false
is_debug = false
symbol_level = 1
use_remoteexec = true
```

Original change's description:
> Remove kDCompVisualTreeOptimization feature flag
>
> Optimized tree building has been enabled for Chromium releases.
> Time to say goodbye to the non-optimized version.
>
> Bug: 41490668
> Change-Id: Ifc64876004a9e2870a02bff310fd238bd4d3479b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5399690
> Reviewed-by: Michael Tang <tangm@microsoft.com>
> Reviewed-by: Sunny Sachanandani <sunnyps@chromium.org>
> Commit-Queue: Rafael Cintron <rafael.cintron@microsoft.com>
> Cr-Commit-Position: refs/heads/main@{#1279388}

Bug: 41490668
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I37ed33c54cd7384343671496c3a4aae9b25753fb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5404326
Owners-Override: Kalvin Lee <kdlee@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Kalvin Lee <kdlee@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1279409}