build: drop python2 support from print_python_deps.py
As we migrated build and test to python3, I don't think we need to keep
this script py2 compatible.

Also this was already broken with python2 like below.

```
$ build/print_python_deps.py --root third_party/blink/renderer/bindings/scripts --output third_party/blink/renderer/bindings/scripts/generate_bindings.pydeps third_party/blink/renderer/bindings/scripts/generate_bindings.py
Traceback (most recent call last):
  File "build/print_python_deps.py", line 227, in <module>
    sys.exit(main())
  File "build/print_python_deps.py", line 216, in main
    out = open(options.output, 'w', newline='') if options.output else sys.stdout
TypeError: 'newline' is an invalid keyword argument for this function
```

Bug: 942720
Change-Id: I4e81fda8d12cce19226d9e9dd9ee3992e4ec7b65
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3686989
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Auto-Submit: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1010060}