Validate that UKM event or metric names don't start with a digit
I will make the same change to the internal version.
Tested locally. For event or metric name starting with a digit, it blocks on the "git cl upload" step:

ValueError: name "3PCBlocked" does not match regex "^[A-Za-z][A-Za-z0-9_.]*$"
** Presubmit Warnings: 1 **

Bug: b/293136767
Change-Id: Icbf196084e6ab250bfa20cd9a7a93cd7540f9d27
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4721416
Reviewed-by: Alexei Svitkine <asvitkine@chromium.org>
Commit-Queue: Sun Yueru <yrsun@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1176738}