Scale WebGL global test timeout by slow multiplier
Currently, WebGLConformanceIntegrationTestBase._GetHeartbeatTimeout()
scales the per-message heartbeat timeout by _GetSlowMultiplier() (4x)
when a test is marked [ Slow ] in test expectations, but
_GetTestTimeout() ignores _GetSlowMultiplier() and enforces a fixed
300s (or 600s on ASAN) global timeout.

As a result, slow tests that legitimately take >300s on Debug builds
(such as conformance/extensions/webgl-compressed-texture-size-limit.html
on Mac Debug (Intel)) still fail with:
RuntimeError: Hit 300.000 second global timeout, but page continued to
send messages over the websocket.

Scale _GetTestTimeout() by self._GetSlowMultiplier() so that [ Slow ]
expectations apply to both the heartbeat and global test timeouts.

Bug: 562980317
Change-Id: Ie612a8424340af7f08728d08ce41c91e5f453af9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8465952
Reviewed-by: Brian Sheedy <bsheedy@chromium.org>
Commit-Queue: Jonathan Ross <jonross@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1706502}