Also bundle repackage_native_impl output
As things stand, both repackage_native and repackage_test_jars
bundle org/chromium/base/natives/GEN_JNI.class. This causes issues
downstream, where the one bundled in repackage_native is currently
winning (for not well defined reasons). Winning in this context means
that Java -> C++ JNI calls will be resolved looked up inside
GEN_JNI.class. This is a problem because repackage_native's GEN_JNI
doesn't contain JNI defined by tests, so tests fails with
java.lang.NoSuchMethodError: No static method
org_chromium_net_NativeTestServer_startNativeTestServer

This CL circumvent the issue by also bundling the output of
repackage_native_impl. Its output is in fact exactly the same of
repackage_native, modulo the stripping of GEN_JNI.class. This way
the one bundled in repackage_test_jars will always win.

Rename repackage_native_impl to repackage_native_without_jni
to better reflect its contents.

(cherry picked from commit 33dcf69fcc63050f70fe88db3ff90b2644ddd5a8)

Bug: b:266917718, 1401015
Change-Id: I31117dcc86a60c88fec5525ef0fca0ab532e1db7
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4269597
Auto-Submit: Mohannad Farrag <aymanm@google.com>
Reviewed-by: Stefano Duo <stefanoduo@google.com>
Commit-Queue: Stefano Duo <stefanoduo@google.com>
Cr-Commit-Position: refs/branch-heads/5563@{#644}
Cr-Branched-From: 3ac59a6729cdb287a7ee629a0004c907ec1b06dc-refs/heads/main@{#1097615}