Revert "[OSCrypt] Remove free function interface"
This reverts commit 22701ff755191f0069a11b385581803fe1d3b363.

Reason for revert:

This broke iOS bots. 
https://ci.chromium.org/ui/p/chrome/builders/ci/simulator-builder/103671/blamelist

[1491/2183] OBJCXX obj/ios_internal/chrome/browser/providers/signin/unit_tests/chrome_identity_service_impl_unittest.o
FAILED: obj/ios_internal/chrome/browser/providers/signin/unit_tests/chrome_identity_service_impl_unittest.o
/opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -...(too long)
../../ios_internal/chrome/browser/providers/signin/chrome_identity_service_impl_unittest.mm:132:5: error: no member named 'SetUp' in 'OSCryptMocker'; did you mean simply 'SetUp'?
OSCryptMocker::SetUp();
^~~~~~~~~~~~~~~~~~~~
SetUp
../../third_party/googletest/src/googletest/include/gtest/gtest.h:295:16: note: 'SetUp' declared here
virtual void SetUp();
^



Original change's description:
> [OSCrypt] Remove free function interface
>
> Removed free function interface, instead used
> directly singleton instance. Updated callers and
> unit tests.
>
> Bug: 1308315
> Change-Id: I3304d4f6b3510df3489b08d741d5d4d8a40635a4
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3550580
> Commit-Queue: Paweł Barań <pbaran@opera.com>
> Reviewed-by: Eric Seckler <eseckler@chromium.org>
> Reviewed-by: Ted Choc <tedchoc@chromium.org>
> Reviewed-by: Christos Froussios <cfroussios@chromium.org>
> Reviewed-by: Sebastien Lalancette <seblalancette@chromium.org>
> Reviewed-by: Kinuko Yasuda <kinuko@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1003717}

Bug: 1308315
Change-Id: I5d5fc1956cf759fb56bd88e8d1a7cb680570686f
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3650959
Reviewed-by: edchin <edchin@google.com>
Owners-Override: edchin <edchin@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: edchin <edchin@google.com>
Commit-Queue: edchin <edchin@google.com>
Cr-Commit-Position: refs/heads/main@{#1003795}