proguard: Fix up rules for cardboard now that we don't keep all natives
https://ci.chromium.org/ui/p/chromium/builders/ci/android-10-arm64-rel/33047/overview
Cardboard tests were failing with:
java.lang.NoSuchMethodError: no static or non-static method
"Lcom/google/cardboard/sdk/QrCodeCaptureActivity;.nativeIncrementDeviceParamsChangedCount()V"

This is due to the change we made in
https://chromium-review.googlesource.com/c/chromium/src/+/5253758

We no longer just apply this keep rule to all natives, so places which
rely on natives being not renamed must specify that themselves.

Change-Id: I028219c402af2454a1f5ed40c169046e13744161
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5277566
Reviewed-by: Zhe Li <zheliooo@google.com>
Owners-Override: Shu Yang <shuyng@google.com>
Auto-Submit: Sam Maier <smaier@chromium.org>
Commit-Queue: Shu Yang <shuyng@google.com>
Cr-Commit-Position: refs/heads/main@{#1257713}