IWYU: math.h required to use floor() in QR code generator
../../chrome/common/qr_code_generator/qr_code_generator.cc: In member function ‘unsigned int QRCodeGenerator::CountPenaltyPoints() const’:
../../chrome/common/qr_code_generator/qr_code_generator.cc:977:40: error: ‘floor’ was not declared in this scope
  977 |   penalty += 5 * static_cast<unsigned>(floor(deviation));
      |                                        ^~~~~

Bug: 957519
Change-Id: Ibf428161deeea35111edcbc9085459ec4966a50d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2394160
Commit-Queue: Adam Langley <agl@chromium.org>
Reviewed-by: Adam Langley <agl@chromium.org>
Cr-Commit-Position: refs/heads/master@{#804606}