Clang build script: Fix python3 problem after crrev.com/c/906112
I didn't notice it locally (python2), but on the bots (python3) the
script would fail with:

SyntaxError: name 'LLVM_BUILD_DIR' is used prior to global declaration
Error: Command 'python3 src/tools/clang/scripts/build.py
    --llvm-force-head-revision --with-android=False --with-fuchsia=False' returned
  non-zero exit status 1 in /b/s/w/ir/cache/builder
  File "src/tools/clang/scripts/build.py", line 535
    global CLANG_REVISION, PACKAGE_VERSION, LLVM_BUILD_DIR
    ^
SyntaxError: name 'LLVM_BUILD_DIR' is used prior to global declaration

Bug: none
Change-Id: I950d70a3f767398409d0023dc709d7021b699d21
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3059450
Commit-Queue: Hans Wennborg <hans@chromium.org>
Auto-Submit: Hans Wennborg <hans@chromium.org>
Reviewed-by: Primiano Tucci <primiano@chromium.org>
Cr-Commit-Position: refs/heads/master@{#906635}