Revert "Remove expired histogram Search.IcingContextReportingStatus."
This reverts commit 676a925fc6ccd43512518ea18a9dbf79273da5c3.

Reason for revert: Chromeperf android builder started to fail after this commit.
First failure:
https://ci.chromium.org/ui/p/chrome/builders/ci/android-builder-perf/651421/overview
Build log:
https://logs.chromium.org/logs/chrome/buildbucket/cr-buildbucket/8763688418810784257/+/u/compile/stdout

[3851/5440] ACTION //clank/java:clank_java__compile_java(//build/toolchain/android:android_clang_arm)
FAILED: obj/clank/java/clank_java.javac.jar obj/clank/java/clank_java.javac.jar.info 
python3 ../../build/android/gyp/compile_java.py --depfile=gen/clank/java/clank_java__compile_java.d --generated-dir=gen/clank/java/clank_java/generated_java --jar-path=obj/clank/java/clank_java.javac.jar --java-srcjars=\[\"gen/clank/java/clank_java__assetres.srcjar\",\ \"gen/clank/java/clank_java.generated.srcjar\"\] --target-name //clank/java:clank_java__compile_java --classpath=@FileArg\(gen/clank/java/clank_java.build_config.json:android:sdk_interface_jars\) --header-jar obj/clank/java/clank_java.turbine.jar --classpath=\[\"obj/clank/java/clank_java.turbine.jar\"\] --classpath=@FileArg\(gen/clank/java/clank_java.build_config.json:deps_info:javac_full_interface_classpath\) --chromium-code=1 --warnings-as-errors --jar-info-exclude-globs=\[\"\*/R.class\",\ \"\*/R\\\$\*.class\",\ \"\*/Manifest.class\",\ \"\*/Manifest\\\$\*.class\",\ \"\*/\*GEN_JNI.class\"\] @gen/clank/java/clank_java.sources
../../clank/java/src/com/google/android/apps/chrome/icing/GoogleApiIcingLightweightClientImpl.java:87: error: cannot find symbol
            ContextReporter.reportStatus(ContextReporter.STATUS_SYNC_NOT_READY_AT_REPORT_TIME);
                                                        ^
  symbol:   variable STATUS_SYNC_NOT_READY_AT_REPORT_TIME
  location: class ContextReporter

Original change's description:
> Remove expired histogram Search.IcingContextReportingStatus.
>
> OBSOLETE_HISTOGRAM[Search.IcingContextReportingStatus]=expired
>
> Bug: 1499480
> Change-Id: I11339f8bba089351216769f242bfc93441e55ab4
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5050169
> Reviewed-by: Alex Ilin <alexilin@chromium.org>
> Commit-Queue: Alexandra Reimers <areimers@chromium.org>
> Code-Coverage: findit-for-me@appspot.gserviceaccount.com <findit-for-me@appspot.gserviceaccount.com>
> Reviewed-by: Luc Nguyen <lucnguyen@google.com>
> Cr-Commit-Position: refs/heads/main@{#1228186}

Bug: 1499480
Change-Id: Ic9be4b6c4a21d08866f63e123fba84e9e4170da0
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5055372
Reviewed-by: Haiyang Pan <hypan@google.com>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Reviewed-by: Gregory Guterman <guterman@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Gregory Guterman <guterman@google.com>
Cr-Commit-Position: refs/heads/main@{#1228249}