Revert "[TabStripApi] Modify TabCollection by removing nested unions"
This reverts commit 6b74e38277c06c6b4060b5db13bde246d89c9b74.

Reason for revert: See failure here:
https://ci.chromium.org/ui/p/chromium/builders/ci/Linux%20MSan%20Builder/101437/overview

Suspect CL, error messsage reads:
error TS2339: Property 'tabContainer' does not exist on type 'ContainerMojoType'.

Bug: 437405835
Original change's description:
> [TabStripApi] Modify TabCollection by removing nested unions
>
> The existing container structure increases frictions for clients due to
> the nested union and container types. A client must first check the
> outer Container union and then subsequently check the inner
> TabCollection union when parsing the collection tree.
>
> This CL simplifies the data model by removing the Container union.
>
> https://docs.google.com/document/d/1Cnxk4k5Cwk1bInFaQvn5L6jVfdFmCpwLPGHAQ28e6qU/edit?usp=sharing&resourcekey=0-2zhFvXZKyxdTIKVEiOBoqQ
>
> Bug: 437405835
> Change-Id: I2ecd78110682c9429f07d7da94c9fe772f66b8c2
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6828512
> Commit-Queue: Fred Shih <ffred@chromium.org>
> Reviewed-by: Tom Lukaszewicz <tluk@chromium.org>
> Reviewed-by: Fred Shih <ffred@chromium.org>
> Reviewed-by: Matthew Denton <mpdenton@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1500484}

Bug: 437405835
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: If994995a20a4031b212af12e96866538088df670
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6843923
Owners-Override: Roman Arora <romanarora@chromium.org>
Commit-Queue: Roman Arora <romanarora@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1500489}