webuijserror: Use build_webui() GN rule.
Also build_webui() previously assumed that a tsconfig_base.json would
always be provided, but this is not the case for super simple cases
like webui_js_error. Exposed a new `ts_use_local_config` property to
accommodate both cases.

Bug: 1340376
Change-Id: I4c684c24e42ffe9d0969fd16d9b10a2bdd5b8477
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3774399
Commit-Queue: Demetrios Papadopoulos <dpapad@chromium.org>
Reviewed-by: Rebekah Potter <rbpotter@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1026426}