Revert "ttc: Build for Clank Desktop"
This reverts commit 010df698027559c0cd13d31f08fea3c18765f6a8.

Reason for revert: Appears to have broken compile on android-desktop-arm64

Failure Link: https://ci.chromium.org/ui/p/chromium/builders/ci/android-desktop-arm64-archive-rel/19330

Failure is:

In file included from ../../chrome/browser/ui/webui/ai_overlay_dialog/ai_overlay_dialog_page_handler_unittest.cc:13:
../../chrome/browser/ui/tabs/tab_strip_model.h:46:2: error: This file should only be included on desktop.
   46 | #error This file should only be included on desktop.


Original change's description:
> ttc: Build for Clank Desktop
>
> - Compile the necessary files for Chrome on Desktop Android.
>
> - Chrome Views does not exist on Clank, so mock out all the dependencies
>   that ttc relies on (e.g., WebUI), and rebuild them using Jetpack
>   Compose and Android Native UI.
>
> Bug: b:534883880
> Change-Id: I920df562dc556c14cea18a8712288f87b6ac26e8
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8101304
> Reviewed-by: Adithya Srinivasan <adithyas@chromium.org>
> Reviewed-by: Gary Klassen <gklassen@chromium.org>
> Commit-Queue: Michael Wojcicka <mwoj@google.com>
> Reviewed-by: Nasko Oskov <nasko@chromium.org>
> Reviewed-by: Linyu He <linyuh@google.com>
> Reviewed-by: James Hawkins <jhawkins@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1684114}

Bug: b:534883880
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I7d75b85b3a77bf0f4b8cd3bbb08a0de43f82a86f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8278163
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Ian Clelland <iclelland@chromium.org>
Owners-Override: Ian Clelland <iclelland@chromium.org>
Reviewed-by: Michael Wojcicka <mwoj@google.com>
Auto-Submit: Ian Clelland <iclelland@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1684143}