SQL: handle failure during recovery more gracefully.
When attempting a recovery, if the meta table is corrupted then the
`key` column can be missing, leading to errors like:

    SQL compilation error: table meta has no column named key.
    Statement: INSERT OR REPLACE INTO meta(key,value) VALUES(?,?)

Current code goes on to attempt to run this statement anyway, which
leads to a fatal DLOG. Intercept this problem earlier for a more
graceful exit.

Bug: 331970403
Change-Id: I3c20d0fdcdbd927df22011c9a4f6d27e96293d42
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5408209
Reviewed-by: Nathan Memmott <memmott@chromium.org>
Commit-Queue: Evan Stade <estade@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1280898}