android: customtabs_benchmark: fix import for py3
The run_benchmark.py was converted to py3 without running it. With
--help it fails like this:

```
  File "/path/to/run_benchmark.py", line 17, in <module>
    from . import customtabs_benchmark
ImportError: attempted relative import with no known parent package
```

Adding the path and importing as 'import customtabs_benchmark'.

Bug: 1154224
Change-Id: I5741dd0aa07685cb79b268bfc0119e40fe68523c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3226108
Reviewed-by: Benoit L <lizeb@chromium.org>
Commit-Queue: Egor Pasko <pasko@chromium.org>
Cr-Commit-Position: refs/heads/main@{#932066}