Add missing dependency
In https://ci.chromium.org/p/chrome/builders/official/mac64/1684:

[44479/53271] CXX obj/chrome/browser/extensions/api/api_registration/generated_api_registration.o
FAILED: obj/chrome/browser/extensions/api/api_registration/generated_api_registration.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/browser/extensions/api/api_registration/generated_api_registration.o.d obj/chrome/browser/extensions/api/api_registration/generated_api_registration.o
In file included from gen/chrome/browser/extensions/api/generated_api_registration.cc:49:
In file included from ../../chrome/browser/extensions/api/tabs/tabs_api.h:14:
In file included from ../../components/translate/content/browser/content_translate_driver.h:14:
gen/components/translate/content/common/translate.mojom.h:30:10: fatal error: 'components/translate/content/common/translate.mojom-shared.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

This fails because tabs_api is being included from outside, yet only declares the
translation code as a deps and not a public_deps.

Bug: 1130293
Change-Id: I86574e6a8688580d4ae8a465784e10b1bebae48d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2436785
Reviewed-by: Reilly Grant <reillyg@chromium.org>
Commit-Queue: Avi Drissman <avi@chromium.org>
Cr-Commit-Position: refs/heads/master@{#811803}