Reland "widevine: Add `ignore_missing_widevine_signing_cert` gn arg"
This reverts commit 3ec270e41c8575923025e7adec27661b9e00f296.

Reason for revert: src-internal DEPS roll happened. Relanding this CL.

Also update mb_config.pyl to use the new gn arg to skip widevine
signing on public "offiical" Mac builders.

This fixes compile errors like:
  ERROR: Cannot find Widevine signing cert!

Original change's description:
> Revert "widevine: Add `ignore_missing_widevine_signing_cert` gn arg"
>
> This reverts commit 175e67feaca515167e6251f606dd44d7ff1f5c85.
>
> Reason for revert: Needs to wait for src-internal DEPS roll to be landed.
>
> Original change's description:
> > widevine: Add `ignore_missing_widevine_signing_cert` gn arg
> >
> > When Widevine CDM host verification signing failed due to no
> > signing cert, the build process will fail by default. However,
> > developers making local builds typically don't have those certs.
> > This CL introduces `ignore_missing_widevine_signing_cert` gn arg
> > so the error caused by missing Widevine signing cert could be
> > ignored.
> >
> > By default, `ignore_missing_widevine_signing_cert` is set to false
> > on official bots (is_official_build=true) to catch real failures.
> > Developers needing to set `is_official_build` can manually set
> > this gn arg to be true to suppress the error.
> >
> > Bug: 1127616
> > Change-Id: I41a43e922399497c75f1f967219d41d1566d90dc
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2412933
> > Commit-Queue: John Rummell <jrummell@chromium.org>
> > Reviewed-by: Michael Moss <mmoss@chromium.org>
> > Reviewed-by: John Rummell <jrummell@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#807513}
>
> TBR=xhwang@chromium.org,mmoss@chromium.org,jrummell@chromium.org
>
> Change-Id: I9a67901d83a13881180fcfe63cecb240cc5ebcde
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 1127616
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2414652
> Reviewed-by: Xiaohan Wang <xhwang@chromium.org>
> Commit-Queue: Xiaohan Wang <xhwang@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#807559}

TBR=xhwang@chromium.org,mmoss@chromium.org,jrummell@chromium.org

# Not skipping CQ checks because this is a reland.

Bug: 1127616
Change-Id: I2857b1a306688e42b370108ab55dc8744f794a65
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2415369
Reviewed-by: Stephen Martinis <martiniss@chromium.org>
Reviewed-by: Xiaohan Wang <xhwang@chromium.org>
Reviewed-by: Michael Moss <mmoss@chromium.org>
Reviewed-by: John Rummell <jrummell@chromium.org>
Commit-Queue: Xiaohan Wang <xhwang@chromium.org>
Cr-Commit-Position: refs/heads/master@{#807738}