Consider ax::mojom::Event::kScrollPositionChanged not handled by AXEventGenerator
This event gets fired by ARC++, so it's likely been a no-op in automation ever
since the event generator changes, since ARC++ doesn't set any of the *scroll*
int attributes.
chrome/browser/chromeos/arc/accessibility/arc_accessibility_util.cc

It does get fired by Blink as well at the moment
third_party/blink/renderer/modules/accessibility/ax_object_cache_impl.cc
so this patch changes those event sites to generic events.

Finally, re-introducing this event seems to have triggered
Error: Error in event handler for scrollPositionChanged during phase 1: TypeError: Cannot read property 'start' of null
    at Output.range_ (chrome-extension://mndnfokpggljbaajbnioimlmbfngpief/chromevox/chromeVoxChromeBackgroundScript.js:1246:77)
        at Output.render_ (chrome-extension://mndnfokpggljbaajbnioimlmbfngpief/chromevox/chromeVoxChromeBackgroundScript.js:1183:83)
	    at Output.withLocation (chrome-extension://mndnfokpggljbaajbnioimlmbfngpief/chromevox/chromeVoxChromeBackgroundScript.js:1148:107)
	        at DesktopAutomationHandler.onScrollPositionChanged (chrome-extension://mndnfokpggljbaajbnioimlmbfngpief/chromevox/chromeVoxChromeBackgroundScript.js:2232:140)
		    at DesktopAutomationHandler.<anonymous> (chrome-extension://mndnfokpggljbaajbnioimlmbfngpief/chromevox/chromeVoxChromeBackgroundScript.js:1824:1)

which we can check for explicitly. What looks to be happening is the target of
the scroll position changed is detached.

R=dmazzoni@chromium.org, hirokisato@chromium.org

Change-Id: If3008218d8e0565428bd18cf8642eb106d83fdec
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2451974
Reviewed-by: Dominic Mazzoni <dmazzoni@chromium.org>
Commit-Queue: David Tseng <dtseng@chromium.org>
Cr-Commit-Position: refs/heads/master@{#816187}