IWYU: vector used in gl_display.h requires include.
Fix build bug with libstdc++:
    ../../ui/gl/gl_display.h:80:5: error: ‘std::vector’ has not been declared
       80 |     std::vector<DisplayType>* init_displays);
          |     ^~~

Bug: 957519
Change-Id: Ib5cf8768f030d5ced945512c05f5eb6e4487898b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3731768
Reviewed-by: Maggie Chen <magchen@chromium.org>
Commit-Queue: Maggie Chen <magchen@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1019936}