Revert "[CORS-RFC1918] Selectively re-enable broken test."
This reverts commit 96a972a12ca41b446ae02033a1c742127e940364.

Reason for revert:
PrivateNetworkRequestBrowserTest.RecordsAddressSpaceFeatureForFetch
is flaky on
https://ci.chromium.org/p/chromium/builders/ci/Win10%20Tests%20x64

It failed 4 out of the last 25 builds.
https://screenshot.googleplex.com/8bGbnEgxTnyrXk9

When I say failed, I mean it failed on both the original run and the re-run (i.e. failed twice in a row), which turns the bot read.

The failures look like
[ RUN      ] PrivateNetworkRequestBrowserTest.RecordsAddressSpaceFeatureForFetch
[20276:19520:1109/002722.827:ERROR:device_event_log_impl.cc(211)] [00:27:22.827] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.
../../chrome/browser/net/private_network_request_browsertest.cc(171): error: Value of: GetAddressSpaceFeatureBucketCounts(histogram_tester)
Expected: has 1 element that has a first field that is equal to WebFeature::kAddressSpaceLocalEmbeddedInPublicSecureContext, and has a second field that is equal to 1
  Actual: {}
Stack trace:
Backtrace:
	`anonymous namespace'::PrivateNetworkRequestBrowserTest_RecordsAddressSpaceFeatureForFetch_Test::RunTestOnMainThread [0x00007FF66FF0A4D5+1211] (o:\chrome\browser\net\private_network_request_browsertest.cc:168)
	content::BrowserTestBase::ProxyRunTestOnMainThreadLoop [0x00007FF673CD884D+683] (o:\content\public\test\browser_test_base.cc:770)
	ChromeBrowserMainParts::PreMainMessageLoopRunImpl [0x00007FF673B2F126+4442] (o:\chrome\browser\chrome_browser_main.cc:1664)
	ChromeBrowserMainParts::PreMainMessageLoopRun [0x00007FF673B2DF05+65] (o:\chrome\browser\chrome_browser_main.cc:1033)
	content::BrowserMainLoop::PreMainMessageLoopRun [0x00007FF672089943+73] (o:\content\browser\browser_main_loop.cc:991)
	content::StartupTaskRunner::RunAllTasksNow [0x00007FF67242BE1F+61] (o:\content\browser\startup_task_runner.cc:41)
	content::BrowserMainLoop::CreateStartupTasks [0x00007FF6720886AC+594] (o:\content\browser\browser_main_loop.cc:905)
	content::BrowserMainRunnerImpl::Initialize [0x00007FF67208B38A+126] (o:\content\browser\browser_main_runner_impl.cc:130)
	content::BrowserMain [0x00007FF672086E9D+161] (o:\content\browser\browser_main.cc:43)
	content::RunBrowserProcessMain [0x00007FF6729DADC5+89] (o:\content\app\content_main_runner_impl.cc:521)
	content::ContentMainRunnerImpl::RunServiceManager [0x00007FF6729DBA61+849] (o:\content\app\content_main_runner_impl.cc:1008)
	content::ContentMainRunnerImpl::Run [0x00007FF6729DB6E2+330] (o:\content\app\content_main_runner_impl.cc:886)
	content::RunContentProcess [0x00007FF6729DA561+805] (o:\content\app\content_main.cc:372)
	content::ContentMain [0x00007FF6729DA8DE+61] (o:\content\app\content_main.cc:398)
	content::BrowserTestBase::SetUp [0x00007FF673CD8452+1772] (o:\content\public\test\browser_test_base.cc:605)
	InProcessBrowserTest::SetUp [0x00007FF673A1EFA6+398] (o:\chrome\test\base\in_process_browser_test.cc:347)

[20276:19520:1109/002727.767:WARNING:pref_notifier_impl.cc(40)] Pref observer for media_router.cast_allow_all_ips found at shutdown.
[  FAILED  ] PrivateNetworkRequestBrowserTest.RecordsAddressSpaceFeatureForFetch, where TypeParam =  and GetParam() =  (5267 ms)


Original change's description:
> [CORS-RFC1918] Selectively re-enable broken test.
>
> This change enables the test except when a conflicting feature is
> enabled. It improves on the status quo (test disabled everywhere) until
> the underlying failure can be fixed, letting the test run on all CI bots
> except for the offending Network Service bot.
>
> Bug: chromium:1142865
> Change-Id: I4bb870d04c6b35961c1c32d9d3549d03afeaa3f3
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2519693
> Auto-Submit: Titouan Rigoudy <titouan@chromium.org>
> Reviewed-by: Matt Menke <mmenke@chromium.org>
> Commit-Queue: Titouan Rigoudy <titouan@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#824400}

TBR=mmenke@chromium.org,titouan@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: chromium:1142865
Change-Id: I65320686b457fcbe21211c0091abf9218a728b31
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2528123
Reviewed-by: Mark Pearson <mpearson@chromium.org>
Reviewed-by: Matt Menke <mmenke@chromium.org>
Commit-Queue: Matt Menke <mmenke@chromium.org>
Cr-Commit-Position: refs/heads/master@{#825519}