Revert "Refactor resource creating for overlay unit tests into a utility class"
This reverts commit 8b0850ef9c6e55abe7a3076c268414d412fd1e5b.

Reason for revert: Likely causing ToT compile errors.

https://ci.chromium.org/ui/p/chromium/builders/ci/linux-cast-x64-rel/8665/overview

../../components/viz/service/display/overlay_unittest.cc:4135:3: error: no matching function for call to 'CreateOpaqueQuadAt'
 4135 |   CreateOpaqueQuadAt(resource_provider(), pass->shared_quad_state_list.back(),

Original change's description:
> Refactor resource creating for overlay unit tests into a utility class
>
> Bug: b:390503465
> Change-Id: I93975924125d4d1a25c905cabafedc0c134fe84e
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6183431
> Reviewed-by: Peter McNeeley <petermcneeley@google.com>
> Commit-Queue: Zoraiz Naeem <zoraiznaeem@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1409890}

Bug: b:390503465
Change-Id: I6782059296e258d2520f26df2b9f944e51ffa9fb
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6192199
Auto-Submit: Erik Chen <erikchen@chromium.org>
Reviewed-by: Peter McNeeley <petermcneeley@google.com>
Commit-Queue: Peter McNeeley <petermcneeley@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1409909}