Revert "Android: Use prebuilt devil tools for most scripts"
This reverts commit d832d489463efe88c11130c35c8349df3261bcb8.

Reason for revert: "AttributeError: 'AvdArgs' object has no attribute 'use_local_devil_tools'"
https://ci.chromium.org/ui/p/chromium/builders/ci/android-nougat-x86-rel/4277/overview
https://chromium-swarm.appspot.com/task?id=61f77da6f79dd610

Original change's description:
> Android: Use prebuilt devil tools for most scripts
>
> It still uses chromium's copies of prebuilts, but no longer defaults
> to chromium's copy of tools that need to be built. Namely:
>   md5sum, forwarder, and dex_commands.jar
>
> The reason for using local copies of these is to be able to test
> changes to them. This coverage is maintained by still using them
> for non-component builds within gtests & instrumentation tests.
>
> The main motivation for this change is to fix a frequently
> occurring error where component builds of the tools do not get
> pushed properly to the devices, and then do not work. md5sum also
> runs faster when built in release mode, so it doesn't make sense
> to use a slow copy of it when building a debug version of chrome.
>
> This is the error output I (and others) see frequently:
>
> W    4.817s TimeoutThread-1-for-Install(FA6AK0304925)  Error calculating md5: (device: FA6AK0304925) shell command run via adb failed on the device:
>   command: a=/data/local/tmp/md5sum/md5sum_bin;! [[ $(ls -l $a) = *14076* ]]&&exit 2;export LD_LIBRARY_PATH=/data/local/tmp/md5sum;$a -gz H4sIADX5rWMC/63RMQ6DMAwF0BORVGxVxcDQqVKrSu2MTGIgIolDEoK4fRFXqAcv1vf7g6WGDBJCkIqcGIlGiwK8jmS0ONZJqCmSw2p+VPh09D7mu93d53Vd2kvbNLKHdFyE+Sb/plKwJncKeoul7mDNE/psFGSKvA1nipckP5hRoGdVNZZuNazkgKhLzUqmNRbcWcnC+/ANews7nugPZnbMzvICAAA=;
>   exit status: 1
>   output:
>   - CANNOT LINK EXECUTABLE "/data/local/tmp/md5sum/md5sum_bin": library "libabsl.cr.so" not found
>
> Bug: 1404180
> Change-Id: Ie93b1a28caca4adfc492726450324ea90b198adf
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4491904
> Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> Reviewed-by: Ben Pastene <bpastene@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1138561}

Bug: 1404180
Change-Id: I94d2aa0e50328afefe15a3d164432b14dc901a38
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4503307
Auto-Submit: Ben Pastene <bpastene@chromium.org>
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Owners-Override: Stephanie Kim <kimstephanie@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1138931}