Revert "[WebLayer] Initial bringup of ad blocking"
This reverts commit ecd22f2fd5f2811b82ae7c540b8c1e40b9e9ce4f.

Reason for revert: SubresourceFilterBrowserTest.DisallowedSubframeURLBlockedOnActivatedURL is flaky

Example failures on https://ci.chromium.org/p/chromium/builders/ci/Win%207%20Tests%20x64%20%281%29

https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8863356200301577856/+/steps/weblayer_browsertests/0/logs/Deterministic_failure:_SubresourceFilterBrowserTest.DisallowedSubframeURLBlockedOnActivatedURL__status_FAILURE_/0

../../weblayer/browser/subresource_filter_browsertest.cc(196): error: Value of: WasParsedScriptElementLoaded(web_contents->GetMainFrame())
  Actual: true
Expected: false

Original change's description:
> [WebLayer] Initial bringup of ad blocking
>
> This CL does the initial bringup of ad tagging and blocking
> functionality in WebLayer. To do so, we do the following:
> - Bring up an implementation of SubresourceFilterClient and attach it
>   to WebContents instances
> - Instantiate subresource filter navigation throttles on navigation
> - Instantiates and configures SubresourceFilterAgent instances in the
>   renderer
>
> The organization and code added is modeled after that in //chrome. We
> have left TODOs for significant pieces of functionality to be added
> in followups (e.g., showing of the infobar on Android). One thing to
> note is that ad tagging/blocking only triggers on Android in WebLayer,
> as it requires having a safe browsing database instance and WebLayer
> does not have one on platforms other than Android.
>
> This CL also adds browsertests of this initial functionality:
> - that the subresource filter activation state is computed on page loads
> - that ads are blocked on activated pages if they are flagged by the
>   ruleset
>
> Bug: 1116095
> Change-Id: I1db0136709014004c221bb0251551eaeac3538e3
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2526087
> Commit-Queue: Colin Blundell <blundell@chromium.org>
> Reviewed-by: Charlie Harrison <csharrison@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#827735}

TBR=blundell@chromium.org,csharrison@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 1116095
Change-Id: I4b8bbed57ed18666e2155dae7a25186803802267
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2545763
Reviewed-by: Marijn Kruisselbrink <mek@chromium.org>
Commit-Queue: Marijn Kruisselbrink <mek@chromium.org>
Cr-Commit-Position: refs/heads/master@{#828459}