Revert "histograms: adds histogram descriptions for inner-text/html"
This reverts commit 6542c312cda1330c389383cb7c0844442d9088c1.

Reason for revert: This appears to be causing build failures with the following message:

AssertionError: The --inputs is not in sync with the most updated list of xmls. Please update the inputs in components/metrics/generate_expired_histograms_array.gni.
  add: /b/s/w/ir/cache/builder/src/tools/metrics/histograms/metadata/content_extraction/histograms.xml

Please reland after fixing as noted above.


Original change's description:
> histograms: adds histogram descriptions for inner-text/html
>
> Bug: b:304353698
> Change-Id: Iced16ec0d64dd663651e4ce76082a483c5a974a2
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5024321
> Commit-Queue: Scott Violet <sky@chromium.org>
> Reviewed-by: Weilun Shi <sweilun@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1224344}

Bug: b:304353698
Change-Id: I8a7c08acd7e006bf86abe755e9a5c85ee328f32e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5029502
Auto-Submit: Michael Wilson <mjwilson@chromium.org>
Owners-Override: Michael Wilson <mjwilson@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Michael Wilson <mjwilson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1224352}