Linux: Fix build error with use_sysroot=false on Ubuntu 18.04
Fixes the following build error:

../../sandbox/linux/seccomp-bpf-helpers/syscall_parameters_restrictions.cc:265:51: error: use of undeclared identifier 'F_SEAL_FUTURE_WRITE'
      F_SEAL_SEAL | F_SEAL_GROW | F_SEAL_SHRINK | F_SEAL_FUTURE_WRITE;

The F_SEAL_FUTURE_WRITE flag was added for Android so it makes sense to move
the usage behind a platform check.

BUG=1299437

Change-Id: I18312d01115282b36fbf8ee7a5e088084171bafe
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3553575
Reviewed-by: Egor Pasko <pasko@chromium.org>
Reviewed-by: Robert Sesek <rsesek@chromium.org>
Commit-Queue: Marshall Greenblatt <marshall@chromium.org>
Cr-Commit-Position: refs/heads/main@{#987613}