[components/enterprise] Fix compilation on iOS
The target //components/enterprise/common:files_scan_data is an
empty static library on iOS which causes libtool to fail with
the following error:

  [183/68488] LIBTOOL-STATIC obj/compone...enterprise/common/libfiles_scan_data.a
  error: sdk/xcode_links/XcodeDefault.xctoolchain/usr/bin/libtool: no files specified

Since the target is empty and not used on iOS, only define it on
non-iOS platforms.

Bug: none
Change-Id: I24d5f0b3811fa31ad009218615bb1437385dcf11
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4009079
Commit-Queue: Sylvain Defresne <sdefresne@chromium.org>
Commit-Queue: Nicolas Ouellet-Payeur <nicolaso@chromium.org>
Auto-Submit: Sylvain Defresne <sdefresne@chromium.org>
Reviewed-by: Nicolas Ouellet-Payeur <nicolaso@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1068146}