Revert "[ChromeCart] Restore module visibility when cart-action happens"
This reverts commit 59efcef1ab235fd8658636a8d489d481ccc177ec.

Reason for revert: seems to have introduced a compile error. see https://ci.chromium.org/p/chromium/builders/ci/chromeos-amd64-generic-lacros-dbg/8720?blamelist=1#blamelist-tab

../../chrome/browser/cart/cart_service.cc:310:22: error: use of undeclared identifier 'IsRemoved'
  if ((IsHidden() || IsRemoved()) &&

Original change's description:
> [ChromeCart] Restore module visibility when cart-action happens
>
> Whenever a cart-related action happens (e.g. add a product to cart,
> visit cart, etc), we should restore the hidden status of the cart
> module.
>
> Bug: 1182495
> Change-Id: I0e97d1b6b5193e2ef4d47942fef0bfa103893900
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2721224
> Reviewed-by: Wei-Yin Chen (陳威尹) <wychen@chromium.org>
> Commit-Queue: Yue Zhang <yuezhanggg@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#858352}

Bug: 1182495
Change-Id: I2b9e81ba6733350daa22dd69c09ed1263c558d6a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2724933
Auto-Submit: Scott Violet <sky@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/master@{#858356}