IWYU: missing include for using std::vector in hash password manager.
Fix build breakage:
../../components/password_manager/core/browser/hash_password_manager.h:44:8: error: ‘vector’ in namespace ‘std’ does not name a template type
   44 |   std::vector<PasswordHashData> RetrieveAllPasswordHashes();
      |        ^~~~~~

Bug: 819294
Change-Id: I8c8a4ec3972eedb87a312c5ec56adf4a21b1b2a2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3041046
Commit-Queue: Vasilii Sukhanov <vasilii@chromium.org>
Reviewed-by: Vasilii Sukhanov <vasilii@chromium.org>
Cr-Commit-Position: refs/heads/master@{#904696}