GCC: template specialization should not be in non namespace scope in PaintOpWriter
Fix build error with GCC because of adding a template specialization
in PaintOpWriter class, instead of namespace level.

Error from compiler was:
    ../../cc/paint/paint_op_writer.h:102:13: error: explicit specialization in non-namespace scope ‘class cc::PaintOpWriter’
      102 |   template <>
          |             ^
    ../../cc/paint/paint_op_writer.h:103:20: error: template-id ‘SerializedSizeSimple<size_t>’ in declaration of primary template
      103 |   constexpr size_t SerializedSizeSimple<size_t>() {
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Bug: 819294
Change-Id: Id902b4ad64fb6b7890fa49bd881917e0ea419eba
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4239982
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Reviewed-by: Xianzhu Wang <wangxianzhu@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1104700}