IWYU: use of std::vector in card unmask code requires its include.
../../chrome/browser/ui/autofill/payments/card_unmask_authentication_selection_dialog_controller.h:42:22: error: ‘vector’ in namespace ‘std’ does not name a template type
   42 |   virtual const std::vector<CardUnmaskChallengeOption>& GetChallengeOptions()
      |                      ^~~~~~

Bug: 957519
Change-Id: I7ff37627a6eaabc2b86104d7ed7e5b1993dcc48a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3211751
Reviewed-by: Peter Boström <pbos@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#929444}