licenses.py: handle missing directories gracefully
Our tarball download script for Electron in openSUSE runs remove_bundled_libraries.py
and then removes empty directories in the end.

Since Electron 30 (Chromium 124) this has caused this error during build:

FAILED: gen/components/resources/about_credits.html
python3 ../../tools/licenses/licenses.py --target-os=linux --depfile gen/components/resources/about_credits.d credits gen/components/resources/about_credits.html
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/src/out/Release/../../tools/licenses/licenses.py", line 1445, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/abuild/rpmbuild/BUILD/src/out/Release/../../tools/licenses/licenses.py", line 1428, in main
    if not GenerateCredits(
           ^^^^^^^^^^^^^^^^
  File "/home/abuild/rpmbuild/BUILD/src/out/Release/../../tools/licenses/licenses.py", line 1069, in GenerateCredits
    directory_metadata, _ = ParseDir(path,
                            ^^^^^^^^^^^^^^
  File "/home/abuild/rpmbuild/BUILD/src/out/Release/../../tools/licenses/licenses.py", line 670, in ParseDir
    if not os.listdir(os.path.join(root, path)):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/abuild/rpmbuild/BUILD/src/third_party/angle/src/common/third_party/xxhash'

Change-Id: I3fe15b6b3e207e91e3eee5661a0f2b4edeacb880
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5591044
Auto-Submit: Bruno Pitrus <brunopitrus@hotmail.com>
Reviewed-by: Sam Maier <smaier@chromium.org>
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Sam Maier <smaier@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1311967}