Reland "SuperSize: Convert absolute object paths to $SYSTEM/..."
This reverts commit 5c3c8bd04071e0042bcbfff983ff012a7e4a70ee.

Reason for reland: Fixed /w test.

Original change's description:
> Revert "SuperSize: Convert absolute object paths to $SYSTEM/..."
>
> This reverts commit 9778bf5afac7f932f04e4ad6f69204f9e9ea9b79.
>
> Reason for revert: Breaking CQ
>
>  File "/b/s/w/ir/cache/builder/src/tools/binary_size/libsupersize/archive_util.py", line 62, in _NormalizeSourcePath
>     path = os.path.join(models.SYSTEM_PREFIX_PATH, os.path.basename(path))
> NameError: name 'models' is not defined
>
> Original change's description:
> > SuperSize: Convert absolute object paths to $SYSTEM/...
> >
> > And move this source_path transformation into NormalizePaths
> >
> > Bug: None
> > Change-Id: Iaf2c290df30dff9af722a6616e5a6d973d44a79b
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3627849
> > Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> > Reviewed-by: Samuel Huang <huangs@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#999721}
>
> Bug: None
> Change-Id: I008cc76947982abeb2a5bf47aa588529569ca87f
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3630738
> Auto-Submit: Andrew Grieve <agrieve@chromium.org>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#999931}

Bug: None
Change-Id: I450b735b3cbeeadfa984c909bd8cb2d39824416e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3632180
Auto-Submit: Andrew Grieve <agrieve@chromium.org>
Reviewed-by: Samuel Huang <huangs@chromium.org>
Commit-Queue: Samuel Huang <huangs@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1000405}