Revert "Refactor native BackgroundTaskScheduler to take TaskIds rather than ints"
This reverts commit 2dab51dde3c069fd4c30e00a99a9820bb28c2793.

Reason for revert: Failing android_compile_dbg trybot

../../components/metrics/reporting_service.cc:189:31: error: no matching constructor for initialization of 'background_task::TaskInfo'
  189 |     background_task::TaskInfo task_info(
      |                               ^
  190 |         static_cast<int>(background_upload_task_id_), one_off);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../components/background_task_scheduler/task_info.h:42:3: note: candidate constructor not viable: no known conversion from 'int' to 'TaskIds' for 1st argument
   42 |   TaskInfo(TaskIds task_id, const OneOffInfo& timing_info);
      |   ^        ~~~~~~~~~~~~~~~

Original change's description:
> Refactor native BackgroundTaskScheduler to take TaskIds rather than ints
>
> FWIU background tasks have to be listed in task_ids.h. So rather than
> having the exposed API taking in ints directly and having callers
> constantly cast TaskIds to ints, just accept TaskIds directly and cast
> to int internally.
>
> Context: https://chromium-review.googlesource.com/c/chromium/src/+/7486465/comment/7627fd76_43d73f01/
>
> Bug: 445735421
> Change-Id: I87578ce4662173bbf00ad86a7b460724521f34f2
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7516509
> Reviewed-by: Shakti Sahu <shaktisahu@chromium.org>
> Reviewed-by: Carlos Knippschild <carlosk@chromium.org>
> Commit-Queue: Luc Nguyen <lucnguyen@google.com>
> Cr-Commit-Position: refs/heads/main@{#1575529}

Bug: 445735421
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I21ea56e783c9c5b696032793df374936b5bc21f3
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7524726
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Carlos Knippschild <carlosk@chromium.org>
Reviewed-by: Shakti Sahu <shaktisahu@chromium.org>
Reviewed-by: Tommy Nyquist <nyquist@chromium.org>
Auto-Submit: Sky Malice <skym@chromium.org>
Commit-Queue: Tommy Nyquist <nyquist@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1575565}