Revert "[Floss] Init client bundle fake implementations"
This reverts commit 410e94360805c38239d51ce382f16b7d5416da5c.

Reason for revert: Compilation error
https://ci.chromium.org/ui/p/chromium/builders/ci/chromeos-arm-generic-dbg/68266/overview

```
[1369/1544] SOLINK ./libdevice_bluetooth.so
FAILED: libdevice_bluetooth.so libdevice_bluetooth.so.TOC
python3 "../../build/toolchain/gcc_solink_wrapper.py" --readelf="/b/s/w/ir/cache/builder/src/build/c...(too long)
ld.lld: error: undefined symbol: floss::FakeFlossManagerClient::FakeFlossManagerClient()
>>> referenced by unique_ptr.h:686 (../../buildtools/third_party/libc++/trunk/include/__memory/unique_ptr.h:686)
>>>               obj/device/bluetooth/bluetooth/floss_dbus_manager.o:(std::Cr::__unique_if<floss::FakeFlossManagerClient>::__unique_single std::Cr::make_unique[abi:v170000]<floss::FakeFlossManagerClient>())
```

Original change's description:
> [Floss] Init client bundle fake implementations
>
> Initialize fake client implementation when needed. Update unit tests to
> not use the stored pointer for client objects but to fetch through DBUS
> manager at run time, as client objects can be deleted and recreated
> throughout the test.
>
> BUG=b:266989920
> TEST=device_unittests
>
> Change-Id: I61b4efc1a6b930c51f269b648e595147e03f3e55
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4205864
> Commit-Queue: Michael Sun <michaelfsun@google.com>
> Reviewed-by: Reilly Grant <reillyg@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1099666}

Bug: b:266989920
Change-Id: Ia5d2f7177d2828c925342a7a79a9aef3e9149da2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4212008
Commit-Queue: Yoshifumi Inoue <yosin@google.com>
Owners-Override: Yoshifumi Inoue <yosin@google.com>
Auto-Submit: Yoshifumi Inoue <yosin@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1099670}