clang: Use Python 3.9-compatible API in sync_deps.py
file_digest is new in 3.11. Move off it, so that this script can
run on macOS 15 with system python.

Without this change, it would fail with

    AttributeError: module 'hashlib' has no attribute 'file_digest'

No behavior change.

Bug: none
Change-Id: If7311097382638762219ac4194baac5d4c756291
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7014109
Reviewed-by: Hans Wennborg <hans@chromium.org>
Commit-Queue: Hans Wennborg <hans@chromium.org>
Auto-Submit: Nico Weber <thakis@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1526139}