[MVT Customization] Make tile View caching robust against duplicate URL.
Consider two code sites:
1. TileGroup.loadTiles(): Suggested tiles are deduped by URL, presumably
   to fix Issue 40511776.
2. TileRender.renderTileSection(): Existing SuggestionsTileView
   instances stored in a cache, using SiteSuggestion as key, and
   reused for new suggestions with identical SiteSuggestion.

For MVT customization on Android, we plan to allow duplicate URLs
(i.e., get rid of (1) -- TBD) since:
* Preventing users from adding duplicate URL is extra burden.
* Later we may specify URL="" to represent "placeholder tiles".

An issue that arises is that without (1) then (2) can crash via:

  java.lang.IllegalStateException: The specified child already has a
  parent. You must call removeView() on the child's parent first.

It turns out that (1) merely masks the root cause of the crash in (2):
Cached tiles are placed in a HashMap, but on usage the tile is not
removed. So if two identical SiteSuggestion exist, then the same
SuggestionsTilewView instance gets added twice, triggering the
IllegalStateException.

This CL fixes the crash by making (2) more robust:
* When a cached SuggestionsTileView is reused, remove from cache.
* Implement cache using new class SuggestionsTileViewCache, which is
  effectively a HashMultimap (to accommodate duplicates) from
  SiteSuggestion to SuggestionsTileView, but takes up less space.

For testing:
* Update TileGroupUnitTest to call refreshData() a second time for
  multiple tests, so caching pathway gets used => Tests still pass.
* Disable (1) => testRenderTileViewWithDuplicatedUrl() crashes due
  to IllegalStateException.
* Apply fix to (2) => Tests now pass.
* Restore (1) => Tests still pass.

Bug: 388782412, 40511776
Change-Id: I4a879b49a62e0bb60ceccb5d8bffa864e838670e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6202421
Reviewed-by: Xi Han <hanxi@chromium.org>
Code-Coverage: findit-for-me@appspot.gserviceaccount.com <findit-for-me@appspot.gserviceaccount.com>
Commit-Queue: Samuel Huang <huangs@chromium.org>
Reviewed-by: Calder Kitagawa <ckitagawa@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1412107}