IWYU: returning unique_ptr of WebContentsViewDelegate require its declaration.
Fix build issue with libstdc++ version of std::unique_ptr, breaking
compilation of ContentBrowserClient converting from nullptr.

Fixes this compilation error:
    ../../content/public/browser/content_browser_client.cc:104:10:   required from here
    /usr/include/c++/11/bits/unique_ptr.h:83:23: error: invalid application of ‘sizeof’ to incomplete type ‘content::WebContentsViewDelegate’

Bug: 957519
Change-Id: Iebbd94866b8a1a5b3c2c5da3dadfbecff254d751
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3615914
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Reviewed-by: Alexander Timin <altimin@chromium.org>
Cr-Commit-Position: refs/heads/main@{#999342}