Revert "Add Breakpad comments and error to crash_key.h"
This reverts commit 92ae8e12a1b32c618df6778287a9315b05e1c499.

Reason for revert: FindIt advised this CL failed the build

Sample Failed Build: https://ci.chromium.org/b/8833969575978110897
Sample Failed Step: compile

obj/components/crash/core/common/zombies/objc_zombie.o
FAILED: obj/components/crash/core/common/zombies/objc_zombie.o
/opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -...(too long)
../../components/crash/core/common/objc_zombie.mm:198:3: error: use of undeclared identifier 'ignore_result'
ignore_result(HANDLE_EINTR(write(STDERR_FILENO, message, strlen(message))));
^
1 error generated.


Original change's description:
> Add Breakpad comments and error to crash_key.h
>
> This change adds comments to crash_key.h to advise about some
> Breakpad-specific quirks:
> * not being able to use GetCrashKeyValue(X) simply to retrieve an
>   oversized key (as it will have been split into X__1, X__2, etc.)
> * ResetCrashKeysForTesting() not working on Linux
>
> I think these additions will prevent future users of this file some
> confusion.
>
> Bug: 1041106
> Change-Id: I83ba5075ff97e88005393378a0dc0cad769c26a0
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3207294
> Commit-Queue: Jesse McKenna <jessemckenna@google.com>
> Reviewed-by: Robert Sesek <rsesek@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#929566}

Bug: 1041106
Change-Id: Ibe7bf80a2a8821a505ed08fe2586d4a62982b59c
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3213792
Commit-Queue: Noel Gordon <noel@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Noel Gordon <noel@chromium.org>
Auto-Submit: Noel Gordon <noel@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#929568}