Revert "[MIM][CCT] BrandingController checks sign-in prompt UI"
This reverts commit be6962f01855b73c87d05062ca2f07dc6ed007f2.

Reason for revert: compilation error

../../clank/java/src/org/chromium/chrome/browser/customtabs/ChromeCustomTabsConnection.java:758: error: method showSignedOutMessage in class MismatchNotificationController cannot be applied to given types;
            notificationController.showSignedOutMessage(context);
                                  ^
  required: Context,Callback<Integer>
  found:    Context
  reason: actual and formal argument lists differ in length
1 error

Original change's description:
> [MIM][CCT] BrandingController checks sign-in prompt UI
>
> BrandingController now takes into account the sign-in prompt UI
> together with branding UI to decide which to show.
>
> Low-Coverage-Reason: HARD_TO_TEST BRUC has low base coverage before this CL.
> Bug: crbug.com/369561656
> Change-Id: I7d4f65158c4783d1253d0f63e326a98120ded6b1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5913493
> Reviewed-by: Wenyu Fu <wenyufu@chromium.org>
> Reviewed-by: Samar Chehade-Lepleux <samarchehade@google.com>
> Commit-Queue: Jinsuk Kim <jinsukkim@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1372893}

Bug: crbug.com/369561656
Change-Id: Ia41626f2cb40186237f45e8ac95f9e87d9849a31
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5958690
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Lijin Shen <lazzzis@google.com>
Commit-Queue: Lijin Shen <lazzzis@google.com>
Cr-Commit-Position: refs/heads/main@{#1372939}