IWYU: uint32_t requires stdint.h include in printing PageRange.
Fix this error:
../../printing/page_range.h:20:3: error: ‘uint32_t’ does not name a type

Introduced in this commit:
https://chromium-review.googlesource.com/c/chromium/src/+/2351580

Bug: 951519
Change-Id: I0c86cfc5dc711b062021dd8661d27d6442e7d47d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2423909
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Reviewed-by: Lei Zhang <thestig@chromium.org>
Cr-Commit-Position: refs/heads/master@{#809758}