bookmarks: fix missing deps
https://ci.chromium.org/ui/p/chromium/builders/build/linux-chromeos-build-perf-ninja/4325/overview

ninja explain: recorded mtime of obj/chrome/browser/ui/bookmarks/impl/bookmark_context_menu_controller.o older than most recent input gen/components/saved_tab_groups/proto/saved_tab_group_data.pb.h (1729144268037727585 vs 1729144272559788385)

ukai@ukai ...src/chromium/src % gn clean out/cros
ukai@ukai ...src/chromium/src % siso ninja -C out/cros obj/chrome/browser/ui/bookmarks/impl/bookmark_context_menu_controller.o
depot_tools/siso.py: Using Siso binary from SISO_PATH: /usr/local/google/home/ukai/go/bin/siso.
ninja: Entering directory `out/cros'
 4.08s init credentials
reapi instance: projects/rbe-chrome-untrusted/instances/default_instance
 3.01s load siso config
11.56s Regenerating ninja files
 2.41s reloading
pre:0 local:2 remote:0 94.3/s cache:22.24%
FAILED: 69ac5cd1-5cc1-4ebf-9e61-73c0e736f3e1 "./obj/chrome/browser/ui/bookmarks/impl/bookmark_context_menu_controller.o" CXX obj/chrome/browser/ui/bookmarks/impl/bookmark_context_menu_controller.o
err: exit=1
"python3" ../../build/toolchain/clang_code_coverage_wrapper.py -  ...(too long)
Use '--verbose_failures' to see the command lines
stderr:
In file included from ../../chrome/browser/ui/bookmarks/bookmark_context_menu_controller.cc:28:
In file included from ../../chrome/browser/ui/tabs/saved_tab_groups/saved_tab_group_utils.h:11:
In file included from ../../chrome/browser/ui/tabs/saved_tab_groups/saved_tab_group_keyed_service.h:16:
../../components/saved_tab_groups/internal/saved_tab_group_sync_bridge.h:15:10: fatal error: 'components/saved_tab_groups/proto/saved_tab_group_data.pb.h' file not found
   15 | #include "components/saved_tab_groups/proto/saved_tab_group_data.pb.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
build failed: 1 steps failed: exit=1
local:2234 remote:5768 cache:1650 fallback:0 retry:0 skip:5670
reapi: ops: 18970(err:5768) / r:35413(err:0) 824.88MiB / w:34141(err:0) 1.72GiB
fs: ops: 532221(err:218927) / r:158866(err:0) 11.92GiB / w:31687(err:0) 887.80MiB
2m05.92s Build Failure: 9652 done 1 failed 0 remaining - 76.65/s
 1 steps failed: exit=1
see ./out/cros/siso_output for command line and output
 or ./out/cros/siso.INFO
use ./out/cros/siso_failed_commands.sh to re-run failed commands

add //components/saved_tab_groups/proto
in //chrome/browser:browser_public_dependencies

Bug: 354839582
Change-Id: I0d280b7484e5ddbb49dfc6eca83894e1a008716e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5937378
Reviewed-by: Peter Boström <pbos@chromium.org>
Reviewed-by: Hidehiko Abe <hidehiko@chromium.org>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Peter Boström <pbos@chromium.org>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1370292}