Revert "[Sync] Implement device re-registration"
This reverts commit 8973359edc279b501f538bde6e47467fd89edac3.

Reason for revert:
Breaks downsteam code because it changed an enum item name. 

https://ci.chromium.org/ui/p/chrome/builders/official/ios/7698/overview

[52059/67687] OBJCXX obj/ios_internal/chrome/browser/providers/signin/signin/chrome_trusted_vault_service_impl.o
FAILED: obj/ios_internal/chrome/browser/providers/signin/signin/chrome_trusted_vault_service_impl.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/ios_internal/chrome/browser/pr...(too long)
../../ios_internal/chrome/browser/providers/signin/chrome_trusted_vault_service_impl.mm:43:11: error: no member named 'kAlreadyRegistered' in 'syncer::TrustedVaultDeviceRegistrationStateForUMA'
kAlreadyRegistered;

Original change's description:
> [Sync] Implement device re-registration
>
> This CL adds logic to send device registration request one more time,
> even if device is already registered. Device key is reused and for the
> most users it should end up in receiving already exists response.
>
> Once re-registration is completed successfully, this logic won't be
> triggered anymore. If first registration happen after this CL,
> re-registration won't be triggered as well.
>
> (cherry picked from commit 6d519778c60dca6214ed0c5a39a8073d1e64a3e7)
>
> Bug: 1341264
> Change-Id: I453a57008a17a25e17755a9d1f2b11514c079d0f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3751139
> Commit-Queue: Maksim Moskvitin <mmoskvitin@google.com>
> Reviewed-by: Rushan Suleymanov <rushans@google.com>
> Reviewed-by: Mikel Astiz <mastiz@chromium.org>
> Cr-Original-Commit-Position: refs/heads/main@{#1024803}
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3771881
> Commit-Queue: Rushan Suleymanov <rushans@google.com>
> Auto-Submit: Maksim Moskvitin <mmoskvitin@google.com>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Cr-Commit-Position: refs/branch-heads/5112@{#1031}
> Cr-Branched-From: b13d3fe7b3c47a56354ef54b221008afa754412e-refs/heads/main@{#1012729}

Bug: 1341264
Change-Id: I25672cf44fa4ca6285d16cacc64379ffc0bd9fbc
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3775674
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: edchin <edchin@google.com>
Owners-Override: edchin <edchin@google.com>
Cr-Commit-Position: refs/branch-heads/5112@{#1044}
Cr-Branched-From: b13d3fe7b3c47a56354ef54b221008afa754412e-refs/heads/main@{#1012729}