Revert "[Lacros] Add sublabel to "Clear Cookie On Exit" setting"
This reverts commit 157a72ae1e6f1eed74f5bf60132989a53c4960d2.

Reason for revert: Fails consistently on linux-lacros-rel bot

First failing build coincides with this change:
https://ci.chromium.org/ui/p/chromium/builders/ci/linux-lacros-tester-rel/26691/overview

Both CrSettingsCookiesPageTest.LacrosSecondaryProfile and CrSettingsCookiesPageTest.CookiesPageTest browsertests are failing.

The error message appears related:

AssertionError: expected '' to equal 'Signs you out of most sites. You won\'t be signed out of your Google Account.'
    at assertEquals (chrome://webui-test/chai_assert.js:54:15)
    at Context.<anonymous> (chrome://webui-test/settings/cookies_page_test.js:96:9)

Original change's description:
> [Lacros] Add sublabel to "Clear Cookie On Exit" setting
>
> The string is:
>
>   "Signs you out of most sites. You won't be signed out of your
>    Google Account."
>
> Screenshot:
> https://storage.cloud.google.com/chromium-translation-screenshots/14d766028b9f4509cb83ea8dc050c0afff0f0189
>
> Bug: 1104667
> Change-Id: I32eaf3313c4376a2a1008d334bf0a69364d4b6bf
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3666719
> Reviewed-by: Theodore Olsauskas-Warren <sauski@google.com>
> Reviewed-by: Rainhard Findling <rainhard@chromium.org>
> Commit-Queue: David Roger <droger@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1009543}

Bug: 1104667
Change-Id: I9a701d6df5cc2b76d496c815f78ab4ef0c6d4600
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3682781
Auto-Submit: Ian Clelland <iclelland@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Ian Clelland <iclelland@chromium.org>
Owners-Override: Ian Clelland <iclelland@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1009572}