Revert "[Xvfb] Increase client limit to 512 when possible"
This reverts commit 380b547d4d2163f6a384c4398921ea87a9fb6d61.

Reason for revert: broke webdriver_tests_suite (see https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8850120093761458880/+/steps/webdriver_tests_suite_on_Ubuntu-14.04/0/stdout?format=raw).

Traceback (most recent call last):
  File "../../testing/xvfb.py", line 460, in <module>
    sys.exit(main())
  File "../../testing/xvfb.py", line 456, in main
    return run_executable(sys.argv[1:], os.environ.copy())
  File "../../testing/xvfb.py", line 136, in run_executable
    return _run_with_xvfb(cmd, env, stdoutfile, use_openbox, use_xcompmgr)
  File "../../testing/xvfb.py", line 180, in _run_with_xvfb
    if '-maxclients' in xvfb_help:
TypeError: a bytes-like object is required, not 'str'


Original change's description:
> [Xvfb] Increase client limit to 512 when possible
>
> BUG=1187948
>
> Change-Id: Iece55f33ab319536df2de83b8aa1124544d1cbc0
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2822788
> Reviewed-by: Dirk Pranke <dpranke@google.com>
> Commit-Queue: Thomas Anderson <thomasanderson@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#871638}

Bug: 1187948
Change-Id: I4c4330ad51686f13cf85d710a7f5fa18d9b5647f
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2823158
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Andrey Kosyakov <caseq@chromium.org>
Reviewed-by: Thomas Anderson <thomasanderson@chromium.org>
Owners-Override: Andrey Kosyakov <caseq@chromium.org>
Commit-Queue: Thomas Anderson <thomasanderson@chromium.org>
Cr-Commit-Position: refs/heads/master@{#871745}