capture_mode: fix missing deps
https://ci.chromium.org/ui/p/chromium/builders/build/linux-chromeos-build-perf-ninja/4469/overview

build step: cxx "./obj/chrome/browser/ash/policy/dlp/dlp/dlp_content_manager_ash.o"
siso_rule: clang-cros/cxx
stderr:
In file included from ../../chrome/browser/ash/policy/dlp/dlp_content_manager_ash.cc:28:
../../chrome/browser/ui/ash/capture_mode/chrome_capture_mode_delegate.h:17:10: fatal error: 'services/screen_ai/public/mojom/screen_ai_service.mojom-forward.h' file not found
   17 | #include "services/screen_ai/public/mojom/screen_ai_service.mojom-forward.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

$ gn refs out/cros chrome/browser/ui/ash/capture_mode/chrome_capture_mode_delegate.h
//chrome/browser/ui/ash/capture_mode:capture_mode
$ gn refs out/cros out/cros/gen/services/screen_ai/public/mojom/screen_ai_service.mojom-forward.h
//services/screen_ai/public/mojom:mojom
//services/screen_ai/public/mojom:mojom__generator

so add //service/screen_ai/public/mojom:mojom
to //chrome/browser:browsre_public_dependencies for is_chromeos_ash.

Bug: 354839582
Change-Id: I449db500022e77347dea1855c160470b617bda41
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5960397
Commit-Queue: Erik Chen <erikchen@chromium.org>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Hidehiko Abe <hidehiko@chromium.org>
Reviewed-by: Erik Chen <erikchen@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1373685}