ozone/wayland: fix compilation of fuzzer.
../../ui/ozone/platform/wayland/fuzzer/wayland_buffer_fuzzer.cc:128:56: error: no matching member function for call to 'ConsumeIntegralInRange'
const uint32_t kFormat = known_fourccs[data_provider.ConsumeIntegralInRange(
~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~

Also removes libffi to fix the following error (libffi doesn't
look as required package for wayland-scanner as it compiles without
that package)

[52/4323] ACTION //third_party/wayland-protocols:keyboard_extension_protocol_gen(//build/toolchain/linux:clang_x86)

python ../../third_party/wayland/wayland_scanner_wrapper.py third_party/wayland-protocols/unstable/keyboard/keyboard-extension-unstable-v1.xml --src-root ../../ --root-gen-dir gen --cmd ./wayland_scanner
/home/msisov/code/chromium/src/out/fuz/wayland_scanner: error while loading shared libraries: libffi.so.6: cannot open shared object file: No such file or directory
wayland-scanner returned an error: 127

FAILED: gen/third_party/wayland-protocols/unstable/keyboard/keyboard-extension-unstable-v1-protocol.c gen/third_party/wayland-protocols/unstable/keyboard/keyboard-extension-unstable-v1-client-protocol.h gen/third_party/wayland-protocols/unstable/keyboard/keyboard-extension-unstable-v1-server-protocol.h
Change-Id: I25ca6d7a6e60a243e96398624a4c690b72054697
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2377717
Commit-Queue: Maksim Sisov (GMT+3) <msisov@igalia.com>
Commit-Queue: Thomas Anderson <thomasanderson@chromium.org>
Auto-Submit: Maksim Sisov (GMT+3) <msisov@igalia.com>
Reviewed-by: Thomas Anderson <thomasanderson@chromium.org>
Cr-Commit-Position: refs/heads/master@{#801877}