Revert "Roll ANGLE from 2997e3545ec6 to df90bbc50d98 (1 revision)"
This reverts commit 67a1f3be3e879e4edf9686814a869b983e810b62.

Reason for revert: Appears to cause compile failure on Linux MSAN:

https://ci.chromium.org/ui/p/chromium/builders/ci/Linux%20MSan%20Builder/73727/overview

../../third_party/angle/src/common/angleutils.h:433:44:
  error: use of undeclared identifier
    '__msan_scoped_disable_interceptor_checks'; did you mean
    'MsanScopedDisableInterceptorChecks'?

Original change's description:
> Roll ANGLE from 2997e3545ec6 to df90bbc50d98 (1 revision)
>
> https://chromium.googlesource.com/angle/angle.git/+log/2997e3545ec6..df90bbc50d98
>
> 2024-07-15 romanl@google.com Refactoring: move angle::HashMap and HashSet to own header
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/angle-chromium-autoroll
> Please CC angle-team@google.com,yuxinhu@google.com on the revert to ensure that a human
> is aware of the problem.
>
> To file a bug in ANGLE: https://bugs.chromium.org/p/angleproject/issues/entry
> To file a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/entry
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://issues.skia.org/issues/new?component=1389291&template=1850622
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md
>
> Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:win_optional_gpu_tests_rel;luci.chromium.try:linux-swangle-try-x64;luci.chromium.try:win-swangle-try-x86
> Bug: None
> Tbr: yuxinhu@google.com
> Change-Id: I2cf0947a12200bb8962effa421516f3bf1b79a60
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5705943
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1327329}

Bug: None
Change-Id: Iaee9963fc7c8b84d33382b4daa189c1a5107a219
Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:win_optional_gpu_tests_rel;luci.chromium.try:linux-swangle-try-x64;luci.chromium.try:win-swangle-try-x86
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5706150
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Tim Sergeant <tsergeant@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1327333}