NewTabPage: Fix TS error surfaced with upcoming TypeScript v6.
The next version of TS throws the following error in
background_image.ts.
"error TS6133: 'onImageLoad' is declared but its value is never read."

Moreover, there was already an ESLint suppression for the same issue.
"// eslint-disable-next-line @typescript-eslint/no-unused-vars"

Both can be addressed by using addEventListener() instead of an inline
`onload=` attribute.

Bug: 423789047
Change-Id: I72fc42cc9d096816f98a345ab0d8c9a97ce70186
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7261483
Reviewed-by: Riley Tatum <rtatum@google.com>
Commit-Queue: Riley Tatum <rtatum@google.com>
Auto-Submit: Demetrios Papadopoulos <dpapad@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1559079}