macOS Signing Scripts: Fix AttributeError object has no attribute '_notarization_tool'
(cherry picked from commit 34c71b1be17b323a50ebd0cdba1939c813e76e53)

Bug: 1450140, 1442256
Change-Id: I84dafc7229e7d907c94e6943322c3dae65a10f6e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4576145
Commit-Queue: Robert Sesek <rsesek@chromium.org>
Reviewed-by: Joshua Pawlicki <waffles@chromium.org>
Auto-Submit: Robert Sesek <rsesek@chromium.org>
Commit-Queue: Joshua Pawlicki <waffles@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1151184}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4576615
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Srinivas Sista <srinivassista@chromium.org>
Owners-Override: Srinivas Sista <srinivassista@chromium.org>
Cr-Commit-Position: refs/branch-heads/5803@{#3}
Cr-Branched-From: 9dc84e5c095e80c3a6f3a1186c09244c28497ec2-refs/heads/main@{#1150927}