media/gpu/v4l2/test: Fix Chromium style error
When building for Linux, compiler complains:
media/gpu/v4l2/test/video_decoder.cc:24:3: error: [chromium-style] auto variable type must not deduce to a raw pointer type.
  const auto kSrcLimit = src + stride * size.height();
  ^~~~~~~~~~
  auto* const

Fix this as suggested.

While at it, also mark the type as const, since the code doesn't
dereference the pointer to modify the contents. Actually, the code
never dereferences the pointer at all.

Bug: b:261157120
TEST=Build v4l2_stateless_decoder with use_v4l2_codecs=true for Linux

Change-Id: I348db2929562d35cbb621f78e452b15328b20bb2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4113216
Commit-Queue: Chen-Yu Tsai <wenst@chromium.org>
Reviewed-by: Steve Cho <stevecho@chromium.org>
Auto-Submit: Chen-Yu Tsai <wenst@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1087486}