Cleanup third_party/mako/*.pyc
After crrev.com/c/3686969 landed some developers reported failures of
this form:

     File "/usr/lib/python3.9/inspect.py", line 35, in <module>
       import ast
   ImportError: bad magic number in 'ast': b'\x03\xf3\r\n'

Deleting the .pyc files in third_party/mako resolved the issue, hence
adding this directory to the cleanup list. Maybe we should be deleting
all .pyc files?

This was tested locally to confirm that it deletes .pyc files from the
mako directory that were not deleted without it.

Change-Id: Ia79ff8b2ddc754fe1d46322626bf20a09bd904e6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3687577
Reviewed-by: Andrey Kosyakov <caseq@chromium.org>
Reviewed-by: Gang Wu <gangwu@chromium.org>
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Auto-Submit: Bruce Dawson <brucedawson@chromium.org>
Commit-Queue: Andrey Kosyakov <caseq@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1010216}