IWYU: Add missing include for uint64_t usage in limited_layer_entropy_cost_tracker.h
In the CL https://crrev.com/c/5934754 used uint64_t in the
components/variations/limited_layer_entropy_cost_tracker.h,
but required include was missed.
Added missing include for uint64_t usage.

Without it build failed when libstdc++ is used:
../../components/variations/limited_layer_entropy_cost_tracker.h:64:20:
error: 'uint64_t' does not name a type

Bug: 41455655
Change-Id: Ib7eccd2ce36dc3af92dad1195ba2d7eaceeb983e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6028950
Reviewed-by: Sylvain Defresne <sdefresne@chromium.org>
Reviewed-by: Ted Choc <tedchoc@chromium.org>
Commit-Queue: Ivan Murashov <ivan.murashov@lge.com>
Cr-Commit-Position: refs/heads/main@{#1384542}