Fix exception in web test driver when output contains sanitizer errors
Fixes the below exception.  This may have regressed after the
python3 migration.

TypeError raised: can only concatenate str (not "bytearray") to str
Traceback (most recent call last):
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/web_tests/run_web_tests.py", line 74, in main
    return run(port, options, args, printer).exit_code
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/web_tests/run_web_tests.py", line 776, in run
    run_details = manager.run(args)
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/web_tests/controllers/manager.py", line 186, in run
    run_results = self._run_test_once(tests_to_run, tests_to_skip,
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/web_tests/controllers/manager.py", line 282, in _run_test_once
    initial_results = self._run_tests(
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/web_tests/controllers/manager.py", line 480, in _run_tests
    return self._runner.run_tests(self._expectations, test_inputs,
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/web_tests/controllers/web_test_runner.py", line 140, in run_tests
    pool.run(('test_list', shard.name, shard.test_inputs,
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/common/message_pool.py", line 105, in run
    self.wait()
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/common/message_pool.py", line 137, in wait
    self._workers[0].run()
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/common/message_pool.py", line 282, in run
    self._raise(sys.exc_info())
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/common/message_pool.py", line 311, in _raise
    six.reraise(exception_type, exception_value, exception_traceback)
  File "/usr/local/google/home/thomasanderson/.vpython-root/57af22/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/common/message_pool.py", line 269, in run
    worker.handle(message.name, message.src, *message.args)
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/web_tests/controllers/web_test_runner.py", line 306, in handle
    device_failed = self._run_test(test_input, test_list_name,
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/web_tests/controllers/web_test_runner.py", line 335, in _run_test
    result = single_test_runner.run_single_test(
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/web_tests/controllers/single_test_runner.py", line 47, in run_single_test
    test_result = runner.run()
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/web_tests/controllers/single_test_runner.py", line 113, in run
    return self._run_crash_test()
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/web_tests/controllers/single_test_runner.py", line 125, in _run_crash_test
    driver_output = self._driver.run_test(self._driver_input())
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/web_tests/port/driver.py", line 236, in run_test
    return self._run_one_input(driver_input, start_time)
  File "/usr/local/google/home/thomasanderson/dev/chromium_1/src/third_party/blink/tools/blinkpy/web_tests/port/driver.py", line 262, in _run_one_input
    self.error_from_test = 'OUTPUT CONTAINS "sanitizer",' + \
TypeError: can only concatenate str (not "bytearray") to str

Bug: None
Change-Id: Id455058b27d5e679998f557b6dbe2dfea1e5254a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3938850
Auto-Submit: Thomas Anderson <thomasanderson@chromium.org>
Reviewed-by: Kent Tamura <tkent@chromium.org>
Commit-Queue: Kent Tamura <tkent@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1057219}