Reland "Create rpc client for kombucha test data seeding for supervised_users."
This reverts commit 9f9761f980aed41dc0bed5040be995cbb44ef740.

Reason for revert: Relanding change

Original change's description:
> Revert "Create rpc client for kombucha test data seeding for supervised_users."
>
> This reverts commit dca9a8bb4114038570a8dc9e427b9ecb6876032c.
>
> Reason for revert: Broke mac arm64 build https://ci.chromium.org/ui/p/chromium/builders/ci/mac-arm64-dbg/12973/overview
>
> [404/419] CXX obj/chrome/test/browser_tests/family_live_test.o
> FAILED: obj/chrome/test/browser_tests/family_live_test.o
> ../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
> In file included from ../../chrome/test/supervised_user/family_live_test.cc:5:
> In file included from ../../chrome/test/supervised_user/family_live_test.h:18:
> ../../chrome/test/interaction/interactive_browser_test.h:375:9: error: call to deleted constructor of 'supervised_user::FamilyLiveTest'
> 375 |       : T(std::forward<Args>(args)...) {}
>
> Original change's description:
> > Create rpc client for kombucha test data seeding for supervised_users.
> >
> > Adds a StateObserver class that can issue rpc that seeds data for
> > supervised user end-to-end tests.
> >
> > Change-Id: I390146b728072115153e2360678ada460b567b94
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5140287
> > Reviewed-by: Dana Fried <dfried@chromium.org>
> > Reviewed-by: James Lee <ljjlee@google.com>
> > Commit-Queue: Tomek Jurkiewicz <tju@google.com>
> > Cr-Commit-Position: refs/heads/main@{#1259089}
>
> Change-Id: I179a9de96f9920911ff6d574a7558bdffb5fde11
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5282369
> Owners-Override: Jeroen Dhollander <jeroendh@google.com>
> Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Commit-Queue: Tomek Jurkiewicz <tju@google.com>
> Auto-Submit: Jeroen Dhollander <jeroendh@google.com>
> Reviewed-by: Tomek Jurkiewicz <tju@google.com>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1259092}

Change-Id: I70e641af8d19736017b6007fc71a427bb69db2ee
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5285674
Reviewed-by: James Lee <ljjlee@google.com>
Commit-Queue: Tomek Jurkiewicz <tju@google.com>
Cr-Commit-Position: refs/heads/main@{#1259164}