Update call to print() in build/android/adb_gdb to work for python3
Prior to this change, running the build/android/adb_gdb script would throw an
error on developer environments that use python3 as the default. This change
drops support for python2 by explicitly calling python3.

The error output was:

```
All subsequent output is from adb_gdb script.
  File "<string>", line 1
    from pylib.constants import ANDROID_NDK_ROOT; print ANDROID_NDK_R...
                                                  ^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Missing parentheses in call to 'print'. Did you mean
  print(...)?
```

Change-Id: Ic50270341e7101854aa35bcbd614c3abd2d60442
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3857629
Reviewed-by: Peter Wen <wnwen@chromium.org>
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Javier Castro <jacastro@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1040624}