Revert "Create keyboard shortcut to toggle bookmark bar."
This reverts commit 30fc61f205c689a627b912977d874d5477efd781.

Reason for revert: Tree-closing compilation error:
https://ci.chromium.org/ui/p/chromium/builders/ci/android-12l-x64-rel-cq/12183/overview

../../chrome/android/javatests/src/org/chromium/chrome/browser/bookmarks/bar/BookmarkBarTest.java:240: error: cannot find symbol
        final var activity = sActivityTestRule.getActivity();
                             ^
  symbol:   variable sActivityTestRule
  location: class BookmarkBarTest
../../chrome/android/javatests/src/org/chromium/chrome/browser/bookmarks/bar/BookmarkBarTest.java:241: error: cannot find symbol
        final var profile = sActivityTestRule.getProfile(/* incognito= */ false);
                            ^
  symbol:   variable sActivityTestRule
  location: class BookmarkBarTest

Original change's description:
> Create keyboard shortcut to toggle bookmark bar.
>
> This CL creates a keyboard shortcut to toggle the bookmark bar. The
> keyboard shortcut updates the native preference that determines bookmark
> bar visibility. Note that bookmark bar visibility is not yet wired up
> to respect the native preference; that will be implemented in a follow
> up CL.
>
> Design: http://shortn/_ywmA9QscHQ
>
> NO_IFTTT=N/A
>
> Bug: 397468253
> Change-Id: If75474e61176cdcae4faa56354afb392e541ed25
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6349960
> Reviewed-by: Theresa Sullivan <twellington@chromium.org>
> Reviewed-by: Mark Schillaci <mschillaci@google.com>
> Commit-Queue: David Black <dmblack@google.com>
> Cr-Commit-Position: refs/heads/main@{#1437029}

Bug: 397468253
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Ia5f00db002e2c415872a4c1e07a2c382a335436f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6387006
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: David Baron <dbaron@chromium.org>
Owners-Override: David Baron <dbaron@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1437045}