Revert "[Android] Move and modularize android/banners."
This reverts commit 4fd275d3b7409d98d6942deeb9beb384b079354b.

Reason for revert: 

Breaks the internal build:

../../clank/java/src/com/google/android/apps/chrome/banner/PhoneskyDetailsDelegate.java:27: error: symbol not found org.chromium.chrome.browser.banners.AppDetailsDelegate
import org.chromium.chrome.browser.banners.AppDetailsDelegate;
       ^
../../clank/java/src/com/google/android/apps/chrome/banner/PhoneskyDetailsDelegate.java:42: error: could not resolve AppDetailsDelegate
public class PhoneskyDetailsDelegate extends AppDetailsDelegate
                                             ^
../../clank/java/src/com/google/android/apps/chrome/banner/PhoneskyDetailsDelegate.java:71: error: could not resolve Observer
            Observer observer, String url, String packageName, String referrer, int iconSize) {
            ^
../../clank/java/src/com/google/android/apps/chrome/banner/PhoneskyDetailsDelegate.java:26: error: symbol not found org.chromium.chrome.browser.banners.AppData
import org.chromium.chrome.browser.banners.AppData;
       ^
../../clank/java/src/com/google/android/apps/chrome/banner/PhoneskyDetailsDelegate.java:83: error: could not resolve AppData
    private AsyncTask<AppData> createRetrievalTask(final Observer observer, final String url,
                      ^
../../clank/java/src/com/google/android/apps/chrome/banner/PhoneskyDetailsDelegate.java:83: error: could not resolve Observer
    private AsyncTask<AppData> createRetrievalTask(final Observer observer, final String url,
                                                         ^
../../clank/java/src/com/google/android/apps/chrome/banner/PhoneskyDetailsDelegate.java:123: error: could not resolve AppData
    private AppData parseAndVerifyAppBundle(
            ^
../../clank/java/src/com/google/android/apps/chrome/banner/PhoneskyDetailsDelegate.java:53: error: could not resolve AppData
    private final LinkedList<AsyncTask<AppData>> mQueuedRequests;
                                       ^
../../clank/java/src/org/chromium/chrome/browser/AppHooksImpl.java:39: error: symbol not found org.chromium.chrome.browser.banners.AppDetailsDelegate
import org.chromium.chrome.browser.banners.AppDetailsDelegate;
       ^
../../clank/java/src/org/chromium/chrome/browser/AppHooksImpl.java:92: error: could not resolve AppDetailsDelegate
    public AppDetailsDelegate createAppDetailsDelegate() {
           ^



Original change's description:
> [Android] Move and modularize android/banners.
>
> This CL moves AppBanner* code from:
>   chrome/android/banners
> ... to ...
>   chrome/browser/banners/android
> ... and modularizes it in the process.
>
> Bug: 1135551
> Change-Id: I8773b293e55f03ca66da15551e27a06e26e2ae96
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2489917
> Commit-Queue: Finnur Thorarinsson <finnur@chromium.org>
> Reviewed-by: Tommy Nyquist <nyquist@chromium.org>
> Reviewed-by: David Trainor <dtrainor@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#821646}

TBR=nyquist@chromium.org,finnur@chromium.org,dtrainor@chromium.org

Change-Id: Ib1570bc83be4716cabf67bc71b3d4e723333bffa
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1135551
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2503952
Reviewed-by: Finnur Thorarinsson <finnur@chromium.org>
Commit-Queue: Finnur Thorarinsson <finnur@chromium.org>
Cr-Commit-Position: refs/heads/master@{#821667}