blink: Fix v8_compile_hints_producer.h compile error
Follow up of http://crrev.com/c/5977022.

Including "web_view_impl.h" in "scrollbar_theme.h" brings in new
deps. The new deps seem to be missing in build gn files. As a
result, compilation occasionally fails with
```
  v8_compile_hints_producer.h:8:10: fatal error:
  'third_party/blink/renderer/bindings/buildflags.h' file
```

This CL adds the missing deps exposed by the above CL.
`instrumentation_probes` -> `blink/renderer/bindings:buildflags`
And also uses forward declaration for `friend`.

Bug: b:367789464, 378381144
Change-Id: I7ed116f98231d02865ee03527edcaf1611233a39
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6013664
Reviewed-by: Dave Tapuska <dtapuska@chromium.org>
Commit-Queue: Xiyuan Xia <xiyuan@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1381964}