Fix IDL parsing failures on Windows
Running "git cl presubmit --all" revealed some strange
UnicodeDecodeError failures that only happened on Windows. They could
most easily be reproduced like this:

  git cl presubmit --files=chrome\common\extensions\api\*.idl

The failures looked like:

chrome\common\extensions\api\platform_keys.idl could not be parsed:
  File "tools\json_schema_compiler\idl_schema.py", line 613
    Main()
  File "tools\json_schema_compiler\idl_schema.py", line 609
    print(json.dumps(schema, indent=2))
..
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 62: invalid start byte

Investigation by rdevlin.cronin@ revealed that the problematic files all
contained non-ASCII characters - a non-breaking space and some fancy
apostrophes.

Replacing these non-ASCII characters with their close-enough ASCII
counterparts avoids the problem. To stop issues like this creeping in
in the future (a very real concern since the issue only manifested on
Windows) this change adds a check for non-ASCII characters to
idl_schema.py. Now the cryptic errors are reliably translated into
clear messages, like this:

chrome\common\extensions\api\wm_desks_private.idl could not be parsed: Traceback (most recent call last):
  File "c:\src\chromium3\src\tools\json_schema_compiler\idl_schema.py", line 617, in <module>
    Main()
  File "c:\src\chromium3\src\tools\json_schema_compiler\idl_schema.py", line 610, in Main
    raise Exception('Non-ascii character "%s" (ord %d) found at offset %d.' % (char, char_value, i))
Exception: Non-ascii character "’" (ord 146) found at offset 2447.

Bug: 1309977
Change-Id: Iaf6577456ff33edc711a91274d49761d7c8a7324
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3579801
Reviewed-by: Devlin Cronin <rdevlin.cronin@chromium.org>
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#992334}