Reland "Reland "[Clank CBCM] Adds more test cases to FirstRunIntegrationTest""
This reverts commit 8c4d783386a5100be1c6f80724a8dd5bedcd8744.

Reason for revert: New patch fixes broken tests

To make it easier to review, patch #1 is the original CL
(crrev.com/c/3174088). Compare the most recent patch with #1 to see
the diff. I also ran these tests 100 times on bots to increase our
confidence that the fix doesn't introduce flakiness or new regressions
(see results in crrev.com/c/3183400).

The error:
 - The original CL mocked libs (data saver, sign-in/sync, search
   engine) to make force promo pages to be skipped/shown
 - The approach however was fragile, since other checks that might
   happen on start-up (e.g. for the Chrome Feed) would not find expected
   functions to also be mocked, leading to errors

The solution:
 - The solution applied on this CL consists of faking functions in
   `FirstRunFlowSequencer`
 - I split part of the responsibilities into a new delegate class, which
   makes mocking less intrusive (for example, I don't need to change
   `FirstRunActivity` to inject the fake)
 - This seems to be less fragile to me, since future changes on
   unrelated features that affect start-up will be less likely to break
   these tests
 - Please notice that there is a lot of room for improvement in that
   approach, which will handled in follow-up CLs (crbug.com/1252903)

Bug: 1203435, 1251784, 1251578, 1251328
Fixed: 1251784, 1251578, 1251328

Original change's description:
> Revert "Reland "[Clank CBCM] Adds more test cases to FirstRunIntegrationTest""
>
> This reverts commit d82f992a4a65342ed040fc08b1198f300ee4ba15.
>
> Reason for revert: consistent failures, crbug.com/1251784
>
> Original change's description:
> > Reland "[Clank CBCM] Adds more test cases to FirstRunIntegrationTest"
> >
> > This reverts commit 3d6a4fe650d42a6bf2fe339d4722b4cb191d13e0.
> >
> > Reason for revert: The original CL was reverted during a tree closure investigation, but doesn't seem to be the one that caused it. Talked to the build sheriff, who confirmed relanding this should be safe.
> >
> > Original change's description:
> > > Revert "[Clank CBCM] Adds more test cases to FirstRunIntegrationTest"
> > >
> > > This reverts commit 5d05a6e07f060f4a71ee9a14f2a4f50cd8ecdd4d.
> > >
> > > Reason for revert:
> > > Error: Default interface methods are only supported starting with Android N (--min-api 24): Lorg/chromium/base/supplier/ObservableSupplier;hasValue()Z
> > >
> > > Original change's description:
> > > > [Clank CBCM] Adds more test cases to FirstRunIntegrationTest
> > > >
> > > > This CL extends the test coverage of FirstRunIntegrationTest by
> > > > allowing tests with all promos enabled or disabled (today, only the
> > > > enabled cases for Data Saver and Sync promos are covered), and more
> > > > tests for onBackPressed during FRE.
> > > >
> > > > This refactoring is part of a larger goal to skip FRE promos disabled
> > > > by cloud policy when policies are received before a promo is shown.
> > > > A follow-up CL will change FirstRunActivity to react to changes in
> > > > preferences due to cloud policies being set after FR started, and
> > > > integration tests will need to cover more cases as well. Because of
> > > > that, I decided to send this CL separately to make review easier.
> > > >
> > > > Other than the additional tests, this CL also mock settings for
> > > > Sign-in/Sync enabled and Data Saver enabled in FirstRunIntegrationTest,
> > > > so we can test all the possible combinations.
> > > >
> > > > Tests for the new sign-in flow on FRE will be added later.
> > > >
> > > > Please notice that we preferred not to use parametrized tests because
> > > > not all tests on this file make sense to be run with multiple
> > > > configurations.
> > > >
> > > > Bug: 1203435
> > > > Change-Id: If2423e288f9f87e145aa99afece8ee5be99c7de2
> > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3081379
> > > > Commit-Queue: Jan Krcal <jkrcal@chromium.org>
> > > > Auto-Submit: Fabio Tirelo <ftirelo@chromium.org>
> > > > Reviewed-by: Jan Krcal <jkrcal@chromium.org>
> > > > Reviewed-by: Sky Malice <skym@chromium.org>
> > > > Reviewed-by: Wenyu Fu <wenyufu@chromium.org>
> > > > Cr-Commit-Position: refs/heads/main@{#922795}
> > >
> > > Bug: 1203435
> > > No-Presubmit: true
> > > No-Tree-Checks: true
> > > No-Try: true
> > > Change-Id: I3324f6f1de44c23933244b5a98126e2fd1f47690
> > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3171053
> > > Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > > Owners-Override: Swapnil Gupta <swapnilgupta@google.com>
> > > Auto-Submit: Swapnil Gupta <swapnilgupta@google.com>
> > > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > > Cr-Commit-Position: refs/heads/main@{#922853}
> >
> > Bug: 1203435
> > Change-Id: I1b4f129d4a50a3ad103b1049ccb74c74240d1582
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3170113
> > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > Reviewed-by: Swapnil Gupta <swapnilgupta@google.com>
> > Owners-Override: Swapnil Gupta <swapnilgupta@google.com>
> > Commit-Queue: Fabio Tirelo <ftirelo@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#922979}
>
> Bug: 1203435, 1251784
> Change-Id: I710105a79226dbfefb69f967309b4d787d18a872
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3174088
> Reviewed-by: Wenyu Fu <wenyufu@chromium.org>
> Commit-Queue: bttk <bttk@chromium.org>
> Owners-Override: bttk <bttk@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#923667}

Bug: 1203435, 1251784
Change-Id: I53e15d010725ea8e056aec6d5cf38194a74992f4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3182723
Commit-Queue: Fabio Tirelo <ftirelo@chromium.org>
Reviewed-by: Jan Krcal <jkrcal@chromium.org>
Reviewed-by: Wenyu Fu <wenyufu@chromium.org>
Cr-Commit-Position: refs/heads/main@{#926095}