Revert "[extensions] Remove ExtensionService::Enable/DisableExtension"
This reverts commit d6d5be97897f0bc930d8051cfba702b2c665011a.

Reason for revert: Build break: https://ci.chromium.org/ui/p/chromium/builders/ci/android-desktop-x64-compile-rel/27664/overview

../../chrome/browser/extensions/chrome_content_verifier_delegate.cc:271:9: error: redefinition of 'registrar'
  271 |   auto* registrar = ExtensionRegistrar::Get(context_);

Bug: 405411622
Original change's description:
> [extensions] Remove ExtensionService::Enable/DisableExtension
>
> Use ExtensionRegistrar version instead.
>
> Bug: 405411622
> Change-Id: Ibf36f4a81740f0b2fd4feea703fb05e0555f2609
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6496507
> Reviewed-by: David Bertoni <dbertoni@chromium.org>
> Commit-Queue: Achuith Bhandarkar <achuith@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1453052}

Bug: 405411622
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I9aff00a9135f96e25e214ff3fabeb07f8c88f859
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6497261
Auto-Submit: S Ganesh <ganesh@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Patti Lor <patricialor@chromium.org>
Owners-Override: Patti Lor <patricialor@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1453056}