Reland "media: Remove `supports_vp9_profile2` in CdmCapability"
This reverts commit 6ff4186f43ca46cbfde4afe5742edf0a068efd30.

Reason for revert: Reland with fix.

Original change's description:
> Revert "media: Remove `supports_vp9_profile2` in CdmCapability"
>
> This reverts commit a23a40cfeded4d5538da401fbcd6cceb8ff99595.
>
> Reason for revert: breaks build
> ../../chrome/common/chrome_content_client.cc:258:14: error: no member named 'supports_vp9_profile2' in 'content::CdmCapability'
>
>   capability.supports_vp9_profile2 = true;
>   ~~~~~~~~~~ ^
>
> Original change's description:
> > media: Remove `supports_vp9_profile2` in CdmCapability
> >
> > The `supports_vp9_profile2` field was added for backward compatibility
> > with older CDMs. Now the new CDM has been deployed since M79, and we
> > should be okay to drop this.
> >
> > Bug: 796725,899403
> > Test: Updated unittests
> > Change-Id: I83982913158f8a61556fa6f726b4fd752892b9b9
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2774437
> > Reviewed-by: John Rummell <jrummell@chromium.org>
> > Reviewed-by: Alex Moshchuk <alexmos@chromium.org>
> > Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> > Commit-Queue: Daniel Cheng <dcheng@chromium.org>
> > Auto-Submit: Xiaohan Wang <xhwang@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#865453}
>
> Bug: 796725
> Bug: 899403
> Change-Id: Ic460fa7ab185e7eac999cd8c3f445623d5559cb7
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2781213
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Commit-Queue: Joel Hockey <joelhockey@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#865511}

Bug: 796725
Bug: 899403
Change-Id: Ia5a5a8e01328ed79cc6c70386a9560a752af3e03
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2779887
Reviewed-by: Nico Weber <thakis@chromium.org>
Reviewed-by: John Rummell <jrummell@chromium.org>
Reviewed-by: Alex Moshchuk <alexmos@chromium.org>
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Commit-Queue: Xiaohan Wang <xhwang@chromium.org>
Cr-Commit-Position: refs/heads/master@{#865883}