Fix Chrome for Testing Windows legacy cleanup test regression
```
../../chrome/installer/setup/setup_util_unittest.cc(910,49): error: use
of undeclared identifier 'kBinariesClientsKeyPath' return
base::win::RegKey(HKEY_CURRENT_USER, kBinariesClientsKeyPath, ^

../../chrome/installer/setup/setup_util_unittest.cc(916,49): error: use
of undeclared identifier 'kCommandExecuteImplClsid' return
base::win::RegKey(HKEY_CURRENT_USER, kCommandExecuteImplClsid,
```

R=grt@chromium.org

Bug: 1336611
Change-Id: Ib35babe5eab82bdfe466ae1478e5ad4700dfbdf5
Follow-up-of: chromium:4102040
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4113423
Reviewed-by: Joshua Pawlicki <waffles@chromium.org>
Commit-Queue: Thiago Perrotta <tperrotta@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1084957}