SyncerError: Remove unused enum entries
Bug: 951350
Change-Id: I8d3885bce1a39f2c331166daf90cc38508aa0d02
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2470556
Reviewed-by: Rushan Suleymanov <rushans@google.com>
Commit-Queue: Marc Treib <treib@chromium.org>
Cr-Commit-Position: refs/heads/master@{#816933}