Fixed build with 'use_ozone = false'.
Chrome build would fail in a few places when use_ozone argument is set
to false.

Specifically:

1. Locally defined variables |locks| is not used if no platform and
   no Ozone are defined:
  ./../components/viz/service/display/skia_renderer.cc:2159:9:
  error: unused variable 'locks' [-Werror,-Wunused-variable]
  auto& locks = pending_overlay_locks_.back();

2. Base class defines IsSelectionBufferAvailable() only #ifdef USE_OZONE
  ../../ui/base/clipboard/clipboard_non_backed.h:100:43:
  error: only virtual member functions can be marked 'override'
  bool IsSelectionBufferAvailable() const override;

3. ui/base/clipboard/BUILD.gn includes clipboard_factory_ozone.cc,
   which refers to ClipboardNonBacked in line 53, however,
   clipboard_factory_ozone.cc is only included if use_ozone is in,
   effect see ui/base/clipboard/BUILD.gn:132.

Change-Id: I6a503647699da5039aa28778d722f5e8aa5e941d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2844777
Reviewed-by: Vasiliy Telezhnikov <vasilyt@chromium.org>
Reviewed-by: Darwin Huang <huangdarwin@chromium.org>
Reviewed-by: Maksim Sisov <msisov@igalia.com>
Commit-Queue: Peter Kvitek <kvitekp@chromium.org>
Cr-Commit-Position: refs/heads/master@{#875531}