Revert "[mparch] Support prerendering in DocumentServiceBase"
This reverts commit 83b797c0e7418a19513dae7fe27f87439154465a.

Reason for revert: Suspect causing compile failure on Cast Audio Linux.
First build failure: https://ci.chromium.org/ui/p/chromium/builders/ci/Cast%20Audio%20Linux/112223/overview

--
[1478/2012] CXX obj/content/test/content_browsertests/document_service_base_browsertest.o
FAILED: obj/content/test/content_browsertests/document_service_base_browsertest.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
../../content/browser/renderer_host/document_service_base_browsertest.cc:54:23: error: no member named 'SetUpOnMainThread' in 'content::test::PrerenderTestHelper'
prerender_helper_.SetUpOnMainThread(embedded_test_server());
~~~~~~~~~~~~~~~~~ ^
1 error generated.
---


Original change's description:
> [mparch] Support prerendering in DocumentServiceBase
>
> This CL replaces IsServedFromBackForwardCache() with
> IsPageActivation() to include the prerendering activation
> in the condition that keeps DocumentServiceBase.
>
> Bug: 1233870
> Change-Id: I3eb4302b085e5a0734296cd45929d79b7122644d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3056266
> Commit-Queue: Julie Kim <jkim@igalia.com>
> Reviewed-by: Kinuko Yasuda <kinuko@chromium.org>
> Reviewed-by: Alexander Timin <altimin@chromium.org>
> Reviewed-by: Lucas Gadani <lfg@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#908788}

Bug: 1233870
Change-Id: I3b07eca955d865b5413a6b464e343ec6e02e1456
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3073563
Auto-Submit: Takashi Sakamoto <tasak@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Matt Falkenhagen <falken@chromium.org>
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Reviewed-by: Matt Falkenhagen <falken@chromium.org>
Cr-Commit-Position: refs/heads/master@{#908792}