Fix memory leak caused by DelayAsyncScriptExecution
https://crrev.com/c/3841687 added a delay limit to
DelayAsyncScriptExecution. But it caused a memory leak.

The previous following code used WrapPersistent to wrap pending_script
but this was not correct. Persisting pending_script caused a memory
leak. So this CL wraps pending_script by WrapWeakPersistent.

```
task_runner_->PostDelayedTask(
    FROM_HERE,
    WTF::Bind(&ScriptRunner::RemoveDelayReasonFromScript,
              WrapWeakPersistent(this), WrapPersistent(pending_script),
              DelayReason::kMilestone),
    features::kDelayAsyncScriptExecutionLimitParam.Get());
```

[sample breakage]
- https://ci.chromium.org/ui/p/chromium/builders/ci/WebKit%20Linux%20Leak/42089/overview
- https://ci.chromium.org/p/chromium/builders/ci/WebKit%20Linux%20Leak

leak_detection_linux still fails with the following errors but this issue is tracked by https://crbug.com/1300277 separately.

```
py_utils.cloud_storage.PermissionError: Attempted to access a file from Cloud Storage but you don't have permission. To configure your credentials:
  1. Run "/b/s/w/ir/third_party/catapult/third_party/gsutil/gsutil config" and follow its instructions.
  2. If you have a @google.com account, use that account.
  3. For the project-id, just enter 0.
```

Bug: 1356276, 1340837
Change-Id: I74b0f2444c73b6e7d8ab3dd005002886dde17f7b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3862027
Reviewed-by: Hiroshige Hayashizaki <hiroshige@chromium.org>
Commit-Queue: Minoru Chikamune <chikamune@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1040649}