Implement a clang plugin for strict deps.
Strict deps is similar to bazel's layering check in that it's basically
"include what you use" but for build files (depend on what you include?).

See https://maskray.me/blog/2022-09-25-layering-check-with-clang

The clang plugin makes the error messages actionable by giving easy to understand
suggestions. Deciding what target to depend on is a nontrivial process
and is best left to the build system to decide.

`gn suggest` is a tool which does precisely this. It understands complex
things such as visibility, so it can suggest things such as groups when
it doesn't have visibility directly into a target.

An example error message output by the plugin is below:
```
build step: cxx "./obj/third_party/abseil-cpp/absl/log/internal/vlog_config/vlog_config.o"
stderr:
../../third_party/abseil-cpp/absl/log/internal/vlog_config.cc:39:10: error: module //third_party/abseil-cpp/absl/log/internal:vlog_config_Private does not depend on a module exporting 'absl/strings/string_view.h', which is part of indirectly used module //third_party/abseil-cpp/absl/strings:string_view
Suggestion: Run `gn suggest $OUT_DIR //third_party/abseil-cpp/absl/log/internal:vlog_config_Private=../../absl/strings/string_view.h`

   39 | #include "absl/strings/string_view.h"
      |          ^
1 error generated.
```

This suggestion is useful, as gn suggest will output:
Suggestion: Add deps = [ "//third_party/abseil-cpp/absl/strings:string_view" ] to :vlog_config (defined at //third_party/abseil-cpp/absl/log/internal/BUILD.gn:311)

Bug: 500845363
Link: https://chromium-review.googlesource.com/id/I11df5b365710f61433525d3a5ed82c656a6a6964
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7815161
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Commit-Queue: Matt Stark <msta@google.com>
Cr-Commit-Position: refs/heads/main@{#1633970}