Revert "Roll SwiftShader from 1d5174b9dc3b to 5b36fbc5ed2b (3 revisions)"
This reverts commit 8e9077156a6e9b0c5222de74536e146156b9e37a.

Reason for revert: Build failed on mac-arm64-rel bot.

https://ci.chromium.org/p/chromium/builders/ci/mac-arm64-rel/3537

../../third_party/swiftshader/third_party/marl/include/marl/pool.h:236:27: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.14 or newer
    MARL_NO_EXPORT inline ~Storage();
                          ^

Original change's description:
> Roll SwiftShader from 1d5174b9dc3b to 5b36fbc5ed2b (3 revisions)
>
> https://swiftshader.googlesource.com/SwiftShader.git/+log/1d5174b9dc3b..5b36fbc5ed2b
>
> 2021-01-21 capn@google.com Target macOS 10.12 when building LLVM
> 2021-01-21 capn@google.com Use aligned allocation for classes with aligned members
> 2021-01-21 nicolascapens@google.com Enable and require C++17 compilation
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/swiftshader-chromium-autoroll
> Please CC swiftshader-team+autoroll@google.com on the revert to ensure that a human
> is aware of the problem.
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/master/autoroll/README.md
>
> Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:linux_chromium_msan_rel_ng;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:win_optional_gpu_tests_rel;luci.chromium.try:linux-swangle-try-x64;luci.chromium.try:win-swangle-try-x86
> Bug: None
> Tbr: swiftshader-team+autoroll@google.com
> Change-Id: I986f61efb56c3c3ca18b0100ae6ca3dfee2fed7b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2643117
> Reviewed-by: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/master@{#845830}

TBR=chromium-autoroll@skia-public.iam.gserviceaccount.com,chromium-scoped@luci-project-accounts.iam.gserviceaccount.com,swiftshader-team+autoroll@google.com

Change-Id: I318bd80475234a7b9b7b5ef3d61602182f2f6dc8
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: None
Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:linux_chromium_msan_rel_ng;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:win_optional_gpu_tests_rel;luci.chromium.try:linux-swangle-try-x64;luci.chromium.try:win-swangle-try-x86
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2644401
Reviewed-by: Yoshifumi Inoue <yosin@chromium.org>
Commit-Queue: Yoshifumi Inoue <yosin@chromium.org>
Cr-Commit-Position: refs/heads/master@{#845948}