Revert "[Desktop Screenshots] Add untrusted JavaScript and Mojo."
This reverts commit 38e715e60699f9c26f47dbdb971ac746994c0488.

Reason for revert: suspect causing compile failure on chromeos-octopus-chrome, chromeos-betty-pi-arc-cfi-thin-lto-chrome, and "chromeos-eve-arc-r-chrome.
---
KeyError: 'Duplicate resource IDs: [23000, 23001, 23002, 23003]. This is likely because the reserved ID ranges defined in tools/gritsettings/resource_ids.spec have been exhausted.'
---

First build failure:
https://ci.chromium.org/ui/p/chrome/builders/ci/chromeos-octopus-chrome/4128/overview
https://ci.chromium.org/ui/p/chrome/builders/ci/chromeos-betty-pi-arc-cfi-thin-lto-chrome/32385/overview
https://ci.chromium.org/ui/p/chrome/builders/ci/chromeos-eve-arc-r-chrome/15890/overview

Original change's description:
> [Desktop Screenshots] Add untrusted JavaScript and Mojo.
>
> This CL builds the mojo and JS needed for executing IPC commands in the
> image editor code path.
>
> Bug: 1249227
> Change-Id: I36779aca6db6885676d50e79fcb13c63ea9d4016
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3350989
> Reviewed-by: Christopher Lam <calamity@chromium.org>
> Reviewed-by: Jiewei Qian <qjw@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Reviewed-by: Travis Skare <skare@chromium.org>
> Auto-Submit: Jeffrey Cohen <jeffreycohen@chromium.org>
> Commit-Queue: Jeffrey Cohen <jeffreycohen@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#970991}

Bug: 1249227
Change-Id: Ic7b90b427193f65c495ed2fd0421e93492b65852
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3462786
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Owners-Override: Takashi Sakamoto <tasak@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#971018}