Revert "Add browser portion of maldoca integration."
This reverts commit 47ca920ef48946ad68104194b400a4b2b583018e.

Reason for revert: suspect causing compile failure on Linux Builder (dbg)(32).

First build failure:
https://ci.chromium.org/ui/p/chromium/builders/ci/Linux%20Builder%20(dbg)(32)/185101/overview

Failure log:
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8836597939264914625/+/u/compile/stdout?format=raw
---
[6951/35612] CXX obj/third_party/maldoca/maldoca-ole/oss_utils.o
FAILED: obj/third_party/maldoca/maldoca-ole/oss_utils.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
../../third_party/maldoca/src/maldoca/ole/oss_utils.cc:435:27: error: no matching function for call to 'max'
out_str->resize(std::max(out_ptr - out_str->data(), 0l));
^~~~~~~~
../../buildtools/third_party/libc++/trunk/include/algorithm:2671:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('int' vs. 'long')
max(const _Tp& __a, const _Tp& __b)
^
---

Original change's description:
> Add browser portion of maldoca integration.
>
> Adding the browser code associated with leveraging the maldoca library
> as part of download protection.
>
> Bug: 1240382
> Change-Id: Icaf1f486cab41ef8321526332091559ce45272c5
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3097969
> Commit-Queue: Olabode O. Anise II <anise@chromium.org>
> Reviewed-by: Daniel Rubery <drubery@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#919609}

Bug: 1240382
Change-Id: I6d35a846fc7dcde51f9d8f93a73bd8580e0e9c56
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3149293
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Owners-Override: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/main@{#919614}