Handle flaky "file does not exist" errors during RmTree
This has happened at least once on Windows when calling rmtree() on the
llvm build directory.

```
  Building final compiler.

 Traceback (most recent call last):
    File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\shutil.py", line 616, in _rmtree_unsafe
      os.unlink(fullname)
  FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\b\\s\\w\\ir\\cache\\builder\\src\\third_party\\rust-toolchain-intermediate\\llvm-host-build\\runtimes\\runtimes-x86_64-pc-windows-msvc-bins\\compiler-rt\\lib\\sanitizer_common\\CMakeFiles\\RTSanitizerCommonLibcNoHooks.x86_64.dir\\sanitizer_stoptheworld_linux_libcdep.cpp.obj'
```

R=zequanwu@chromium.org

Bug: 1271215
Change-Id: I11c9097600157d9b22f87981423c19726c7c2cd6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4424969
Reviewed-by: Zequan Wu <zequanwu@google.com>
Commit-Queue: danakj <danakj@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1130095}