libstdc++: do not use const members on std::vector used in BackgroundTracingFieldTrial unit test
libstdc++ implementation of std::vector does not allow non-const
types as members.

Fixes build break with libstdc++:
    /usr/include/c++/11/bits/stl_vector.h: In instantiation of ‘class std::vector<const {anonymous}::SetupModeParams>’:
    ../../chrome/browser/tracing/background_tracing_field_trial_unittest.cc:73:44:   required from here
    /usr/include/c++/11/bits/stl_vector.h:401:66: error: static assertion failed: std::vector must have a non-const, non-volatile value_type
      401 |       static_assert(is_same<typename remove_cv<_Tp>::type, _Tp>::value,
          |                                                                  ^~~~~

Bug: 957519
Change-Id: I07a762feacea16a8e88b0b514881e69500c26601
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3377525
Reviewed-by: Stephen Nusko <nuskos@chromium.org>
Reviewed-by: José Dapena Paz <jdapena@igalia.com>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#957137}