Revert "Printing page JS to TS"
This reverts commit 56ba382c55142724630393e391c7277c9ae5d5ed.

Reason for revert: This CL is likly the cause of compile failure on   Linux Chromium OS ASan LSan Builder, link:https://ci.chromium.org/ui/p/chromium/builders/ci/Linux%20Chromium%20OS%20ASan%20LSan%20Builder/64868/overview
Relevant error message: [!] Error: Could not resolve './os_printing_page/cups_printer_shared_css.js' from gen/chrome/browser/resources/settings/chromeos/preprocessed/chromeos/lazy_load.js
Error: Could not resolve './os_printing_page/cups_printer_shared_css.js' from 

Original change's description:
> Printing page JS to TS
>
> Bug: 1315757
> Change-Id: Ia26ff0fbcf2b7892c98fe099d7c4c788f26a5c15
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3938524
> Reviewed-by: Michael Checo <michaelcheco@google.com>
> Reviewed-by: Wes Okuhara <wesokuhara@google.com>
> Commit-Queue: Owen Wiggins <owx@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1066823}

Bug: 1315757
Change-Id: I17d5f71722f6241dd863799051b3b6bf0f386b6b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3999461
Owners-Override: Maggie Cai <mxcai@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Maggie Cai <mxcai@chromium.org>
Commit-Queue: Maggie Cai <mxcai@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1066844}