Add missing lock.h include
Fixes the following error building on Windows with `use_custom_libcxx=false`:

../../base/debug/dump_without_crashing.cc(20,35): error: no member named 'Lock' in namespace 'base'

Change-Id: Ifbdae56ae152cdf70580f117da4fcdaa4c662a1a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3479396
Reviewed-by: Nico Weber <thakis@chromium.org>
Commit-Queue: Marshall Greenblatt <marshall@chromium.org>
Cr-Commit-Position: refs/heads/main@{#973856}