libstdc++: std::vector cannot have const members in AccountSelectionBubbleView.
Implementation of std::vector in libstdc++ does not allow const
members.

Fixes the compilation error:
    /usr/include/c++/11/bits/stl_vector.h: In instantiation of ‘class std::vector<const content::IdentityRequestAccount>’:
    ../../chrome/browser/ui/views/webid/account_selection_bubble_view.h:131:60:   required from here
    /usr/include/c++/11/bits/stl_vector.h:401:66: error: static assertion failed: std::vector must have a non-const, non-volatile value_type
      401 |       static_assert(is_same<typename remove_cv<_Tp>::type, _Tp>::value,
          |                                                                  ^~~~~

Bug: 957519
Change-Id: I5bd822243c77526a31db8f152de0326365705522
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3729260
Reviewed-by: Christian Biesinger <cbiesinger@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#1018688}