android: Fix base64 encoding errors in result_sink on py3.
As-is, this line runs into an error when ran on py3:
TypeError: a bytes-like object is required, not 'str'

The py3 version of base64 expects bytes rather than a string, so this
converts the log contents to bytes on py3 before passing it off to
base64 + converts the resulting bytes back into a string.

Note that this is a no-op on python2 since the native string on py2
is already bytes.

Bug: 1198282
Change-Id: Ide0ec6d3c9dc633551e6fa1044f844c5cb72bc3a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2863926
Reviewed-by: Mohamed Heikal <mheikal@chromium.org>
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Cr-Commit-Position: refs/heads/master@{#878102}