Revert "media/gpu/v4l2: Remove unused member from V4L2DecodeSurface"
This reverts commit aacbca5423b50f0aad7231ab4617c736e162d304.

Reason for revert: compilation failure in https://ci.chromium.org/ui/p/chromium/builders/ci/lacros-arm64-generic-rel/9681/overview :

FAILED: obj/media/gpu/v4l2/v4l2/v4l2_decode_surface.o
../../build/cros_cache/chrome-sdk/symlinks/arm64-generic+15113.0.0+target_toolchain/bin/aarch64-cros...(too long)
../../media/gpu/v4l2/v4l2_decode_surface.cc:96:50: error: format specifies type 'int' but the argument has type 'size_t' (aka 'unsigned long') [-Werror,-Wformat]
base::StringAppendF(&out, "Buffer %d -> %d. ", input_buffer_.BufferId(),
~~           ^~~~~~~~~~~~~~~~~~~~~~~~
%zu
1 error generated.

Original change's description:
> media/gpu/v4l2: Remove unused member from V4L2DecodeSurface
>
> This CL removes V4L2DecodeSurface::input_record_ because it's
> unused, except for a debug printout where an alternative exists.
>
> No new functionality.
>
> Bug: b:222774780
> Change-Id: I88dd138a07ffe522947d9acc211c259ae81011a6
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3979248
> Reviewed-by: Nathan Hebert <nhebert@chromium.org>
> Commit-Queue: Miguel Casas-Sanchez <mcasas@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1063450}

Bug: b:222774780
Change-Id: Ib0fb127cedd718775a00a9ea2dee2fa28cafca0a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3978872
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: David Baron <dbaron@chromium.org>
Owners-Override: David Baron <dbaron@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1063466}