Revert "Roll Speedometer from f866d2b07703 to a6d7f0ae29c9 (1 revision)"
This reverts commit 92abde5c1ee707df4c90565c92eb6fd15c266221.

Reason for revert: Looks like this broke the sync of third_party/speedometer/main (gclient sync).

Failure Link:
src/third_party/speedometer/main (ERROR)
----------------------------------------
[0:00:02] Started.[0:00:02] Finished running: git rev-list -n 1 HEAD
[0:00:02] Finished running: git rev-parse --abbrev-ref=strict HEADerror: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:00:04] fatal: expected 'acknowledgments'
[0:00:07] error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:00:07] fatal: expected 'acknowledgments'
----------------------------------------
Error: Command 'git -c core.deltaBaseCacheLimit=2g fetch origin a6d7f0ae29c93e7efbc42520d0104ba4bcc95207 --no-tags' returned non-zero exit status 128

Original change's description:
> Roll Speedometer from f866d2b07703 to a6d7f0ae29c9 (1 revision)
>
> https://chromium.googlesource.com/external/github.com/WebKit/Speedometer.git/+log/f866d2b07703..a6d7f0ae29c9
>
> 2026-07-01 cbruni@chromium.org Use full URL parsing and search params for frame.src (#552)
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/speedometer-chromium
> Please CC v8-waterfall-gardener@rotations.google.com,v8-waterfall-gardeners@google.com on the revert to ensure that a human
> is aware of the problem.
>
> To file a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/entry
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://issues.skia.org/issues/new?component=1389291&template=1850622
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md
>
> Bug: None
> Tbr: v8-waterfall-gardener@rotations.google.com
> Change-Id: I1dac7e353efd1b5fad074491d0bd4e42dd9e20a6
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8029597
> Bot-Commit: chromium-autoroll@skia-public.iam.gserviceaccount.com <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Commit-Queue: chromium-autoroll@skia-public.iam.gserviceaccount.com <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1655465}

Bug: None
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I139d1bd11a32c1015a819d86485a8fda4f9c4cf6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8030503
Auto-Submit: Yuki Shiino <yukishiino@chromium.org>
Owners-Override: Yuki Shiino <yukishiino@chromium.org>
Commit-Queue: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1655886}