chrome: Add missing deps to chrome/browser/ui/views/accessibility:impl
This fixes the following compile error:

```
> autoninja -C out/default obj/chrome/browser/ui/views/accessibility/impl/accessibility_focus_highlight.o
...
In file included from ../../chrome/browser/ui/views/accessibility/accessibility_focus_highlight.cc:13:
In file included from ../../chrome/browser/ui/views/frame/browser_view.h:25:
../../chrome/browser/ui/browser_window.h:25:10: fatal error: 'chrome/browser/ui/webui/tab_search/tab_search.mojom.h' file not found
   25 | #include "chrome/browser/ui/webui/tab_search/tab_search.mojom.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

AX-Relnotes: n/a
Bug: 346429448
Change-Id: If9d6e63a97ddd7a8c8aea7f80b682ceafee83610
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8036420
Commit-Queue: Jacques Newman <janewman@microsoft.com>
Auto-Submit: Junji Watanabe <jwata@google.com>
Reviewed-by: Jacques Newman <janewman@microsoft.com>
Cr-Commit-Position: refs/heads/main@{#1656107}