Disable Rust on iOS with xcode 15.
ios17 uses xcode15, on which bindgen fails to work, due to stdint.h not
providing the uint32_t type.

The bot:
https://ci.chromium.org/ui/p/chromium/builders/ci/ios17-sdk-simulator

```
 python3 ../../build/rust/run_bindgen.py --exe /Volumes/Work/s/w/ir/cache/builder/src/third_party/rust-toolchain/bin/bindgen --header ../../build/rust/tests/bindgen_test/lib.h --depfile obj/build/rust/tests/bindgen_test/c_lib_bindgen.d --output gen/build/rust/tests/bindgen_test/c_lib_bindgen.rs --libclang-path ../../third_party/rust-toolchain/lib -- -DDCHECK_ALWAYS_ON=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_LIBCPP_ENABLE_ASSERTIONS=1 -DCR_XCODE_VERSION=1500 -DCR_CLANG_REVISION=\"llvmorg-17-init-12166-g7586aeab-3\" -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=b272a1c128aae14ac6f77836a4df86dd353fd57e -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -I../.. -Igen -I../../buildtools/third_party/libc++ -Wall -Werror -Wextra -Wimplicit-fallthrough -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wunguarded-availability -Wundeclared-selector -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-ignored-pragma-optimize -Wno-deprecated-builtins -Wno-bitfield-constant-conversion -Wno-deprecated-this-capture -Wshadow -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing -fstack-protector-strong -femit-dwarf-unwind=no-compact-unwind -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -ffp-contract=off -fcomplete-member-pointers -target x86_64-apple-ios15.0-simulator -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes -ftrivial-auto-var-init=pattern -O0 -fno-omit-frame-pointer -gdwarf-4 -g1 -gdwarf-aranges -isysroot sdk/xcode_links/iPhoneSimulator17.0.sdk -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ref-template-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-stack-allocated -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -std=c11 -isystem../../third_party/llvm-build/Release+Asserts/lib/clang/17/include -fparse-all-comments -fvisibility=default
 ../../build/rust/tests/bindgen_test/lib.h:39:18: error: unknown type name 'uint32_t'
 ../../build/rust/tests/bindgen_test/lib.h:39:43: error: unknown type name 'uint32_t'
 ../../build/rust/tests/bindgen_test/lib.h:39:55: error: unknown type name 'uint32_t'
 panicked at 'Unable to generate bindings: ClangDiagnostic("../../build/rust/tests/bindgen_test/lib.h:39:18: error: unknown type name 'uint32_t'\n../../build/rust/tests/bindgen_test/lib.h:39:43: error: unknown type name 'uint32_t'\n../../build/rust/tests/bindgen_test/lib.h:39:55: error: unknown type name 'uint32_t'\n")', bindgen-cli/main.rs:52:36
```

Bug: 1386212
Change-Id: I4b43936e05fd99c68113d60c4c08341fbdf9218f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4652765
Reviewed-by: Justin Cohen <justincohen@chromium.org>
Commit-Queue: Justin Cohen <justincohen@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1163713}