Revert "Reland #4 (?) of "Force Python 3 to be used in build.""
This reverts commit bba4dc0ed6c3390607407454cfd002454941070d.

Reason for revert: Breaks v8 generation script for at least
linux and linux-chromeos.

FAILED: gen/v8/include/v8-gn.h 
python3 ../../v8/tools/gen-v8-gn.py -o gen/v8/include/v8-gn.h -p V8_COMPRESS_POINTERS -p V8_31BIT_SMIS_ON_64BIT_ARCH -p V8_DEPRECATION_WARNINGS -p CPPGC_CAGED_HEAP -n V8_ENABLE_CHECKS -n V8_COMPRESS_ZONES -n V8_HEAP_SANDBOX -n V8_IMMINENT_DEPRECATION_WARNINGS -n V8_NO_ARGUMENTS_ADAPTOR -n V8_USE_PERFETTO -n CPPGC_SUPPORTS_OBJECT_NAMES -n CPPGC_YOUNG_GENERATION
Traceback (most recent call last):
  File "../../v8/tools/gen-v8-gn.py", line 80, in <module>
    main()
  File "../../v8/tools/gen-v8-gn.py", line 63, in main
    header_stream = BytesIO("")
TypeError: a bytes-like object is required, not 'str'

Original change's description:
> Reland #4 (?) of "Force Python 3 to be used in build."
>
> This reverts commit 17801e45e6fead9859bb0f1748afd7efd3e76899.
>
> Reason for revert: Fixes to the internal scripts that broke
> have landed.
>
> Original change's description:
> > Revert "Reland "Force Python 3 to be used in build.""
> >
> > This reverts commit 6ea5c38d3c503161223f5233df8b052d8eb9847d.
> >
> > Reason for revert: build failure: https://ci.chromium.org/ui/p/chromium/builders/ci/Deterministic%20Linux/30058/overview
> >
> > Original change's description:
> > > Reland "Force Python 3 to be used in build."
> > >
> > > This reverts commit b617219612a8f7deec6e289936d346bdab2a6054.
> > >
> > > Reason for revert: We rolled GN to a new version with a fix for
> > > the win dev issues, so hopefully is good to go now.
> > >
> > > Original change's description:
> > > > Revert "Force Python 3 to be used in build."
> > > >
> > > > This reverts commit bb97ab9b82bb505b31c0b4c27a9529e0800e83cf.
> > > >
> > > > Reason for revert: Various breakages.
> > > >
> > > > Original change's description:
> > > > > Force Python 3 to be used in build.
> > > > >
> > > > > This CL makes Python 3 be the default script executable used by Ninja
> > > > > to run action() and action_foreach()'s during the build.
> > > > >
> > > > > This does *not* mean that everything works with Python3; many targets
> > > > > may still use Python 2 via the python2_action() and
> > > > > python2_action_foreach() targets or via custom logic.
> > > > >
> > > > > However, it does mean that it should prevent regressions from
> > > > > creeping in.
> > > > >
> > > > > This CL should not be taken to imply that we can start to write
> > > > > Python3-specific code that can run during the build; we should
> > > > > still be trying to ensure that everything is compatible with Python2.
> > > > >
> > > > > Also, this CL does not enable the use of vpython in actions; we should
> > > > > still avoid that because vpython is slower than direct Python
> > > > > invocations.
> > > > >
> > > > > Bug: 1112471
> > > > > Change-Id: I472b032b500715156d955b0758640a7ed0384305
> > > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2515787
> > > > > Reviewed-by: Bruce Dawson <brucedawson@chromium.org>
> > > > > Commit-Queue: Dirk Pranke <dpranke@google.com>
> > > > > Cr-Commit-Position: refs/heads/master@{#836234}
> > > >
> > > > TBR=dpranke@google.com,brucedawson@chromium.org,chromium-scoped@luci-project-accounts.iam.gserviceaccount.com
> > > >
> > > > Change-Id: I72039140f401f1fefc1b515dcfe34f1984b0d914
> > > > No-Presubmit: true
> > > > No-Tree-Checks: true
> > > > No-Try: true
> > > > Bug: 1112471
> > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2587576
> > > > Reviewed-by: Dirk Pranke <dpranke@google.com>
> > > > Commit-Queue: Dirk Pranke <dpranke@google.com>
> > > > Cr-Commit-Position: refs/heads/master@{#836284}
> > >
> > > TBR=dpranke@google.com,brucedawson@chromium.org,tikuta@chromium.org,chromium-scoped@luci-project-accounts.iam.gserviceaccount.com
> > >
> > > # Not skipping CQ checks because original CL landed > 1 day ago.
> > >
> > > Bug: 1112471
> > > Change-Id: I55ee8ccb381b5aeeac58a85a6168765ed40457ba
> > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2630725
> > > Reviewed-by: Dirk Pranke <dpranke@google.com>
> > > Reviewed-by: Bruce Dawson <brucedawson@chromium.org>
> > > Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
> > > Commit-Queue: Dirk Pranke <dpranke@google.com>
> > > Cr-Commit-Position: refs/heads/master@{#844885}
> >
> > TBR=dpranke@google.com,brucedawson@chromium.org,tikuta@chromium.org,chromium-scoped@luci-project-accounts.iam.gserviceaccount.com
> >
> > Change-Id: I01ac20d80f5fe38a1f8113010f803509df0d7861
> > No-Presubmit: true
> > No-Tree-Checks: true
> > No-Try: true
> > Bug: 1112471
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2637169
> > Reviewed-by: Yutaka Hirano <yhirano@chromium.org>
> > Commit-Queue: Yutaka Hirano <yhirano@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#844986}
>
> TBR=dpranke@google.com,yhirano@chromium.org,brucedawson@chromium.org,tikuta@chromium.org,chromium-scoped@luci-project-accounts.iam.gserviceaccount.com
>
> # Not skipping CQ checks because original CL landed > 1 day ago.
>
> Bug: 1112471
> Change-Id: Icbefaa2cb23b1bf9e54bbd674cb5ab564dae3785
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2643157
> Reviewed-by: Dirk Pranke <dpranke@google.com>
> Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
> Reviewed-by: Bruce Dawson <brucedawson@chromium.org>
> Commit-Queue: Dirk Pranke <dpranke@google.com>
> Cr-Commit-Position: refs/heads/master@{#846193}

TBR=dpranke@google.com,yhirano@chromium.org,brucedawson@chromium.org,tikuta@chromium.org,chromium-scoped@luci-project-accounts.iam.gserviceaccount.com

Change-Id: Ic21ef3e38758d295dac893a02f8d206a67e49d52
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1112471
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2645206
Reviewed-by: James Cook <jamescook@chromium.org>
Commit-Queue: James Cook <jamescook@chromium.org>
Cr-Commit-Position: refs/heads/master@{#846218}