Revert "[CodeHealth] Migrate presubmit checks in components/cronet/ to Python3"
This reverts commit 8e733aa338d2e46778c6070b0d2352aff57f2706.

Reason for revert: https://crbug.com/1272991

This cause the following error:
```
Traceback (most recent call last):
  File "/b/s/w/ir/x/w/src/components/cronet/android/test/javaperftests/run.py", line 50, in <module>
    import urllib.parse
ImportError: No module named parse
```


Original change's description:
> [CodeHealth] Migrate presubmit checks in components/cronet/ to Python3
>
> and fixed resulting errors.
>
> Bug: 1262285
> Change-Id: I5960d8eb23a4d879c94388a11adcf86d9b86ccba
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3282041
> Reviewed-by: Ryan Hamilton <rch@chromium.org>
> Commit-Queue: Joshua Hood‎ <jdh@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#944270}

Bug: 1272991
Change-Id: I6de5279f5632fcc2fd9ae158f446e39556ab5b96
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3296032
Auto-Submit: Arthur Sonzogni <arthursonzogni@chromium.org>
Commit-Queue: Arthur Hemery <ahemery@chromium.org>
Owners-Override: Arthur Sonzogni <arthursonzogni@chromium.org>
Reviewed-by: Arthur Hemery <ahemery@chromium.org>
Cr-Commit-Position: refs/heads/main@{#944433}