Revert "Also bundle repackage_native_impl output"
This reverts commit 33dcf69fcc63050f70fe88db3ff90b2644ddd5a8.

Reason for revert: Breaking CL has been reverted (https://crrev.com/c/4295306), so this is no longer needed.

Original change's description:
> Also bundle repackage_native_impl output
>
> As things stand, both repackage_native and repackage_test_jars
> bundle org/chromium/base/natives/GEN_JNI.class. This causes issues
> downstream, where the one bundled in repackage_native is currently
> winning (for not well defined reasons). Winning in this context means
> that Java -> C++ JNI calls will be resolved looked up inside
> GEN_JNI.class. This is a problem because repackage_native's GEN_JNI
> doesn't contain JNI defined by tests, so tests fails with
> java.lang.NoSuchMethodError: No static method
> org_chromium_net_NativeTestServer_startNativeTestServer
>
> This CL circumvent the issue by also bundling the output of
> repackage_native_impl. Its output is in fact exactly the same of
> repackage_native, modulo the stripping of GEN_JNI.class. This way
> the one bundled in repackage_test_jars will always win.
>
> Rename repackage_native_impl to repackage_native_without_jni
> to better reflect its contents.
>
> Bug: b:266917718, 1401015
> Change-Id: I7509bab3761ca240ee1c0220fb179a15baee3d6a
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4204647
> Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> Commit-Queue: Stefano Duo <stefanoduo@google.com>
> Cr-Commit-Position: refs/heads/main@{#1099738}

Bug: b:266917718, 1401015
Change-Id: I82d1e473e670560bf06481493358cbc399ffdbe0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4395992
Commit-Queue: Stefano Duo <stefanoduo@google.com>
Reviewed-by: Sam Maier <smaier@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1126013}