Fix list_flags.py -u.
Currently, running this command fails with:

ValueError: binary mode doesn't take an encoding argument

Fix by not reading in binary mode. Also change the shebang to use
python3 explicitly, as this script no longer runs with Python 2.

Change-Id: I80023bf0a79e636c6a74b0ff54f508fcc6d0ea8f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3176305
Commit-Queue: Lei Zhang <thestig@chromium.org>
Reviewed-by: Nico Weber <thakis@chromium.org>
Cr-Commit-Position: refs/heads/main@{#924043}