auto-nav.py: check for URL args missing scheme
This change makes auto-nav.py check that the URLs it receives as
command-line arguments contain a scheme (e.g., "https://"). This is
required by chromedriver, so this change just makes auto-nav.py a bit
easier to use.

Old error message:
PS C:\src\chromium\src> vpython3 tools/auto-nav.py out/bug 2 a b
Traceback (most recent call last):
  File "tools/auto-nav.py", line 191, in <module>
    sys.exit(main())
  File "tools/auto-nav.py", line 178, in main
    driver.get(url)
  File "C:\Users\jessemckenna\.vpython-root\03c0a7\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\jessemckenna\.vpython-root\03c0a7\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\jessemckenna\.vpython-root\03c0a7\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=92.0.4492.0)

New error message:
PS C:\src\chromium\src> vpython3 tools/auto-nav.py out/bug 2 a b
auto-nav.py: error: URL is missing required scheme (e.g., "https://"): a

Change-Id: If2802af82f86c649cb1d5b134557453a995e6d8e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2894451
Commit-Queue: Jesse McKenna <jessemckenna@google.com>
Reviewed-by: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/master@{#882743}