chrome/browser/ui/autofill: fix missing deps
$ siso ninja -C out/dep obj/chrome/browser/ui/autofill/impl/chrome_autofill_client.o
...
stderr:
In file included from ../../chrome/browser/ui/autofill/chrome_autofill_client.cc:156:
In file included from ../../chrome/browser/compose/chrome_compose_client.h:15:
../../chrome/browser/compose/compose_session.h:20:10: fatal error: 'chrome/common/compose/compose.mojom.h' file not found
   20 | #include "chrome/common/compose/compose.mojom.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

chrome/browser/ui/autofill/chrome_autofill_client.cc
(//chrome/browser/ui/autofill:impl) includes
headers in //chrome/browser
and depends on //chrome/browser:browser_public_dependencies.

add //chrome/common/compose:mojo_bindings (for
gen/chrome/common/compose/compose.mojom.h) in
//chrome/browser:browser_public_dependencies.

Bug: b/371126166
Change-Id: I40e876b2c2eed09c07dcaa11220117a77a060edb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5905663
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Erik Chen <erikchen@chromium.org>
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Hidehiko Abe <hidehiko@chromium.org>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1363526}