Reland "[AutoDark] Add AutoDark app menu item"
This reverts commit 79b4ee8ba7996b76f9257654d8d3aa461010997c.

Reason for revert: This CL does not use ObserverableSupplier; attempting to relanding

Original change's description:
> Revert "[AutoDark] Add AutoDark app menu item"
>
> This reverts commit 9a25aff4656cf4887f671080cb754cffa66e8fd6.
>
> Reason for revert:
> Seems to cause this build failure:
> Error: Default interface methods are only supported starting with Android N (--min-api 24): Lorg/chromium/base/supplier/ObservableSupplier;hasValue()Z
> in
> https://ci.chromium.org/ui/p/chromium/builders/ci/android-pie-arm64-rel/11634/overview
>
> Original change's description:
> > [AutoDark] Add AutoDark app menu item
> >
> > -Adds app menu item for AutoDark.
> > -Shows app menu item when both flag and global setting are enabled.
> > -Menu item adds site setting exceptions to block sites from auto-darkening (or removes exceptions for sites that are currently blocked).
> >
> > Note: Uses placeholder string for app menu item and temp value for ContentSettingType.
> >
> > Screenshot: https://screenshot.googleplex.com/3gp8H3r5kV4KEE7.png
> >
> > Bug: 1248537
> > Change-Id: Icf04ee922923b0c0298b12e7c21e2dd65f0c758e
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3140103
> > Reviewed-by: Wenyu Fu <wenyufu@chromium.org>
> > Reviewed-by: Filip Gorski <fgorski@chromium.org>
> > Reviewed-by: Christian Dullweber <dullweber@chromium.org>
> > Reviewed-by: Gang Wu <gangwu@chromium.org>
> > Commit-Queue: Neil Coronado <nemco@google.com>
> > Cr-Commit-Position: refs/heads/main@{#922769}
>
> Bug: 1248537
> Change-Id: Id7add84757e070fcc90b597bb10c6ff80735e619
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3170532
> Auto-Submit: Daniel Murphy <dmurph@chromium.org>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Commit-Queue: Chloe Pelling <cpelling@google.com>
> Owners-Override: Chloe Pelling <cpelling@google.com>
> Cr-Commit-Position: refs/heads/main@{#922836}

Bug: 1248537
Cq-Include-Trybots: luci.chromium.try:android-pie-arm64-rel
Change-Id: I6bf1e1c2b13021ad86c4d4e4ed3fd95afe29e730
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3171267
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Gang Wu <gangwu@chromium.org>
Reviewed-by: Daniel Murphy <dmurph@chromium.org>
Reviewed-by: Filip Gorski <fgorski@chromium.org>
Reviewed-by: Christian Dullweber <dullweber@chromium.org>
Commit-Queue: Wenyu Fu <wenyufu@chromium.org>
Cr-Commit-Position: refs/heads/main@{#923118}