Revert "Batch AppBannerManagerTest"
This reverts commit 34fe73ee6891705957aefd1b8fd3f4657df07805.

Reason for revert: Seems to cause test failures on android-nougat-x86-rel

https://ci.chromium.org/ui/p/chromium/builders/ci/android-nougat-x86-rel/4779/test-results?sortby=&groupby=

java.lang.AssertionError: Page never became interactable.
	at org.junit.Assert.fail(Assert.java:89)
	at org.chromium.chrome.test.util.ChromeTabUtils.waitForInteractable(ChromeTabUtils.java:363)
	at org.chromium.chrome.test.ChromeActivityTestRule.loadUrlInNewTab(ChromeActivityTestRule.java:361)
	at org.chromium.chrome.test.ChromeActivityTestRule.loadUrlInNewTab(ChromeActivityTestRule.java:338)
	at org.chromium.chrome.test.ChromeActivityTestRule.loadUrlInNewTab(ChromeActivityTestRule.java:329)
	at org.chromium.chrome.browser.banners.AppBannerManagerTest.testBottomSheetSkipsHiddenWebContents(AppBannerManagerTest.java:1064)


Original change's description:
> Batch AppBannerManagerTest
>
> This CL changes the following two things in the test suite to batch them:
> 1. Turns the RecordHistogram.getHistogramValueCountForTesting usage to
> use HistogramWatcher, so the counts won't stay between tests
> 2. CLoses all tabs for the two tests with hidden WebContents, because
> they need to run with the exact number of tabs.
>
> Bug: 1145837
> Change-Id: Ibff2293fb83ff0f0bc682fe55b78c310e5eed89d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4599090
> Reviewed-by: Peter Conn <peconn@chromium.org>
> Commit-Queue: Peter Conn <peconn@chromium.org>
> Auto-Submit: Ella Ge <eirage@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1155466}

Bug: 1145837
Change-Id: Ia59d04fab584fa550ea90272b15365cc1e918044
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4604971
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Justin DeWitt <dewittj@chromium.org>
Auto-Submit: Justin DeWitt <dewittj@chromium.org>
Reviewed-by: Justin DeWitt <dewittj@chromium.org>
Commit-Queue: Justin DeWitt <dewittj@chromium.org>
Reviewed-by: Dan H <harringtond@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1155711}