Revert "Suppress -Wfree-nonheap-object in libsync"
This reverts commit 8def637ba490adea1c28bfefac34d52822a27250.

Reason for revert: Warning was made less aggressive in https://reviews.llvm.org/D97512

Original change's description:
> Suppress -Wfree-nonheap-object in libsync
>
> libsync uses an uint64_t to represent a pointer which triggers this new warning:
>
> ../../third_party/libsync/src/sync.c:142:18: error: attempt to call free on non-heap object '(void *)info->sync_fence_info' [-Werror,-Wfree-nonheap-object]
> free((void *)info->sync_fence_info);
>
> Bug: 1182743
> Change-Id: I137070f9b0cac84fe8406362c349fd3ecaa72ea9
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2723272
> Commit-Queue: Arthur Eubanks <aeubanks@google.com>
> Commit-Queue: Nico Weber <thakis@chromium.org>
> Reviewed-by: Nico Weber <thakis@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#858209}

Bug: 1182743
Change-Id: I09b7097cc6617f34834a44adca4e95443cc439d2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2822652
Auto-Submit: Arthur Eubanks <aeubanks@google.com>
Commit-Queue: Hans Wennborg <hans@chromium.org>
Reviewed-by: Hans Wennborg <hans@chromium.org>
Cr-Commit-Position: refs/heads/master@{#871833}