Revert "Load QuickOffice manifest from cros rootfs"
This reverts commit a1b9a2a855e11df2b04d6643c459e3fec2a8ebe6.

Reason for revert: suspect causing compile failure on lacros-arm32-rel-ready bot.

First build failure:
https://ci.chromium.org/ui/p/chrome/builders/ci/lacros-arm32-rel-ready/17628/overview

Sample log:
../../chrome/browser/extensions/component_loader.cc:550:7: error: use of undeclared identifier 'AddComponentFromDirWithManifestFilename'
AddComponentFromDirWithManifestFilename(
^
1 error generated.

Original change's description:
> Load QuickOffice manifest from cros rootfs
>
> QuickOffice will change in crrev.com/c/5014644 to load all files
> including manifest.json into rootfs at
> /usr/share/chromeos-assets/quickoffice.
>
> CrOS will load all files directly from gcs rather than using the
> chromium repo submodule. There will be no need to keep
> chrome/browser/resources/chromeos/quickoffice.
>
> Bug: 1491571
> Change-Id: I1f1de7cc1c4950b4fd30d1bab8300faf6b7e8494
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5013290
> Commit-Queue: Joel Hockey <joelhockey@chromium.org>
> Reviewed-by: Dominick Ng <dominickn@chromium.org>
> Reviewed-by: Kyle Horimoto <khorimoto@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1222566}

Bug: 1491571
Change-Id: Ifdc07c1b1b21caf0bf5ad35913bb1c2a12dd3f51
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5017114
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/main@{#1222647}