Revert "Roll Catapult from 471aa8aec31a to e5fe611367ec (1 revision)"
This reverts commit 8c596a2269ff6219d6da036cf812e0977435e359.

Reason for revert: suspected to cause linux-presubmit bot failure.

Failure Link: https://ci.chromium.org/ui/p/chromium/builders/ci/linux-presubmit/43148

> ./run_performance_tests_unittest.py
> argparse.ArgumentError: argument --browser: invalid choice: 'android-webview-trichrome-google-bundle' ...

Original change's description:
> Roll Catapult from 471aa8aec31a to e5fe611367ec (1 revision)
>
> https://chromium.googlesource.com/catapult.git/+log/471aa8aec31a..e5fe611367ec
>
> 2026-09-15 victorvianna@google.com Migrate catapult away from trichrome targets
>
> If this roll has caused a breakage, revert this CL and set the roller
> to dry run mode using the controls here:
> https://autoroll.skia.org/r/catapult-autoroll
> Please CC browser-perf-engprod@google.com,ggj@google.com,gmarcoesau@google.com,johnchen@chromium.org,wenbinzhang@google.com on the revert to ensure that a human
> is aware of the problem.
>
> To file a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/entry
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://issues.skia.org/issues/new?component=1389291&template=1850622
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md
>
> Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:gpu-fyi-cq-mac-arm64;luci.chromium.try:win_optional_gpu_tests_rel;luci.chromium.try:gpu-fyi-cq-win-arm64;luci.chromium.try:dawn-android-arm-deps-rel;luci.chromium.try:dawn-android-arm64-deps-rel;luci.chromium.try:dawn-linux-x64-deps-rel;luci.chromium.try:dawn-mac-x64-deps-rel;luci.chromium.try:dawn-mac-arm64-deps-rel;luci.chromium.try:dawn-win10-x64-deps-rel;luci.chromium.try:dawn-win10-x86-deps-rel;luci.chromium.try:dawn-win11-arm64-deps-rel;luci.chrome.try:linux-autofill-captured-sites-rel;luci.chrome.try:linux-password-manager-captured-sites-rel
> Bug: chromium:532501271
> Tbr: ggj@google.com,gmarcoesau@google.com
> Change-Id: I394207e189414b6ddc6d7dca884814c34072235a
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8412268
> Commit-Queue: chromium-autoroll@skia-public.iam.gserviceaccount.com <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Bot-Commit: chromium-autoroll@skia-public.iam.gserviceaccount.com <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1698197}

Bug: chromium:532501271
Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:gpu-fyi-cq-mac-arm64;luci.chromium.try:win_optional_gpu_tests_rel;luci.chromium.try:gpu-fyi-cq-win-arm64;luci.chromium.try:dawn-android-arm-deps-rel;luci.chromium.try:dawn-android-arm64-deps-rel;luci.chromium.try:dawn-linux-x64-deps-rel;luci.chromium.try:dawn-mac-x64-deps-rel;luci.chromium.try:dawn-mac-arm64-deps-rel;luci.chromium.try:dawn-win10-x64-deps-rel;luci.chromium.try:dawn-win10-x86-deps-rel;luci.chromium.try:dawn-win11-arm64-deps-rel;luci.chrome.try:linux-autofill-captured-sites-rel;luci.chrome.try:linux-password-manager-captured-sites-rel
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I6f747fd2341858e4838713eacedb90a2035bbdc1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8411214
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Hiroshige Hayashizaki <hiroshige@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1698313}