media/gpu/v4l2/test: Replace native references with raw_ref<T>
Required by Chromium code style checks:

    error: [chromium-rawref] Use raw_ref<T> instead of a native reference.

Bug: b:258331312, b:291169645
Change-Id: I8fbfc59dce3a720e9c087796e37109a62121282c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4710351
Reviewed-by: Miguel Casas-Sanchez <mcasas@chromium.org>
Commit-Queue: Chen-Yu Tsai <wenst@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1175274}