Revert "Policy WebUI: 'Reload Policies' button reloads google update policies"
This reverts commit e030934239279d80a01af7602edde943bc565f9d.

Reason for revert: doesn't compile on for example https://ci.chromium.org/p/chrome/builders/ci/win-chrome/14113

../../chrome/browser/ui/webui/policy_ui_handler.cc(1298,30): error: no viable overloaded '='
updater_status_provider_ = std::make_unique<UpdaterStatusProvider>();
~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../buildtools/third_party/libc++/trunk/include\memory(2551,15): note: candidate function not viable: 'this' argument has type 'const std::unique_ptr<PolicyStatusProvider>', but method is not marked const


Original change's description:
> Policy WebUI: 'Reload Policies' button reloads google update policies
> 
> Bug: 1119703
> Change-Id: Ib91b37dc1da4f06782caea7b67ecc6d0c8c87b2d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2367673
> Commit-Queue: Yann Dago <ydago@chromium.org>
> Reviewed-by: Owen Min <zmin@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#802644}

TBR=zmin@chromium.org,ydago@chromium.org

Change-Id: I6c3b3bb79801e5aae68ab97f5ba79e5b8d10509a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1119703
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2381300
Reviewed-by: Marijn Kruisselbrink <mek@chromium.org>
Commit-Queue: Marijn Kruisselbrink <mek@chromium.org>
Cr-Commit-Position: refs/heads/master@{#802668}