IWYU: usage of nan() in cstring_builder_pa_unittests.cc requires including cmath
Fix build error with libstdc++:
    ../../base/allocator/partition_allocator/partition_alloc_base/strings/cstring_builder_pa_unittest.cc: In member function ‘virtual void partition_alloc::internal::base::strings::CStringBuilderTestPA_FloatingPoint_Test::TestBody()’:
    ../../base/allocator/partition_allocator/partition_alloc_base/strings/cstring_builder_pa_unittest.cc:98:15: error: ‘nan’ was not declared in this scope
       98 |   builder9 << nan("");
          |               ^~~

Bug: 957519
Change-Id: I2383db46be24c0bed06e4b0c6a79d628d166b635
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4790501
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#1184725}