Fix screen lock detection for Gnome, MATE, and XFCE4.
The object_path field was unset in the kServices datastructure, which means the GetActive call will always fail.

Compare:

$ gdbus call --session --dest org.gnome.ScreenSaver  --object-path  / -m org.gnome.ScreenSaver.GetActive
Error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path "/"
$ gdbus call --session --dest org.gnome.ScreenSaver  --object-path  /org/gnome/ScreenSaver -m org.gnome.ScreenSaver.GetActive
(false,)

Tested on Ubuntu 22.04 using the demo https://developer.mozilla.org/en-US/docs/Web/API/IdleDetector

(cherry picked from commit fea5c9b297a1b1b1de6755cc7203a573fa7ffc7c)

Change-Id: Ic51d88f84d6ab81df93d81474312d6d87761c637
Bug: 1336001
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3695929
Reviewed-by: Scott Violet <sky@chromium.org>
Commit-Queue: Robert Spier <rspier@google.com>
Reviewed-by: Thomas Anderson <thomasanderson@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1013696}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3706138
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Robert Spier <rspier@google.com>
Commit-Queue: Scott Violet <sky@chromium.org>
Cr-Commit-Position: refs/branch-heads/5112@{#68}
Cr-Branched-From: b13d3fe7b3c47a56354ef54b221008afa754412e-refs/heads/main@{#1012729}