Revert "Introduce ElementRareDataVector"
This reverts commit 8d8e1983cbbea64724a3963f5d1c7d1a96659b54.

Reason for revert: Suspecting that this introduced crashes on UBsan and CFI builders, e.g. https://ci.chromium.org/ui/p/chromium/builders/ci/linux-ubsan-vptr/19222
[ RUN      ] All/PaintPreviewRecorderRenderViewTest.TestCaptureLocalFrame/NoCompositeAfterPaint
../../third_party/blink/renderer/core/dom/element.cc:1028:10: runtime error: downcast of address 0x312900229e20 which does not point to an object of type 'ElementRareData'
0x312900229e20: note: object is of type 'blink::ElementRareDataVector'
 7d 02 16 00  98 c9 29 2b 4b 56 00 00  01 00 00 40 14 25 0f 80  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'blink::ElementRareDataVector'
    #0 0x564b28241601 in GetElementRareData third_party/blink/renderer/core/dom/element.cc:1028:10
    #1 0x564b28241601 in blink::Element::HasElementFlagInternal(blink::ElementFlags) const third_party/blink/renderer/core/dom/element.cc:652:10
    #2 0x564b28283db2 in StyleAffectedByEmpty third_party/blink/renderer/core/dom/element.h:697:12
    #3 0x564b28283db2 in blink::Element::CheckForEmptyStyleChange(blink::Node const*, blink::Node const*) third_party/blink/renderer/core/dom/element.cc:4420:8
   ...

Instead of reverting, I first tried fixing this by simply changing the cast in element.cc's GetElementRareData() to cast to ElementRareDataBase* - which looked like it was simply forgotten in 
CL:3947564 - but this was not possible as easily, because ElementRareDataBase does not inherit from NodeRareData. Probably the inheritance hierarchy will need to be changed first:

../../third_party/blink/renderer/core/dom/element.cc:1028:10: error: static_cast from 'NodeRareData *' to 'ElementRareDataBase *', which are not related by inheritance, is not allowed
  return static_cast<ElementRareDataBase*>(RareData());

Original change's description:
> Introduce ElementRareDataVector
>
> This class is an alternative to the existing ElementRareData which
> should use less memory by storing each ElementRareData member in a
> vector only when members are actually requested.
>
> https://docs.google.com/document/d/17h-zNNWTUrSqp9kl7zI2JWkfrv4B6KS56LZwbXiVtrM/edit?resourcekey=0-EiflwUy7FrpNOXU6P7GBbw
>
> Bug: 1262227
> Change-Id: I18f57dc30e73ed501fbbbd137048888abd0ebaf9
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3917270
> Commit-Queue: Joey Arhar <jarhar@chromium.org>
> Reviewed-by: Anders Hartvoll Ruud <andruud@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1079390}

Bug: 1262227
Change-Id: I0dd7d4c76f93b8d64ee59bb77bf7d657c2f7f47c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4079215
Owners-Override: Pavol Marko <pmarko@chromium.org>
Auto-Submit: Pavol Marko <pmarko@chromium.org>
Commit-Queue: Michael Ershov <miersh@google.com>
Commit-Queue: Pavol Marko <pmarko@chromium.org>
Reviewed-by: Michael Ershov <miersh@google.com>
Cr-Commit-Position: refs/heads/main@{#1079698}