Revert "Fix compile for Chrome-branded builds"
This reverts commit afc8e2d46315742e0c1dc58cf3d190a0424b7cdb.

Reason for revert: This cl broke the build:
Looks like this cl broke the build:
https://ci.chromium.org/ui/p/chrome/builders/try/lacros-amd64-generic-chrome/1327/overview

Original change's description:
> Fix compile for Chrome-branded builds
>
> With the following gn args:
>
> use_goma = true
> is_debug = false
> is_component_build = false
> enable_nacl = true
> symbol_level = 2
> blink_symbol_level = 1
> is_official_build = true
> is_chrome_branded = true
> media_use_ffmpeg = true
> media_use_libvpx = true
> proprietary_codecs = true
> ffmpeg_branding = "Chrome"
> enable_software_reporter = false
>
> I cannot compile as I hit the following error:
>
> ```
> ../../chrome/browser/ui/views/profiles/profile_menu_view.cc(598,9): error: use of undeclared identifier 'kGoogleGLogoIcon'; did you mean 'vector_icons::kGoogleGLogoIcon'?
>         kGoogleGLogoIcon,
>         ^~~~~~~~~~~~~~~~
>         vector_icons::kGoogleGLogoIcon
> gen\components/vector_icons/vector_icons.h(144,24): note: 'vector_icons::kGoogleGLogoIcon' declared here
> VECTOR_ICON_TEMPLATE_H(kGoogleGLogoIcon)
> ```
>
> Bug: none
> Change-Id: I9814ed59232cfbbb16472e0ee6db3c1aa267a44a
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3884542
> Reviewed-by: Ramin Halavati <rhalavati@chromium.org>
> Commit-Queue: Alex Gough <ajgo@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1045185}

Bug: none
Change-Id: I9d1198a21aa0c1761dc4e0b0628565380ef7f99b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3887282
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Jenny Zhang <jennyz@chromium.org>
Owners-Override: Jenny Zhang <jennyz@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1045284}