ash/app_list: fix missing deps
In file included from ../../ash/app_list/views/search_box_view.cc:28:
../../ash/capture_mode/capture_mode_controller.h:30:10: fatal error: 'chromeos/ash/services/recording/public/mojom/recording_service.mojom.h' file not found
   30 | #include "chromeos/ash/services/recording/public/mojom/recording_service.mojom.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

ash/app_list/views/search_box_view.cc (//ash/app_list)
includes ash/capture_mode/capture_mode_controller.h (//ash),
which includes
gen/chromeos/ash/services/recording/public/mojom/recording_service.mojom.h
(//chromeos/ash/services/recording/public/mojom).

Add //chromeos//ash/services/recording/public/mojom in public_deps of
//ash/public/cpp, which //ash/app_list depends on.

Bug: 371475033
Change-Id: Iff92e776a9359ebc2f6c7355420638f512fd9e31
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5907334
Reviewed-by: Mitsuru Oshima <oshima@chromium.org>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Cr-Commit-Position: refs/heads/main@{#1364064}