Propagate the VPX platform configs dir to dependant targets.
Without this CL, if a VPX header file (e.g. vpx_thread.h) includes
vpx_config.h (which is target platform specific), it will fail to
compile with the error:

../../third_party/libvpx/source/libvpx/vpx_util/vpx_thread.h:18:10: fatal error: './vpx_config.h' file not found
   18 | #include "./vpx_config.h"

This is caused by the fact that "-I third_party/libvpx/source/config/linux/x64/" is not propagated to the compiler command for the translation unit that included vpx_thread.h.

To fix this, this CL ensures that we propagate the path of where
vpx_config.h lives to all the targets that depend on //third_party/libvpx.

Bug: b/313730937
Change-Id: I1d4ecf9bab2a2570113e81d15acec3382b2045f2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5087695
Commit-Queue: Mirko Bonadei <mbonadei@chromium.org>
Reviewed-by: James Zern <jzern@google.com>
Cr-Commit-Position: refs/heads/main@{#1233577}