CCA: Fix implicit any return type for functions
This CL fixes the following tsc error:
> error TS7014: Function type, which lacks return-type annotation,
> implicitly has an 'any' return type.

Most of the callback functions expect "void" return type, and some of
them expect "!Promise" instead. In some cases we need to use explicit
any type "*" to make Closure compiler happy.

Bug: b/172340451
Test: Reduced 25 errors in tsc.
Change-Id: I5632a2cc62d1e399462217d140af3d9ce66b9125
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2709984
Auto-Submit: Shik Chen <shik@chromium.org>
Reviewed-by: Inker Kuo <inker@chromium.org>
Commit-Queue: Shik Chen <shik@chromium.org>
Cr-Commit-Position: refs/heads/master@{#856168}