Revert "Replace JSONStringValueDeserializer with base::JSONReader"
This reverts commit 69d52b169460d36b978cbfc0d5bfb6be215ff21a.

Reason for revert: Breaking linux builds

../../chrome/common/media/component_widevine_cdm_hint_file_linux.cc:75:3: error: unknown type name 'JSONStringValueSerializer'
   75 |   JSONStringValueSerializer serializer(&json_string);
      |   ^
1 error generated.

Bug: 40912727, 40258809, 40912723
Original change's description:
> Replace JSONStringValueDeserializer with base::JSONReader
>
> base::JSONReader presents a simpler API based on std::optional and
> base::expected, and JSONStringValueDeserializer will be removed in the
> future.
>
> This CL was uploaded by git cl split.
>
> R=aprilzhou@google.com, droger@chromium.org, khmel@chromium.org, muyaoxu@google.com, slutskii@google.com, wfh@chromium.org
>
> Bug: 40912727, 40258809, 40912723
> Change-Id: Ief3d19a84748725ce728bddd21a99eef24ba84c0
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6438231
> Reviewed-by: Yury Khmel <khmel@chromium.org>
> Reviewed-by: Ted Choc <tedchoc@chromium.org>
> Commit-Queue: Ted Choc <tedchoc@chromium.org>
> Reviewed-by: Muyao Xu <muyaoxu@google.com>
> Reviewed-by: April Zhou <aprilzhou@google.com>
> Reviewed-by: Will Harris <wfh@chromium.org>
> Reviewed-by: Michael Slutskii <slutskii@google.com>
> Auto-Submit: Andrew Paseltiner <apaseltiner@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1447249}

Bug: 40912727, 40258809, 40912723
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I2c34c75ff3c884288729c7f413105488253e14cb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6460030
Reviewed-by: Yury Khmel <khmel@chromium.org>
Commit-Queue: Giovanni Ortuno Urquidi <ortuno@chromium.org>
Reviewed-by: Will Harris <wfh@chromium.org>
Owners-Override: Giovanni Ortuno Urquidi <ortuno@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1447300}