[119] Don't scroll to an invalid index path
This CL addresses a crash we see in Stable, with the following
exception:

> NSInternalInconsistencyException: Attempted to scroll the
> collection view to an out-of-bounds item (15) when there are
> only 15 items in section 0.

This is similar to crrev/c/4915697, that solved another codepath the
same way.

(cherry picked from commit f443851d98b27575a49645f16a0c19c657d709d0)

Fixed: 1490362
Change-Id: Id273a747c6b25e41d5abc07530c906c002908358
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4946311
Auto-Submit: Louis Romero <lpromero@google.com>
Code-Coverage: findit-for-me@appspot.gserviceaccount.com <findit-for-me@appspot.gserviceaccount.com>
Commit-Queue: Aliona Dangla <alionadangla@chromium.org>
Reviewed-by: Aliona Dangla <alionadangla@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1210924}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4949852
Commit-Queue: Louis Romero <lpromero@google.com>
Cr-Commit-Position: refs/branch-heads/6045@{#631}
Cr-Branched-From: 905e8bdd32d891451d94d1ec71682e989da2b0a1-refs/heads/main@{#1204232}