GCC: explicitely move return value of SCTHashdanceMetadata::ToValue
GCC rejects to do Return Value Optimization in
SCTHashdanceMetadata::ToValue, because the copy constructor is
deleted, and in that scenario RVO is rejected in GCC:
    ../../services/network/sct_auditing/sct_auditing_reporter.cc: In member function ‘base::Value network::SCTAuditingReporter::SCTHashdanceMetadata::ToValue() const’:
    ../../services/network/sct_auditing/sct_auditing_reporter.cc:191:10: error: use of deleted function ‘base::Value::Value(const base::Value&)’
      191 |   return value;
          |          ^~~~~
    In file included from ../../services/network/sct_auditing/sct_auditing_reporter.h:14,
                     from ../../services/network/sct_auditing/sct_auditing_reporter.cc:5:
    ../../base/values.h:254:3: note: declared here
      254 |   Value(const Value&) = delete;
          |   ^~~~~

Bug: 819294
Change-Id: I111e51dd10eee7b909d4ac3c0911aac18a589166
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3488747
Reviewed-by: Chris Thompson <cthomp@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#976299}