Revert "[third_party] Uprev protobuf to v3.13.0.1+"
This reverts commit a3bfafb151b195006c7f4674b86944804ff6cbf9.

Reason for revert: Breaks compilation, for example on https://ci.chromium.org/p/chromium/builders/ci/Deterministic%20Linux%20%28dbg%29/19608

[14678/62398] ACTION //tools/privacy_budget/blink_apis:blink_apis(//build/toolchain/linux:clang_x64)
FAILED: blink_apis.textpb 
python ../../tools/privacy_budget/blink_apis/generate_blink_api_db.py --web_idl_database gen/third_party/blink/renderer/bindings/web_idl_database.pickle --output blink_apis.textpb --path ../../third_party/blink/renderer/bindings/scripts:../../third_party/blink/renderer/build/scripts:pyproto/tools/privacy_budget/blink_apis/proto:pyproto:pyproto/google/third_party/six
Traceback (most recent call last):
  File "../../tools/privacy_budget/blink_apis/generate_blink_api_db.py", line 74, in <module>
    main()
  File "../../tools/privacy_budget/blink_apis/generate_blink_api_db.py", line 66, in main
    from blink_api_proto import BlinkApiProto
  File "/b/s/w/ir/cache/builder/src/tools/privacy_budget/blink_apis/blink_api_proto.py", line 10, in <module>
    import blink_apis_pb2 as pb
  File "pyproto/tools/privacy_budget/blink_apis/proto/blink_apis_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: 'module' object has no attribute '_internal_create_key'

Original change's description:
> [third_party] Uprev protobuf to v3.13.0.1+
>
> Followed process in //third_party/protobuf/README.chromium
> Highlights:
> * Some protobuf APIs started being deprecated. Moved sources in
> //chromecast and //components to start using the non-deprecated
> versions.
> * Removed most of the patches and updated the ones that are still
> needed. No new patches.
> * //components/subresource_filter/core/common/unindexed_ruleset.h:
> HadError is not const anymore.
>
> Size increase is caused by protobuf mainlining 2
> functions to Serialize and Parse inside each *pb.cc file. This new
> methods are now the way protobuf serializes and deserializes messages
> so no way to avoid those without substantially changing protobuf
> internals.
>
> Binary-Size: Unavoidable. Increase intrinsic to new protobuf.
> Bug: 1144985
> Change-Id: I23ce43f07da82fdda60575934a4b039200164f48
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2518036
> Commit-Queue: Andres Medina <medinaandres@chromium.org>
> Auto-Submit: Andres Medina <medinaandres@chromium.org>
> Reviewed-by: Colin Blundell <blundell@chromium.org>
> Reviewed-by: Peter Kasting <pkasting@chromium.org>
> Reviewed-by: Luke Halliwell (slow) <halliwell@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#828263}

TBR=pkasting@chromium.org,caitkp@chromium.org,blundell@chromium.org,halliwell@chromium.org,medinaandres@chromium.org

Change-Id: I856a83d283bcf9453cfdd604a4ee7dba539d2b68
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1144985
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2544866
Reviewed-by: Marijn Kruisselbrink <mek@chromium.org>
Commit-Queue: Marijn Kruisselbrink <mek@chromium.org>
Cr-Commit-Position: refs/heads/master@{#828302}