Revert "[MerchantTrust] Update favicon while navigating within bottom sheet"
This reverts commit d13faf82daf15785007b552fef5dbc3024861807.

Reason for revert:
Error: Default interface methods are only supported starting with Android N (--min-api 24): Lorg/chromium/base/supplier/ObservableSupplier;hasValue()Z

Original change's description:
> [MerchantTrust] Update favicon while navigating within bottom sheet
>
> We need to update favicon dynamically while user navigates within the
> bottom sheet.
>
> Bug: 1250399
> Change-Id: I3f5fc58fa4b7fb6b5c18d1c02e16f608e522a172
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3168758
> Reviewed-by: Ayman Almadhoun <ayman@chromium.org>
> Commit-Queue: Zhiyuan Cai <zhiyuancai@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#922660}

Bug: 1250399
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Ice67d144aecfec0a1d5e5deee656bb571f12c264
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3171020
Owners-Override: Swapnil Gupta <swapnilgupta@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Swapnil Gupta <swapnilgupta@google.com>
Cr-Commit-Position: refs/heads/main@{#922878}