Add missing <string> include in hid_system_tray_icon.h
Without this include, ash chrome arm64 build fails to me
with:

../../chrome/browser/hid/hid_system_tray_icon.h:35:15:
 error: no type named 'u16string' in namespace 'std'
  static std::u16string GetManageHidDeviceButtonLabel(Profile* profile);
         ~~~~~^
../../chrome/browser/hid/hid_system_tray_icon.h:38:15:
 error: no type named 'u16string' in namespace 'std'
  static std::u16string GetTooltipLabel(size_t num_devices);
         ~~~~~^
2 errors generated.

Bug: None
Change-Id: I603dbf0b7a6cefea5c429ebedc4c6d92fb833849
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4255289
Auto-Submit: Antonio Gomes <tonikitoo@igalia.com>
Commit-Queue: Scott Violet <sky@chromium.org>
Reviewed-by: Scott Violet <sky@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1105912}