[Nearby] Remove traces of Nearby Share in non-primary profiles
Before this CL, Nearby Share objects were still created for non-primary
profiles. Notably, the share sheet icon was displayed and would crash if
clicked. Also, the Nearby Share settings row was displayed, but no data
or services, e.g., contact retrieval, were available.

Here, we add a static function,
IsNearbyShareSupportedForBrowserContext(), to be used as the source of
truth for whether or not any Nearby Share objects should be created for
the given browser context. Previously, only the feature flag was used
in many places.

Exception: We do not change the logic in
PopulateChromeWebUIFrameBinders(). Because Nearby Share is only
currently supported for the primary profile, we should only register
binders in that scenario. However, we don't want to plumb the profile
through to this function. Instead, we 1) ensure that NearbyShareDialogUI
will not be created for non-primary profiles, and 2) rely on the
BindInterface() implementation of OSSettingsUI to ensure that no Nearby
Share receivers are bound.

Manually verified no trace of Nearby Share in non-primary profiles and,
consequently, no crashes. Confirmed that non-primary profiles cannot
bypass our restrictions by navigating to chrome://nearby or
chrome://os-settings/multidevice/nearbyshare.

Fixed: 1176145
Change-Id: I065939dc6f14c1ea268148b97faf5c708f8ed6a2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2686449
Commit-Queue: Josh Nohle <nohle@chromium.org>
Reviewed-by: Richard Knoll <knollr@chromium.org>
Reviewed-by: Melissa Zhang <melzhang@chromium.org>
Reviewed-by: Alex Gough <ajgo@chromium.org>
Reviewed-by: Kyle Horimoto <khorimoto@chromium.org>
Reviewed-by: James Vecore <vecore@google.com>
Cr-Commit-Position: refs/heads/master@{#858873}