Dictation: Speculative fix for flaky Dictation JS tests
According to the attached bug and the chromium flake portal [1], there
are flaky Dictation JavaScript tests. The most prominent one is
DictationE2ETest.SilencesSpokenFeedbackWhenStarting, which fails
with the following error:

AssertionError: expected '' to equal '_ext_ime_egfdjlfmgnehecnclamagfafdccgfndpdictation'

However, there are other tests that also flake with the same error.

I haven't been able to reproduce these flakes locally, even when
running many tests in parallel. The most likely cause for the flakes
is the NO_FOCUSED_IME timeout, which will stop Dictation (and reset
the active IME) if Dictation doesn't focus a text field before the
timeout runs (which is currently one second). This change attempts to
address the flakes by increasing the NO_FOCUSED_IME timeout so that
we guarantee that Dictation is never stopped by timeouts. We already
do this in C++ tests, so it makes sense to do the same in JS tests.

[1] https://luci-analysis.appspot.com/p/chromium/clusters?q=dictation

AX-Relnotes: N/A
Bug: b:260206802
Change-Id: I7927443514eaeaf3d677f969c3a881a82072af07
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4142282
Commit-Queue: Akihiro Ota <akihiroota@chromium.org>
Reviewed-by: Katie Dektar <katie@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1090186}