Add missing mojom dependency
display_color_spaces_mojom_traits.cc includes
skcolorspace_primaries_mojom_traits.h which then includes
skcolorspace_primaries.mojom.h, but since no dependency is declared
there was no guarantee that the mojom.h file would be generated in time.
This adds the needed dependency to guarantee the correct build ordering.

The (edited) build error message on Windows was:
obj/ui/gfx/mojom/shared_mojom_traits/display_color_spaces_mojom_traits.obj
...
In file included from ../../ui/gfx/mojom/display_color_spaces_mojom_traits.cc:7:
../..\skia/public/mojom/skcolorspace_primaries_mojom_traits.h(9,10): fatal error: 'skia/public/mojom/skcolorspace_primaries.mojom.h' file not found
#include "skia/public/mojom/skcolorspace_primaries.mojom.h"

Change-Id: I136d3e4e003c570e72568b78b7cf371d22436ea0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4064212
Reviewed-by: Alex Gough <ajgo@chromium.org>
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1077154}