GCC: fix undefined reference to ScrollView::SetContents()
Compiling Chrome fails at linking stage with an undefined reference:

../../ui/views/metadata/view_factory_internal.h:183:
 error: undefined reference to 'views::View*
 views::ScrollView::SetContents<views::View>
  (std::unique_ptr<views::View, std::default_delete<views::View> >)'

This was introduced with https://crrev.com/c/3257538.
Add an explicit specialization for ScrollView::SetContents().

Bug: 819294
Change-Id: Ie7089686ae1e997727277266103efe5b7c2bd40e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3265104
Reviewed-by: Allen Bauer <kylixrd@chromium.org>
Commit-Queue: Stephan Hartmann <stha09@googlemail.com>
Cr-Commit-Position: refs/heads/main@{#944148}