grit: Fix python3 error when showing warnings in verbose
If you trigger warnings about missing translations and have (-v)
verbose enabled you'll trigger this exception:

Traceback (most recent call last):
  File "chromium/src/tools/grit/grit.py", line 29, in <module>
    sys.exit(grit.grit_runner.Main(sys.argv[1:]))
  File "chromium/src/tools/grit/grit/grit_runner.py", line 314, in Main
    return toolobject.Run(options, args[1:])
  File "chromium/src/tools/grit/grit/tool/build.py", line 275, in Run
    self.Process()
  File "chromium/src/tools/grit/grit/tool/build.py", line 454, in Process
    self.VerboseOut(warnings)
  File "chromium/src/tools/grit/grit/tool/interface.py", line 56, in VerboseOut
    self.o.output_stream.write(text)
TypeError: write() argument must be str, not bytes

Avoid that by not encoding the warning string, nothing uses the encoded
string in any way.

Bug: 1305323
Change-Id: I5820311d57293f75d08a9d65ba37cf9efe6c4eff
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3515920
Reviewed-by: Lei Zhang <thestig@chromium.org>
Commit-Queue: Joel Klinghed <the_jk@opera.com>
Cr-Commit-Position: refs/heads/main@{#980158}