Revert "Remove no-longer-needed support for raw_ptr from cbor_extract::Element"
This reverts commit ebb70a6ec0bc755da61d7c7399c775371e7b68d9.

Reason for revert: caused build error
../../device/fido/cbor_extract_unittest.cc:87:7: error: constexpr variable 'kMakeCredParseSteps' must be initialized by a constant expression

Original change's description:
> Remove no-longer-needed support for raw_ptr from cbor_extract::Element
>
> This reverts commit 16f9768803e17c90901adce97b3153cfd39fdde2
> (aka. crrev.com/c/2224954). Since then, the automated rewriter got much
> smarter about dealing with templated functions, so no need to
> special-case it.
>
> Bug: 1080832
> Change-Id: I7b85558f313cd19de5da858396c711597f3e62a9
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3292392
> Reviewed-by: Łukasz Anforowicz <lukasza@chromium.org>
> Reviewed-by: Adam Langley <agl@chromium.org>
> Commit-Queue: Bartek Nowierski <bartekn@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#943506}

Bug: 1080832
Change-Id: Id4f65f96b084c0b7f94da89a2a61c60bd6576721
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3299715
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Łukasz Anforowicz <lukasza@chromium.org>
Reviewed-by: Bartek Nowierski <bartekn@chromium.org>
Reviewed-by: Adam Langley <agl@chromium.org>
Commit-Queue: Adam Langley <agl@chromium.org>
Cr-Commit-Position: refs/heads/main@{#945243}