Revert "Expose effects processor from MediaEffectsService up to content client"
This reverts commit fd87acad3272d2447b46a6bd5972378106cb62b1.

Reason for revert: Broke compile on (at least) lacros:

[184/1697] CXX obj/content/browser/browser/os_registration.o
FAILED: obj/content/browser/browser/os_registration.o
../../build/cros_cache/chrome-sdk/symlinks/arm-generic+15778.0.0+target_toolchain/bin/armv7a-cros-li...(too long)
In file included from ../../content/browser/attribution_reporting/os_registration.cc:5:
In file included from ../../content/browser/attribution_reporting/os_registration.h:14:
../../content/public/browser/content_browser_client.h:93:10: fatal error: 'services/video_effects/public/mojom/video_effects_processor.mojom-forward.h' file not found
93 | #include "services/video_effects/public/mojom/video_effects_processor.mojom-forward.h"

Original change's description:
> Expose effects processor from MediaEffectsService up to content client
>
> Additionally, add unit tests for VideoEffectsProcessor that mostly
> mimic the tests that have been written for Video Effects Manager. This
> also includes a basic fake implementation of VideoEffectsService and
> VideoEffectsProcessor.
>
> MediaEffectsService header file also now exposes a way to override the
> VideoEffectsService for testing, as otherwise it'd have to spawn a new
> utility process, and this is not desired in unittests.
>
> Bug: b:328118837
> Change-Id: Id096ecb09e0059d660896d743b80c991915dc4ff
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5353891
> Reviewed-by: Bryant Chandler <bryantchandler@chromium.org>
> Reviewed-by: Alex Moshchuk <alexmos@chromium.org>
> Commit-Queue: Piotr Bialecki <bialpio@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1278592}

Bug: b:328118837
Change-Id: I09a5fa42187e85cfb0a4d8394b5d61f970918b43
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5397951
Auto-Submit: Devlin Cronin <rdevlin.cronin@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Devlin Cronin <rdevlin.cronin@chromium.org>
Owners-Override: Devlin Cronin <rdevlin.cronin@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1278603}