Typescript: Handle obsolete ts files in ts_library(), avoid build errors
When a ts_library() is migrating JS to TS one file at a time (leveraging
allowJs) the following error can be thrown

"error TS5056: Cannot write file '...' because it would be overwritten
by multiple input files."

when building a later CL and then building an earlier CL (either in a
bot or locally), because stale TS files from the later CL are present
in the gen/ folder, and are erroneously picked up by the Typescript
compiler when building the earlier CL.

Bug: 1189595
Change-Id: Ia1905f34c57066b617599ab34c37cf5b8ea9d27d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2934619
Auto-Submit: dpapad <dpapad@chromium.org>
Commit-Queue: Rebekah Potter <rbpotter@chromium.org>
Reviewed-by: Rebekah Potter <rbpotter@chromium.org>
Cr-Commit-Position: refs/heads/master@{#888892}