Revert "[Refactor] Isolate constants used by Scrollable Shelf"
This reverts commit 09c28084f038d2016b82c551d9eee34192a995c9.

Reason for revert: Cause building error:
redefinition of 'kArrowButtonEndPadding'

TBR=jamescook@chromium.org

Original change's description:
> [Refactor] Isolate constants used by Scrollable Shelf
>
> This CL moves the constants used by the Scrollable Shelf to a separate
> header file in order to make those constants more accessible.
>
> In addition, GetArrowButtonSize(), a member function of Scrollable
> Shelf, is erased because it is never used.
>
> This CL should not introduce any UI differences.
>
> Bug: 1207378
> Change-Id: I84391f7de638bb1ab93c537c9528c3b3af665c42
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2883194
> Reviewed-by: James Cook <jamescook@chromium.org>
> Commit-Queue: Andrew Xu <andrewxu@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#882078}

Bug: 1207378
Change-Id: I360a7f4ac6bab79cdefbe341d7ef2d5366a16401
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2892420
Reviewed-by: Andrew Xu <andrewxu@chromium.org>
Reviewed-by: James Cook <jamescook@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Andrew Xu <andrewxu@chromium.org>
Cr-Commit-Position: refs/heads/master@{#882088}