Rerun UNKNOWN tests when there is a test failure.
Sometimes a test will have a failure and a crash, or a failure and then
the instrumentation process crashes. The test is recorded
as failure and not as a crash, thus preventing the other tests from being
ran.

For a real case example:
https://ci.chromium.org/p/chromium/builders/ci/android-pie-x86-rel/4624
in chrome_public_test_apk:

testhasHTMLOrStyledTextForNormalText (Failure)
which causes the following tests to all be marked flaky as they're
batched together
Flaky failure:IntentFilterUnitTest#testAboutUri (status NOTRUN,SUCCESS)
...

The
Process crashed while executing
testhasHTMLOrStyledTextForNormalText:
    java.lang.AssertionError: Single-use callback called multiple times.
    	at org.junit.Assert.fail(Assert.java:88)
   INSTRUMENTATION_STATUS: test=testhasHTMLOrStyledTextForNormalText
   INSTRUMENTATION_STATUS_CODE: -2
   INSTRUMENTATION_RESULT: shortMsg=Process crashed.

So the test had a java.lang.AssertionError which was marked as a failure
and at some time the instrumentation process crashed, but the crash
isn't recorded.


Bug: 1127935
Change-Id: I44edcbe1c018cf0830154ad4fd5111dcbd4cc4f9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2857214
Reviewed-by: Michael Thiessen <mthiesse@chromium.org>
Commit-Queue: benjamin joyce <bjoyce@chromium.org>
Cr-Commit-Position: refs/heads/master@{#877955}