Avoid printing a python exception after a rustc compile/link error
The error text should be the last thing visible in the terminal, and
we should just forward along the return value. This makes the rustc
wrapper script behave more like a direct call to rustc, which it's
intended to mimic.

A compiler error before:

error[E0433]: failed to resolve: use of undeclared crate or module `acrate`
   --> ../../base/rs_glue/future.rs:401:28
    |
401 |         block_on(async_cpp(acrate::rs_glue::ffi::TestAsyncImmediate(&mut ran)));
    |                            ^^^^^^ use of undeclared crate or module `acrate`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
Traceback (most recent call last):
  File "/home/danakj/s/c/src/build/rust/rustc_wrapper.py", line 133, in <module>
    sys.exit(main())
  File "/home/danakj/s/c/src/build/rust/rustc_wrapper.py", line 113, in main
    subprocess.run([args.rustc, *rustc_args], env=env, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '[PosixPath('../../third_party/android_rust_toolchain/toolchain/bin/rustc'), '-Clinker=../../third_party/llvm-build/Release+Asserts/bin/clang++', '--crate-name', 'base_rs_unittests', '../../base/lib.rs', '--crate-type', 'bin', '--cfg', 'feature="test"', '--test', '-Coverflow-checks=on', '-Z', 'dep-info-omit-d-target', '-Cembed-bitcode=no', '--cfg', 'rustc_version="rustc 1.56.1-dev"', '-g', '--edition=2021', '--emit=dep-info=base_rs_unittests.d,link', '-o', './base_rs_unittests', '-Clink-arg=-fuse-ld=lld', '-Clink-arg=-Wl,--fatal-warnings', '-Clink-arg=-Wl,--build-id', '-Clink-arg=-fPIC', '-Clink-arg=-Wl,-z,noexecstack', '-Clink-arg=-Wl,-z,relro', '-Clink-arg=-Wl,-z,now', '-Clink-arg=-Wl,--icf=all', '-Clink-arg=-Wl,--color-diagnostics', '-Clink-arg=-Wl,--no-call-graph-profile-sort', '-Clink-arg=-m64', '-Clink-arg=-no-canonical-prefixes', '-Clink-arg=-Werror', '-Clink-arg=-Wl,--gdb-index', '-Clink-arg=-rdynamic', '-Clink-arg=-nostdlib++', '-Clink-arg=--sysroot=../../build/linux/debian_sid_amd64-sysroot', '-Clink-arg=-Wl,-z,defs', '-Clink-arg=-Wl,--as-needed', '-Clink-arg=-pie', '-Clink-arg=-Wl,--disable-new-dtags', '-Clink-arg=-Wl,--no-gc-sections', '-Clink-arg=obj/build/rust/std/libstd.rlib', '-Clink-arg=obj/build/rust/std/libaddr2line.rlib', '-Clink-arg=obj/build/rust/std/libadler.rlib', '-Clink-arg=obj/build/rust/std/liballoc.rlib', '-Clink-arg=obj/build/rust/std/libcfg_if.rlib', '-Clink-arg=obj/build/rust/std/libcompiler_builtins.rlib', '-Clink-arg=obj/build/rust/std/libcore.rlib', '-Clink-arg=obj/build/rust/std/libgetopts.rlib', '-Clink-arg=obj/build/rust/std/libgimli.rlib', '-Clink-arg=obj/build/rust/std/libhashbrown.rlib', '-Clink-arg=obj/build/rust/std/liblibc.rlib', '-Clink-arg=obj/build/rust/std/libmemchr.rlib', '-Clink-arg=obj/build/rust/std/libminiz_oxide.rlib', '-Clink-arg=obj/build/rust/std/libobject.rlib', '-Clink-arg=obj/build/rust/std/libpanic_abort.rlib', '-Clink-arg=obj/build/rust/std/libpanic_unwind.rlib', '-Clink-arg=obj/build/rust/std/libproc_macro.rlib', '-Clink-arg=obj/build/rust/std/librustc_demangle.rlib', '-Clink-arg=obj/build/rust/std/libstd_detect.rlib', '-Clink-arg=obj/build/rust/std/libtest.rlib', '-Clink-arg=obj/build/rust/std/libunicode_width.rlib', '-Clink-arg=obj/build/rust/std/libunwind.rlib', '@base_rs_unittests.rsp']' returned non-zero exit status 1.
ninja: build stopped: cannot make progress due to previous errors.

A compiler error after:

error[E0425]: cannot find function `ablock_on` in this scope
   --> ../../base/rs_glue/future.rs:401:9
    |
165 | pub fn block_on<F: Future>(mut f: F) -> F::Output {
    | ------------------------------------------------- similarly named function `block_on` defined here
...
401 |         ablock_on(async_cpp(crate::rs_glue::ffi::TestAsyncImmediate(&mut ran)));
    |         ^^^^^^^^^ help: a function with a similar name exists: `block_on`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
ninja: build stopped: cannot make progress due to previous errors.

R=adetaylor@chromium.org

Bug: 1292082
Change-Id: Ieda187fcc84828fea94da63a97f17957a79dd773
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3429461
Reviewed-by: Nico Weber <thakis@chromium.org>
Commit-Queue: danakj chromium <danakj@chromium.org>
Cr-Commit-Position: refs/heads/main@{#965747}