Cast pointer diff in WTF::Vector::InsertAt to wtf_size_t
WTF::Vector::InsertAt(Iterator, U&&) does a pointer diff and pass it to
insert(wtf_size_t,U&&). We need to do a cast from pointer diff type to
wtf_size_t to use this function.

Without this, calling Vector::InsertAt() fails with:
error: implicit conversion loses integer precision: 'long' to 'wtf_size_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
 2129 |   insert(position - begin(), val);
      |   ~~~~~~ ~~~~~~~~~^~~~~~~~~
Previously, nothing called this and so the compiler never emitted
a warning.

Change-Id: Ied96164ff1869e53b1129d5028d20371d4fb6d70
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5734165
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Commit-Queue: Hao Liu <haoliuk@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1332583}